### ISSUE TITLE
M-x eaf-open

### ISSUE THREAD

**Issue by yssource** [manateelazycat/emacs-application-framework#1]
- 4.16.16-300.fc28.x86_64
- GNU Emacs 26.1
- Package python3-xlib-0.20-4.fc28.noarch is already installed
- Package python3-qt5-5.10-3.fc28.x86_64 is already installed

```
EAF process starting...
*eaf* exited abnormally with code 2

```

**Comment by manateelazycat** [comment]
Switch buffer *eaf*, and paste me the output from python

**Comment by yssource** [comment]
It seems my PyQt5 is not compatible with libQt5Core. 
And I'm trying to google find a solution.

```
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: /home/jimmy/.pyenv/versions/anaconda3-5.0.1/envs/devel/lib/python3.6/site-packages/PyQt5/../../../libQt5Network.so.5: symbol _Z14qt_safe_selectiP6fd_setS0_S0_PK8timespec version Qt_5 not defined in file libQt5Core.so.5 with link time reference

```
