### ISSUE TITLE
MacOS install?

### ISSUE THREAD

**Issue by watkinsr** [manateelazycat/emacs-application-framework#10]
Docs reference: 

sudo pacman -S python-xlib python-pyqt5 python-pymediainfo
sudo pip install git+https://github.com/wbsoft/python-poppler-qt5.git

Could somebody provide a way to install this on Mac via brew or any other given source?

Thanks,
Ryan

**Comment by manateelazycat** [comment]
Current still not support Mac OS, i will try test Mac in next week, then i will provide install steps on MacOS

**Comment by watkinsr** [comment]
Thanks @manateelazycat

**Comment by manateelazycat** [comment]
I have speed two days make eaf working on MacOS.

Sadly, it can't work, sorry.

Why this awesome framework can't works with MacOS?
There are mainly three obstacles:

I can't make dbus/python-dbus works on MacOS High Sierra
This framework need use X11 reparent to stick Qt5 window to emacs frame, but i don't know how to make X11 works on MacOS.
Qt5 QGraphicsView/QGraphicsScene can't work MacOS, specify QGraphicsVideoItem can't work.

**Comment by watkinsr** [comment]
@manateelazycat X11 can work on MacOS via XQuartz.

**Comment by NightMachinary** [comment]
@manateelazycat Can we have an open issue on macOS support, so that if it does get supported we can get notified?

**Comment by manateelazycat** [comment]
> @manateelazycat Can we have an open issue on macOS support, so that if it does get supported we can get notified?

macos cannot support in short time，it not necessary to open issue

**Comment by xihajun** [comment]
may I kindly ask if it is supporting macOS now?

**Comment by MatthewZMD** [comment]
Nope

**Comment by xihajun** [comment]
thanks

Matthew Zeng <notifications@github.com> 于2020年11月19日周四 下午2:36写道：

**Comment by manateelazycat** [comment]
> may I kindly ask if it is supporting macOS now?

EAF support MAC now

**Comment by mak1A4** [comment]
> > may I kindly ask if it is supporting macOS now?
> 
> EAF support MAC now

nice to hear :) how did you make it work? is there any documentation? thanks

**Comment by moritzschaefer** [comment]
@mak1A4 https://github.com/emacs-eaf/emacs-application-framework/wiki/macOS
