### ISSUE TITLE
Disable javascript for browser app

### ISSUE THREAD

**Issue by clemera** [manateelazycat/emacs-application-framework#100]
Hi, 

I would like to disable Javascript by default, I couldn't find any info how to configure that. 
Thank you for creating this!

**Comment by MatthewZMD** [comment]
What you are looking for is EWW

**Comment by clemera** [comment]
@MatthewZMD Thank you for the suggestion, I know about eww but I really want the "real thing"  to show webpages with colors and css applied.

**Comment by manateelazycat** [comment]
most website in this world need javascript

web page cannot render correctly if you disable javascript

**Comment by clemera** [comment]
@manateelazycat For security reasons I have javascript disabled by default in my day to day browser, too. I only enable it for websites I trust and would like to do the same with the eaf-browser app. I mostly want to use eaf-browser to read blog posts within my feed reader, those usually don't need javascript.

**Comment by MatthewZMD** [comment]
Sounds reasonable. We need to look into how to disable JavaScript on the PyQtWebEngine side, to provide the option by setting up a variable to control that using eaf-setq.

I don't have much time recently, if you want it very soon I suggest you start looking into it yourself. :)

Matthew

**Comment by clemera** [comment]
Okay thanks, I think I found the relevant documentation [here](https://doc.qt.io/qt-5/qml-qtwebengine-webenginesettings.html#javascriptEnabled-prop) but I don't know anything about how this magic works and how I would go about setting this.

**Comment by manateelazycat** [comment]
#### EAF Browser
Default browser enable plugin and JavaScript, to disable them, you can add something like the following to `.emacs`

```Elisp
(eaf-setq eaf-browser-enable-plugin "false")
(eaf-setq eaf-browser-enable-javascript "false")
```

**Comment by clemera** [comment]
@manateelazycat Thank you very much for your help and the fast implementation!
