### ISSUE TITLE
Pass data from python to elisp

### ISSUE THREAD

**Issue by clemera** [manateelazycat/emacs-application-framework#101]
I'm trying to write a little colorpicker with eaf using a javascript application and I succeeded getting the color value using:

    color = self.buffer_widget.web_page.executeJavaScript("window.selectedColor;")

But now I'm stuck because I can't figure out how I would return that value to the Elisp side. I can show it via `self.message_to_emacs.emit` but how would I set an elisp variable from the python side or return that value in another way to the elisp side?

**Comment by manateelazycat** [comment]
can you tell me the purpose of set elisp variable?
I can provide a new interface after I understand purpose

**Comment by clemera** [comment]
The color picker shows you a colormap from which you select a color. The javascript `window.selectedColor;` returns the hexcode of the color you selected. This can be useful when you want to insert a hexcode of a color in an Emacs buffer by visually selecting it. Here is an example how I would like to use it:


    (defvar eaf-selected-color ""
      "Hexcode of selected color.")

    (defun insert-hex-code ()
      (interactive)
      (eaf-open-colorpicker)
      (insert eaf-selected-color))

**Comment by clemera** [comment]
I want to select the hexcode of a color by selecting it visually using a new command `eaf-open-colorpicker`. Here is an example how imagine using it:

    (eaf-open-colorpicker)
    ;; the app window get focused and the use has to select a color, then quit the app
    ;; with q, afterwards some variable for example `eaf-selected-color' should
    ;; contain the hexcode of color the user selected so one can insert it
    (insert eaf-selected-color)

**Comment by MatthewZMD** [comment]
We should reuse the same alist `eaf-var-list` for this feature, I think something similar to `self.message_to_emacs.emit` should do the job.

**Comment by manateelazycat** [comment]
> We should reuse the same alist `eaf-var-list` for this feature, I think something similar to `self.message_to_emacs.emit` should do the job. Clemens Radermacher <notifications@github.com> writes:
> […](#)
> I want to select the hexcode of a color by selecting it visually using a new command eaf-open-colorpicker. Here is an example how imagine using it: (eaf-open-colorpicker) ;; the app window get focused and the use has to select a color, then quit the app ;; with q, afterwards some variable for example `eaf-selected-color' should ;; contain the hexcode of color the user selected so one can insert it (insert eaf-selected-color) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

eaf-var-list is variable list use to store customize option and pass to python.

I think @clemera want a interface that set any value of Emacs from python side.

**Comment by MatthewZMD** [comment]
> I think @clemera want an interface that set any value of Emacs from python side.

Yes, when that value is sent to Emacs, it should be saved to `eaf-var-list` too. Essentially that list will store all variables that will be synced and shared across elisp and python, to prevent possible chaos in the future.

**Comment by clemera** [comment]
Maybe even something like:

    self.eval_in_emacs("<elispcode>")

This would for other use cases, too. Like saving some buffer after interacting with an app or something similar.

**Comment by manateelazycat** [comment]
In Python side, use ```self.set_emacs_var.emit("eaf-hello", "cool")```

**Comment by clemera** [comment]
Thanks!

**Comment by clemera** [comment]
@manateelazycat BTW, I will try to contribute some code in the future to make adding apps easier. It would be great if people could write additional apps and release them without modifying code in eaf.el (for keybindings and stuff).

**Comment by MatthewZMD** [comment]
> It would be great if people could write additional apps and release them without modifying code in eaf.el

More enhancements (and refactoring) can be done on this part for sure

**Comment by MatthewZMD** [comment]
> In Python side, use self.set_emacs_var.emit("eaf-hello", "cool")

Also, documentation of this should be added to HACKING and README :)
