### ISSUE TITLE
Call elisp functions from python

### ISSUE THREAD

**Issue by clemera** [manateelazycat/emacs-application-framework#103]
Sorry for being on an issue spree here. I managed to set the variable I talked about in #101 and it works great, thanks again! Here is the code I use:

    def set_color(self):
        color = self.buffer_widget.web_page.executeJavaScript("window.selectedColor;")
        self.set_emacs_var.emit("eaf-colorpicker-color", str(color))

Now I would also like to quit the app (or better bury the buffer) after that and automatically insert the value of `eaf-colorpicker-color` into the buffer that the app was started from. How should that be done?

I think closing the app from the python side and having a quit hook would be a way. Or adding the ability to call arbitrary elisp functions from the python side.

**Comment by clemera** [comment]
For now I just advice `set_color` like this which works, too:

    (define-advice set_color (:after (&rest args) handle-exit)
      (bury-buffer)
      (insert eaf-colorpicker-color))

**Comment by manateelazycat** [comment]
Try ```self.eval_in_emacs.emit('''(message "hello")''') ``` , I haven't test eval_in_emacs interface.

**Comment by clemera** [comment]
Hey, thanks I just was implementing it myself using your previous commit as a template ;)

**Comment by clemera** [comment]
@manateelazycat  I just tested it and it works as intended!

**Comment by manateelazycat** [comment]
Enjoy and looking forward to your color picker plugin. ;)

**Comment by clemera** [comment]
I will let you know when its ready, do you want it to be included to `emacs-application-framework`? I'm using the js app from [here](https://github.com/osener/emacs-webkit-color-picker/blob/765cac80144cad4bc0bf59025ea0199f0486f737/color-picker.html) which is MIT licensed.

**Comment by MatthewZMD** [comment]
> which is MIT licensed.

I don't see a problem here, iirc MIT is compatible with GPL

**Comment by manateelazycat** [comment]
> I will let you know when its ready, do you want it to be included to `emacs-application-framework`? I'm using the js app from [here](https://github.com/osener/emacs-webkit-color-picker/blob/765cac80144cad4bc0bf59025ea0199f0486f737/color-picker.html) which is MIT licensed.

yes，welcome to pr

**Comment by MatthewZMD** [comment]
> Try self.eval_in_emacs.emit('''(message "hello")''') , I haven't test eval_in_emacs interface.

I think HACKING.md should be updated with this new feature :)
