### ISSUE TITLE
[HELP REQUEST] building from source, didn't found sip and pyqt5

### ISSUE THREAD

**Issue by mmohammadi-9812** [manateelazycat/emacs-application-framework#104]
Hi, I didn't know how to fix this problem, and I don't think anywhere else I would find any help, so I thought asking here would help me better.
When I try to build source, pyqt/cmake/FindSIP.py and pyqt/cmake/FindPyQt5.py use python2.7/dist-packages to look for packages. At first I didn't saw the output carefully, and I thought the problem was with sip and pyqt5 and I built them from source, but after it didn't work again, I found the problem. I searched to see if pyqt5 was available for python2.7, but it seems it requires python3.4 or later.
I thought about changing python to provide python3 instead of python2, but I don't know if it's true. Anyway, if any one could help me, It'd be great.

**Comment by MatthewZMD** [comment]
> I thought about changing python to provide python3 instead of python2, but I don't know if it's true.

Yes, that's true. It supports python3 only. I also suggest you migrate to python3 asap. The pyhon2 support will end within [30](https://pythonclock.org/) days.

**Comment by manateelazycat** [comment]
please use pip install dependences
