### ISSUE TITLE
ImportError: No module named app.browser.buffer

### ISSUE THREAD

**Issue by mgcyung** [manateelazycat/emacs-application-framework#11]
Traceback (most recent call last):
  File "/home/magic/.emacs.d/elpa-alone/emacs-application-framework/core/eaf.py", line 35, in <module>
    from app.browser.buffer import BrowserBuffer
ImportError: No module named app.browser.buffer

**Comment by mgcyung** [comment]
The whole repo is already cloned into directory "/home/magic/.emacs.d/elpa-alone/emacs-application-framework".

**Comment by Compro-Prasad** [comment]
You might have sorted the imports?

**Comment by mgcyung** [comment]
> You might have sorted the imports?

Do you mean imports in eaf.py? It is as follows
[code]
from PyQt5.QtWidgets import QApplication
from dbus.mainloop.glib import DBusGMainLoop
from fake_key_event import fake_key_event
from pymediainfo import MediaInfo
from utils import file_is_image, file_is_video
from view import View
import dbus
import dbus.service

import os,sys,inspect
current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent_dir = os.path.dirname(current_dir)
sys.path.insert(0, parent_dir)
from app.browser.buffer import BrowserBuffer
from app.imageviewer.buffer import ImageViewerBuffer
from app.videoplayer.buffer import VideoPlayerBuffer
from app.pdfviewer.buffer import PdfViewerBuffer
from app.demo.buffer import DemoBuffer
[/code]

**Comment by manateelazycat** [comment]
Can you add below code in eaf.py?

print(parent_dir)

Just put it after "parent_dit = os.path.dirname(current_dir)

I need see what's it parent_dir

**Comment by mgcyung** [comment]
> Can you add below code in eaf.py?
>
> print(parent_dir)
>
> Just put it after "parent_dit = os.path.dirname(current_dir)
>
> I need see what's it parent_dir

The parent_dir is
"/home/magic/.emacs.d/elpa-alone/emacs-application-framework"
as shown in buffer "eaf"

/home/magic/.emacs.d/elpa-alone/emacs-application-framework
Traceback (most recent call last):
  File "/home/magic/.emacs.d/elpa-alone/emacs-application-framework/core/eaf.py", line 36, in <module>
    from app.browser.buffer import BrowserBuffer
ImportError: No module named app.browser.buffer

**Comment by manateelazycat** [comment]
@mgcyung I see your problem.

I just update new patch to fix this problem: https://github.com/manateelazycat/emacs-application-framework/commit/66e51af1f855e106f7a968ca630094d6f3f71493

Can you help me test it?

Thank for your feedback.

**Comment by manateelazycat** [comment]
@mgcyung I see your problem, I have write new patch to fix this problem: https://github.com/manateelazycat/emacs-application-framework/commit/2cf99b2b3750944ec21ae1dd704cf57bf66c2c83

Can you update repo to newest and try again?

Thanks for your feedback!

**Comment by mgcyung** [comment]
@manateelazycat

It seems the problem still exists

Traceback (most recent call last):
  File "/home/magic/.emacs.d/elpa-alone/emacs-application-framework/eaf.py", line 23, in <module>
    from app.browser.buffer import BrowserBuffer
ImportError: No module named app.browser.buffer

**Comment by Compro-Prasad** [comment]
@mgcyung What OS and python version are you using?

**Comment by manateelazycat** [comment]
@mgcyung 

Open python in terminal
Paste below code in python shell:

from PyQt5.QtWebKitWidgets import QWebView, QWebPage


What's output?

**Comment by mgcyung** [comment]
The OS is Gentoo and the Python version is 2.7.14. The system
information is as follows: 

Portage 2.3.40 (python 2.7.14-final-0, default/linux/amd64/17.0, gcc-7.3.0, glibc-2.26-r7, 4.14.52-gentoo x86_64)
=================================================================
System uname: Linux-4.14.52-gentoo-x86_64-Intel-R-_Core-TM-_i5-7200U_CPU_@_2.50GHz-with-gentoo-2.4.1
KiB Mem:     8049552 total,     89316 free
KiB Swap:    8388604 total,   8319772 free
Timestamp of repository gentoo: Tue, 03 Jul 2018 00:00:01 +0000
Head commit of repository gentoo: 12d29e46359700c563ed2f064bb895535d76a749
Head commit of repository gentoo-snappy: 0ea79c799ebe1bc6cd924b9dd707b710eea24e83

sh bash 4.4_p12
ld GNU ld (Gentoo 2.30 p2) 2.30.0
app-shells/bash:          4.4_p12::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.24.3-r1::gentoo
dev-lang/python:          2.7.14-r1::gentoo, 3.5.5::gentoo, 3.6.5::gentoo
dev-util/cmake:           3.9.6::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.4.1-r2::gentoo
sys-apps/openrc:          0.34.11::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.11.6-r3::gentoo, 1.15.1-r2::gentoo
sys-devel/binutils:       2.30-r2::gentoo
sys-devel/gcc:            4.9.4::gentoo, 7.3.0-r3::gentoo
sys-devel/gcc-config:     1.8-r1::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.2.1::gentoo
sys-kernel/linux-headers: 4.13::gentoo (virtual/os-headers)
sys-libs/glibc:           2.26-r7::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-metamanifest: yes
    sync-rsync-extra-opts: 
    sync-rsync-verify-max-age: 24

gentoo-snappy
    location: /usr/local/portage/gentoo-snappy
    sync-type: git
    sync-uri: https://github.com/zyga/gentoo-snappy.git
    masters: gentoo
    priority: 50

gentoo-zh
    location: /var/lib/layman/gentoo-zh
    sync-type: laymansync
    sync-uri: git://github.com/microcai/gentoo-zh.git
    masters: gentoo
    priority: 50

science
    location: /var/lib/layman/science
    sync-type: laymansync
    sync-uri: https://anongit.gentoo.org/git/proj/sci.git
    masters: gentoo
    priority: 50

steam-overlay
    location: /var/lib/layman/steam-overlay
    sync-type: laymansync
    sync-uri: https://github.com/anyc/steam-overlay.git
    masters: gentoo
    priority: 50

stuff
    location: /var/lib/layman/stuff
    sync-type: laymansync
    sync-uri: https://github.com/istitov/stuff.git
    masters: gentoo
    priority: 50

unity-gentoo
    location: /var/lib/layman/unity-gentoo
    sync-type: laymansync
    sync-uri: https://github.com/shiznix/unity-gentoo
    masters: gentoo
    priority: 50

wizard
    location: /var/lib/layman/wizard
    sync-type: laymansync
    sync-uri: https://github.com/m31271n/wizard.git
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/easy-rsa /usr/share/gnupg/qualified.txt /var/bind"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -pipe"
DISTDIR="/usr/portage/distfiles"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync multilib-strict news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://mirrors.ustc.edu.cn/gentoo http://mirrors.xmu.edu.cn/gentoo http://distfiles.gentoo.org http://www.ibiblio.org/pub/Linux/distributions/gentoo"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j3"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X acl amd64 berkdb bindist bzip2 cli crypt cxx dri fortran gdbm iconv ipv6 libtirpc modules multilib ncurses nls nptl openmp pam pcre readline seccomp ssl tcpd tk unicode xattr zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon plan sheets stage words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev synaptics wacom" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6 php7-0" POSTGRES_TARGETS="postgres9_5 postgres10" PYTHON_SINGLE_TARGET="python3_5" PYTHON_TARGETS="python2_7 python3_5" RUBY_TARGETS="ruby23" SANE_BACKENDS="hp" USERLAND="GNU" VIDEO_CARDS="intel i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, LINGUAS, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

**Comment by mgcyung** [comment]
There is no output. QWebView and QWebPage are imported.

**Comment by manateelazycat** [comment]
@mgcyung It's so strange, i don't know why you can import app.browser.buffer

**Comment by Compro-Prasad** [comment]
@mgcyung What if you use python3 over python2?

**Comment by manateelazycat** [comment]
@mgcyung Please use Python3, don't use Python2

**Comment by manateelazycat** [comment]
@mgcyung I don't know how to fixed your problem, you need switch to Python3 and try.

Anyway, i add new patch https://github.com/manateelazycat/emacs-application-framework/commit/0d934ddda30125cf936d27650e11c3dc49beaad6

Make you still can use eaf even you can't import some plugin.

**Comment by manateelazycat** [comment]
@mgcyung I think pyqt5 install in Python3 env, but you system default python is Python2.

I will close this issue.

If you still have problem after you switch system default Python to Python3, feel free to re-open this issue.
