### ISSUE TITLE
Commands Like M-: and M-! get prompted twice while in any EAF program

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/emacs-application-framework#110]
I noticed a weird bug, while in any EAF program's buffer and you try `M-:` or `M-!` invoking `eval-expression` or `shell-command`, it gets evaluated but the prompt appeared again right after. 

I don't have too much time this weekend to debug it, posting it here for now.

**Comment by MatthewZMD** [comment]
Interactive functions like `eaf-open` also behave this way.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/snails/commit/44f77cc35f75e623a6e2a419629a16ec9b9c3fbf related bug, I believe the problem is recent eaf-monitor-key-event patch introduced.

**Comment by manateelazycat** [comment]
我裸看代码的哈，没有测试，下面是我的推论：

1. eaf-monitor-key-event 这个事件过滤函数，在 https://github.com/manateelazycat/emacs-application-framework/blob/901f2e317eebc92424acadedf87feb04648bd4dd/eaf.el#L558 这里的逻辑，当按键不是EAF插件的快捷键的时候，执行一次这个按键对应的命令。

2. https://github.com/manateelazycat/emacs-application-framework/blob/901f2e317eebc92424acadedf87feb04648bd4dd/eaf.el#L569 eaf-monitor-key-event 每次执行完成后，会重新把 eaf-monitor-key-event 这个事件函数勾在 pre-command-hook 上，避免按键出异常后 eaf-monitor-key-event 这个函数无法执行的问题

3. EAF的 eaf-monotor-key-event 这个函数每一个事件循环只能执行一次，如果执行两次就会导致按键被调用了两次，就像我最近的修复的 https://github.com/manateelazycat/snails/commit/44f77cc35f75e623a6e2a419629a16ec9b9c3fbf 问题，以为是 snails 的问题，今天回想起来本质是 EAF 的问题

4. 基于上面的逻辑推理，eaf-monitor-key-event 在 https://github.com/manateelazycat/emacs-application-framework/blob/901f2e317eebc92424acadedf87feb04648bd4dd/eaf.el#L388 被调用了

5. 我认为是 https://github.com/manateelazycat/emacs-application-framework/pull/96/files 这个补丁引起的，为了显示 C-h m 的帮助，错误的借用了 eaf-monitor-key-event 的作用导致的

**Comment by clemera** [comment]
One can add `eaf-monitor-key-event` buffer locally to `pre-command-hook` of the eaf-mode buffer. This way it does not unnecessary run outside eaf buffers and this fixes this problem. Do you want me to PR?

**Comment by manateelazycat** [comment]
> One can add `eaf-monitor-key-event` buffer locally to `pre-command-hook` of the eaf-mode buffer. This way it does not unnecessary run outside eaf buffers and this fixes this problem because it runs inside minibuffer and can not handle minibuffer quit signal. Do you want me to PR?

Sure, thanks

**Comment by manateelazycat** [comment]
@MatthewZMD I found bug reason is like @clemera said, eaf-monitor-key-event should running in local of eaf-mode buffer, I have fix this bug in newest version.

**Comment by clemera** [comment]
@manateelazycat  I think it is still called twice

**Comment by manateelazycat** [comment]
> @manateelazycat I think it is still called twice

I have test it, (call-interactively (key-binding key)) won't call twice.

Did you found except example?

**Comment by clemera** [comment]
If I try `M-:` or `M-!` it is still invoked twice. Another problem I found is if you have multiple app buffers open the `eaf-mode-map` gets overridden. Try open a pdf and then an html and do `C-h m` on both. I think maybe it's best to avoid using `pre-command-hook` and have a buffer local keymap for each app which handles the commands directly (instead of having an empty dummy command let the command handle the keypress). I'm currently working on it.

**Comment by manateelazycat** [comment]
> If I try `M-:` or `M-!` it is still invoked twice. Another problem I found is if you have multiple app buffers open the `eaf-mode-map` gets overridden. Try open a pdf and then an html and do `C-h m` on both.
> 
> I think maybe it's best to avoid using `pre-command-hook` and have a buffer local keymap for each app which handles the commands directly (instead of having an empty dummy command let the command handle the keypress). I'm currently working on it.

The Key is we need use ```(eaf-call "send_key" buffer-id key-desc)``` send single-key event from Elisp to Python, otherwise browser can't input character, so we need pre-command-hook hook to find Emacs event is self-insert-command.

If we use local keymap, we can't handle above situation, because we don't know every character in different country.

**Comment by clemera** [comment]
Okay I understand, but maybe could we remap self-insert-command instead? Like:

    (define-key eaf-mode-map [remap self-insert-command] 'eaf-handle-input-key)


    (defun eaf-handle-input-key ()
      (interactive)
      (eaf-call "send_key"
                buffer-id
                (key-description (this-command-keys-vector))))

**Comment by manateelazycat** [comment]
> Okay I understand, but maybe could we remap self-insert-command instead? Like:
> 
> ```
> (define-key eaf-mode-map [remap self-insert-command] 'eaf-handle-input-key)
> 
> 
> (defun eaf-handle-input-key ()
>   (interactive)
>   (eaf-call "send_key"
>             buffer-id
>             (key-description (this-command-keys-vector))))
> ```

I don't think only local map can replace eaf-monitor-key-event , self-insert-command just an example.
