### ISSUE TITLE
Positioning widgets

### ISSUE THREAD

**Issue by clemera** [manateelazycat/emacs-application-framework#118]
I'm trying to learn a bit about PyQt programming and follow the [tutorial](http://zetcode.com/gui/pyqt5/widgets/) you recommended. However I have problems getting started.

Here is my code:

    from PyQt5.QtGui import QColor
    from PyQt5.QtWidgets import QPushButton, QCheckBox
    from PyQt5.QtCore import Qt
    from core.buffer import Buffer

    class AppBuffer(Buffer):
        def __init__(self, buffer_id, url, arguments):
            Buffer.__init__(self, buffer_id, url, arguments, True, QColor(0, 0, 0, 255))

            cb = QCheckBox('Show title')
            cb.stateChanged.connect(self.changeTitle)
            cb.move(200, 20)
            self.add_widget(cb)

        def changeTitle(self, state):

            if state == Qt.Checked:
                self.eval_in_emacs.emit("(message \"on\")")
            else:
                self.eval_in_emacs.emit("(message \"off\")")

The ticking works and message on/off is shown, but cb.move(200, 20) seems to have no effect. How can I position the checkbox?

**Comment by manateelazycat** [comment]
move function is use for toplevel window, move to position that relative to screen coordinate.

You should Google Qt widget margin, use margin or padding adjust checkbox position with parent widget.

**Comment by clemera** [comment]
Okay thanks, I think I have to learn a bit more, maybe I should start with regular PyQt code to understand better.

**Comment by manateelazycat** [comment]
> Okay thanks, I think I have to learn a bit more, maybe I should start with regular PyQt code to understand better.

http://zetcode.com/gui/pyqt5/ this is quick book to study PyQt, then you can found EAF is same as PyQt knowledge.
