### ISSUE TITLE
exited abnormally with code 1

### ISSUE THREAD

**Issue by mmohammadi-9812** [manateelazycat/emacs-application-framework#119]
I've successfully installed & built dependencies, but it gives me this error:
```
Making completion list...
EAF process starting...
Opening eaf-demo with EAF-demo...
*eaf* exited abnormally with code 1

You can run the command ‘eaf-open-demo’ with M-x -dem RET
*eaf* exited abnormally with code 1
```
 and I don't know why it gives me this error. It gives this error for every `eaf-` function I run. I tried to set `debug-on-error` to `t`, but didn't help me. Is there any way I could debug it so I could find why I'm getting this error?
Any help would be appreciated.
PS: I'm using elementary OS 5.1 Hera, and I've built GNU Emacs  27.0.50 from source.

**Comment by MatthewZMD** [comment]
> EAF process starting...
> Opening eaf-demo with EAF-demo...
> *eaf* exited abnormally with code 1

This error message indicates that it could be a problem on the Python side. Check the *eaf* buffer.

Most of the time I encounter this issue is that the pip packages didn't install correctly for some reason, just reinstall a few times and it should be fixed.

Sometimes it may also be incompatibility with DE or WM, what are you using?

**Comment by manateelazycat** [comment]
Please check buffer *eaf* for error information.

**Comment by mmohammadi-9812** [comment]
@MatthewZMD I'm using default elementary WM, gala and pantheon DE which according to [wikipedia](https://en.wikipedia.org/wiki/Elementary_OS#Pantheon_desktop_environment) is built on gnome. Also, you were right, I have a problem with eaf.py file: `ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'`
which I don't why happens, because I have all python dependencies:
```
dbus-python==1.2.12
grip==4.5.2
PyMuPDF==1.16.9
PyQt5==5.13.2
PyQt5-sip==4.19.19
PyQtWebEngine==5.13.2
python-xlib==0.26
qrcode==6.1
```
I think it must be a problem with my PyQt5, which I had some problem with it before. Anyway, thanks for help.
