### ISSUE TITLE
Full-blown vs keyboard oriented browser/nav

### ISSUE THREAD

**Issue by fngx** [manateelazycat/emacs-application-framework#12]
Hi, thank you for bringing eaf.

Regarding browser navigation (and perhaps other plugins), are you planning a GUI approach as well
(URI / reload / navigation buttons);

or whether a strictly keyboard approach (vimium..)

perhaps both ..?

**Comment by manateelazycat** [comment]
i will build something like vimium.

but i need make eaf works on mac.

look my todolist in git
