### ISSUE TITLE
Idea: Popup Scratch-like buffer to edit text

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/emacs-application-framework#131]
For example, when we want to edit text in EAF browser, we can open a small popup buffer that allows the user to edit text the familiar Emacs-way. User enter `<return>` or `C-c c` to finish edit, then EAF takes the string and inserts it into EAF browser.

This introduces a couple benefits

1.  Emacs is very powerful when comes to editing text, `C-a`, `C-e`, `M-f`, etc. Also, auto-completion features like company-mode and TabNine can come in handy. 
2. It would be very troublesome to implement same features again in EAF Browser
3. We can eliminate all these code in `browser.py`
```
qt_key_dict = {
    '''a''': Qt.Key_A,
    '''b''': Qt.Key_B,
    '''c''': Qt.Key_C,
    '''d''': Qt.Key_D,
    '''e''': Qt.Key_E,
    '''f''': Qt.Key_F,
    '''g''': Qt.Key_G,
    '''h''': Qt.Key_H,
    '''i''': Qt.Key_I,
    '''j''': Qt.Key_J,
    '''k''': Qt.Key_K,
    '''l''': Qt.Key_L,
    and so on ......
```

;)

**Comment by clemera** [comment]
I use [edit-indirect](https://github.com/Fanael/edit-indirect) for such purposes. It's a great package where you can edit dosctrings in text-mode for example. But we need the ability to send text to the python side for insertion.

**Comment by manateelazycat** [comment]
I don't think it's a good idea.

Because browser is complicated that most every site use JavaScript, many widget is not a simple plain HTML tag.
Such as Google's search suggestion completion list won't show if you use this way.

Anyway, If you really want this, I think best way is write JavaScript for EAF browser:

1. Press key to popup Emacs buffer like Chrome extension "Atomic Chrome" does.
2. Edit content in Emacs buffer.
3. C-c C-k to cancel.
4. C-c C-c commit Emacs buffer content to EAF brower

**Comment by manateelazycat** [comment]
> I use [edit-indirect](https://github.com/Fanael/edit-indirect) for similar purposes. It's a great package where you can edit dosctrings in text-mode for example. We could probably reuse some parts of it. But we need the ability to send text to the python side for insertion.

We need write JavaScript code for EAF browser, like "Atomic Chrome" extension does for Google Chrome

**Comment by clemera** [comment]
> We need write JavaScript code for EAF browser

I found keys are send like this:

    QApplication.sendEvent(widget, key_press)

Couldn't we iterate over the text and send key presses like this?

**Comment by manateelazycat** [comment]
> > We need write JavaScript code for EAF browser
> 
> I found keys are send like this:
> 
> ```
> QApplication.sendEvent(widget, key_press)
> ```
> 
> Couldn't we iterate over the text and simulate key presses like this? Maybe slow and hacky but could work well enough.

The problem is not here, but you have to know a question: whether the current cursor in the input area?
You cannot use sendEvent insert anything if cursor not in input area.

**Comment by clemera** [comment]
When the text is typed in normal Emacs buffer and types `C-c C-c` could we bury the buffer and focus the input area again before sending events?

**Comment by manateelazycat** [comment]
> When the text is typed in normal Emacs buffer and the user invokes `C-c C-c` could we bury the buffer and focus the input area again before sending events?

qt only can focus widget, only javascript know whether cursor in input area, only javascript know how to focus input area

**Comment by clemera** [comment]
As far as I understand when the input field is focused when the user invokes the command and later we switch back to eaf buffer it would still be focused, unless the user manually unfocused it.

**Comment by manateelazycat** [comment]
> As far as I understand when the input field is focused when the user invokes the command then later when we switch back to eaf buffer it would still be focused, unless the user manually unfocused it.

you can try Atomic chrome extension first

we should not make sync input text base on bury and focus must in input area

**Comment by clemera** [comment]
Okay, no problem just wanted to discuss ideas. I don't know how to install extensions using the eaf browser.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/emacs-application-framework/commit/99db0b2d85b63743758778436fe0f1ec089b46ee

Done.
