### ISSUE TITLE
Idea: pass location to external application

### ISSUE THREAD

**Issue by clemera** [manateelazycat/emacs-application-framework#134]
Each buffer could have variable which tracks current location and can be passed to external commands (I'm not sure we should use `buffer-file-name` here because it could have weird side effects. 

After we have this feature we could use this for example to pass that location to any external command like youtube-dl in browser app or pdfsam in pdf app.

**Comment by manateelazycat** [comment]
With newest version, we can use eaf-call "call_function" get location from Python, then pass to shell-command to call external application.

```Elisp
(with-current-buffer (current-buffer)
 (shell-command (format "youtube-dl %s" (eaf-call "call_function" eaf--buffer-id "get_localtion")))
```

**Comment by manateelazycat** [comment]
location variable welcome to PR

**Comment by clemera** [comment]
Great thanks! For location one can use get_bookmark
