### ISSUE TITLE
Default navigation bindings to Emacs-like instead of vim-like?

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/emacs-application-framework#138]
Should we default pdf-viewer's navigation (i.e `scroll_up`, `scroll_down`, etc.) to Emacs's `C-n`, `C-p` instead of the current vim-like bindings (i.e `h`, `j`, `k`, `l`)? 
It will make the behavior consistent with the current browser's default binding too. After all, this is an Emacs package ;)

For any user interested to use the vim-like bindings, they can easily configure it using `eaf-bind-key` in their own config file.

**Comment by manateelazycat** [comment]
no，i like vim keys
