### ISSUE TITLE
Rename all EAF bindings to have eaf- prefix or don't use it at all

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/emacs-application-framework#140]
Right now, this line
```
do (let ((dummy (intern (format "eaf-%s" fun))))
```
will put an `eaf-` prefix for all dummy functions. 

There is no functionality issue with this approach, however, the `*Help*` buffer can give misinformation.

For example,
```
eaf-switch_to_read_mode is an interactive Lisp closure.

(eaf-switch_to_read_mode)

This Lisp function is a placeholder, the actual function will be handled on the Python side.

Use ‘eaf-execute-app-cmd’ if you want to execute this command programmatically.
Please ONLY use ‘eaf-bind-key’ to edit EAF keybindings!
```

The user, upon reading the last line, might try to use `eaf-bind-key` function with the variable name  on the first line, which is `eaf-switch_to_read_mode`. This will break because they're supposed to  call `eaf-bind-key` with the variable name `switch_to_read_mode` instead. 

Therefore, I propose we either rename *all* EAF bindings to have a `eaf-` prefix, or we don't format with the prefix at all using `(format "eaf-%s" fun)`

**Comment by manateelazycat** [comment]
Check https://github.com/manateelazycat/emacs-application-framework/commit/2a833fab1991085c33f1ac00d07be2066534276f
