### ISSUE TITLE
Always load path no matter what I type in

### ISSUE THREAD

**Issue by FirstLoveLife** [manateelazycat/emacs-application-framework#15]
### Environment
```
archlinux 福 ~/.emacs.d/elisp 
6620 ◯ : emacs --version                                                                                                                    
GNU Emacs 26.1
```

```
Linux archlinux 4.14.21-1-MANJARO #1 SMP PREEMPT Fri Feb 23 00:01:40 UTC 2018 x86_64 GNU/Linux
```

### install

`sudo pacman -S python-xlib python-pyqt5 python-pymediainfo ` has no problem. 

```
archlinux 福 ~/.emacs.d/elisp 
6625 ◯ : sudo pip install PyMuPDF                                                                                                         ⏎ 

Requirement already satisfied: PyMuPDF in /usr/lib/python3.6/site-packages (1.13.11)
picard 2.0.0.dev7 requires PyQt5, which is not 
```

### M-x eaf-open

When I type www.baidu.com in minbuffer, like the gif below: 

![peek 2018-07-04 11-52](https://user-images.githubusercontent.com/37442588/42255910-c47a8696-7f80-11e8-82e6-6b997486eb24.gif)

First, it will load my current directory in minbuffer automatically, then I remove the path and input `www.baidu.com`. But it is still regarded as path, not url. 

```
Quit
Kill f5635b35-90df-ba0c-5634-405c82c57974
Path /run/media/czxyl/0C3203E00C3203E0/book/book/www.baidu.com not exists.
Mark set
```

BTW, image view and videw player work fine, while `demo`(eaf-demo) and `camera`(eaf-camera) also fail because the are regrded as path: 
`Path /run/media/czxyl/0C3203E00C3203E0/book/book/eaf-demo not exists.`

**Comment by manateelazycat** [comment]
@FirstLoveLife Can you just try M-x eaf-open ? don't use it in helm

**Comment by FirstLoveLife** [comment]
@manateelazycat I have tried just now, nothing changed:
![baidu](https://user-images.githubusercontent.com/37442588/42259711-305b9270-7f94-11e8-9aff-38f7f6b7a8fb.gif)
