### ISSUE TITLE
Don't `eval_js` for browser movements?

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/emacs-application-framework#154]
Code snippet from `browser_buffer.py`
```python
    def scroll_up(self):
        self.eval_js("window.scrollBy(0, 50)")

    def scroll_down(self):
        self.eval_js("window.scrollBy(0, -50)")

    def scroll_up_page(self):
        self.eval_js("window.scrollBy(0, screen.height)")

    def scroll_down_page(self):
        self.eval_js("window.scrollBy(0, -screen.height)")
```
Instead of manually calculate scrolling up/down distances, maybe it's better to convert the signal to `<up>/<down>` that will be sending to QtWebBrowser instead? Because QtWebBrowser already understands what <up>/<down> means

**Comment by manateelazycat** [comment]
no,send key is hacking way

use javascript is normal implement

**Comment by MatthewZMD** [comment]
>  use javascript is normal implement

We have given the user the ability to turn off javascript, would `eval_js` work without javascript?

**Comment by MatthewZMD** [comment]
>  would eval_js work without javascript?

Upon testing, when I set
```
(eaf-setq eaf-browser-enable-javascript "false")
```

The existing functions that uses `eval_js` all broke

**Comment by manateelazycat** [comment]
if user disable javascript，feature is limit，ignore this

**Comment by MatthewZMD** [comment]
> feature is limit，ignore this

I don't think we should ignore this. From a user's perspective, the ability to scroll pages shouldn't be affected by whether javascript has turned on or not

**Comment by manateelazycat** [comment]
if cusor in input area,fake_key_event is broken

**Comment by MatthewZMD** [comment]
Okay, instead of using the hacky `send_key` way, we can explore possible solutions to move the browser that might be provided by Qt
