### ISSUE TITLE
eaf-open broken in Kali Linux

### ISSUE THREAD

**Issue by Qquanwei** [manateelazycat/emacs-application-framework#16]
Stage:
`sudo apt install python-xlib python-pyqt5 python-pymediainfo` success
`sudo pip install PyMuPDF grip`  success
`emacs -Q`
`M-x eaf-open` with `~/doc/RealWorldHaskell.pdf`

Output *Message*:
```
EAF process starting...
*eaf* exited abnormally with code 1
```

When I manual execute `python ~/.emacs.d/emacs-application-framework/app/pdfviewer/buffer.py`
with error:

```
Traceback (most recent call last):
  File "buffer.py", line 28, in <module>
    from core.buffer import Buffer
ImportError: No module named core.buffer
```

Sys info:
```
Linux kali 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux
emacs --version GNU Emacs 27.0.50
python --version  Python 2.7.14+
python3 --version ython 3.6.5rc1
```

**Comment by manateelazycat** [comment]
When you got exited anhormally error, please switch to buffer *eaf*, then paste output from *eaf*, it's useful.

Don't do 
```
python ~/.emacs.d/emacs-application-framework/app/pdfviewer/buffer.py
```

Because all code is execute from /emacs-application-framework/eaf.py from eaf.el

If you execute from app directory, it's wrong root directory to execute, No module error of course will throw, but it's not problem.

Please paste buffer *eaf* content.

**Comment by Qquanwei** [comment]
*eaf* buffer:

```
Traceback (most recent call last):
  File "/home/quanwei/.emacs.d/emacs-application-framework/eaf.py", line 23, in <module>
    from core.fake_key_event import fake_key_event
ImportError: No module named core.fake_key_event

```

**Comment by manateelazycat** [comment]
Can you do "ls -al" in your emacs-application-framework/core directory ?

**Comment by Qquanwei** [comment]
```
~/.emacs.d/emacs-application-framework/core $ ls -al
total 20
drwxr-xr-x   2 quanwei        quanwei  4096 2018-07-09 21:36 .
drwxr-xr-x   6 quanwei        quanwei  4096 2018-07-09 21:36 ..
-rw-r--r--   1 quanwei        quanwei  2299 2018-07-09 21:36 buffer.py
-rw-r--r--   1 quanwei        quanwei  2695 2018-07-09 21:36 fake_key_event.py
-rw-r--r--   1 quanwei        quanwei  1909 2018-07-09 21:36 utils.py
-rw-r--r--   1 quanwei        quanwei  4168 2018-07-09 21:36 view.py
-rw-r--r--   1 quanwei        quanwei  1470 2018-07-09 21:36 xutils.py
```

Sorry I'm late,  I only work on my computer at night.

**Comment by manateelazycat** [comment]
@Qquanwei  Can you touch empty file "__init__.py" in core directory, then try again?

**Comment by Qquanwei** [comment]
I `touch init,py` and output the same error.  I just clone this project to .emacs.d.

**Comment by Qquanwei** [comment]
I `touch init,py` and output the same error.  I just clone thie project to .emacs.d.

**Comment by manateelazycat** [comment]
It's so strange.

**Comment by manateelazycat** [comment]
@Qquanwei  I mean touch file name with:
```
__init__.py
```

in core directory, github convert 
```
__
```
string, not init.py, is:
```
__init__.py
```

**Comment by Qquanwei** [comment]
It still not work.

I `touch __init__.py` and `M-x eaf-open` with a picture path.

```
dbus-call-method: D-Bus error: "Traceback (most recent call last):
  File \"/usr/lib/python2.7/dist-packages/dbus/service.py\", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File \"/home/quanwei/.emacs.d/emacs-application-framework/eaf.py\", line 71, in new_buffer
    return self.create_app(buffer_id, url, \"app.imageviewer.buffer\")
  File \"/home/quanwei/.emacs.d/emacs-application-framework/eaf.py\", line 92, in create_app
    if importlib.util.find_spec(module_path) is not None:
AttributeError: 'module' object has no attribute 'util'
```

**Comment by Qquanwei** [comment]
Is that I miss some package ?

**Comment by manateelazycat** [comment]
@Qquanwei  you need use python3 execute those code, all your error is you use python2

**Comment by manateelazycat** [comment]
@Qquanwei I have patch https://github.com/manateelazycat/emacs-application-framework/commit/12e6e820c2680d8e0798321d9b37659298a75c52

Force use python3, please try again.

**Comment by Qquanwei** [comment]
@manateelazycat It works. 
I saw you fixed, so I closed this issue.
