### ISSUE TITLE
eval: Symbol’s function definition is void: map-put

### ISSUE THREAD

**Issue by DeepestAbyss** [manateelazycat/emacs-application-framework#160]
I use XFCE4 on Arch Linux 
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-30
Test code
`````
emacs -q
(add-to-list 'load-path "~/.emacs.d/package/")
(require 'eaf)
(eaf-bind-key scroll_up "RET" eaf-pdf-viewer-keybinding)
  (eaf-bind-key scroll_down_page "DEL" eaf-pdf-viewer-keybinding)
  (eaf-bind-key scroll_up "C-n" eaf-pdf-viewer-keybinding)
  (eaf-bind-key scroll_down "C-p" eaf-pdf-viewer-keybinding)
  (eaf-bind-key take_photo "p" eaf-camera-keybinding)
`````

The Messages buffer show: `eval: Symbol’s function definition is void: map-put `

**Comment by MatthewZMD** [comment]
Huh, quite weird, map.el should be automatically loaded even when emacs -q. Maybe because I am on 27? I haven't use 26 for couple of months.
