### ISSUE TITLE
error in README.md

### ISSUE THREAD

**Issue by arstum** [manateelazycat/emacs-application-framework#162]
Installation

    Install python dependences:

    sudo pip3 install dbus-python pymupdf grip qrcode python-xlib pyqt5 pyqtwebengine

    Install QTermWidget's Python binding:

git clone https://github.com/lxqt/qtermwidget.git --depth=1
mkdir bulid && cd build

bulid
build

**Comment by MatthewZMD** [comment]
please elaborate

**Comment by manateelazycat** [comment]
git clone https://github.com/lxqt/qtermwidget.git --depth=1
mkdir bulid && cd build
cmake .. -DQTERMWIDGET_BUILD_PYTHON_BINDING=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr
make
sudo make install

**Comment by arstum** [comment]
mkdir A && cd B  in the README.md

cd: no such file or directory: build

**Comment by manateelazycat** [comment]
fixed

**Comment by MatthewZMD** [comment]
What are you talking about? At what line does this appear
```
mkdir A && cd B
```

Also please at least use a complete sentence
