### ISSUE TITLE
同时开启多个 app 会重叠

### ISSUE THREAD

**Issue by kkeidl** [manateelazycat/emacs-application-framework#17]
# 例
同时开启 "Pdf Viewer" 和 "Video Player"，其中一个会覆盖另一个。
但是两个 app 可以同时运行，用鼠标可以聚焦/操作。应该是再一个 buffer 中。
下图中，中间的黑条部分是视频。

![1](https://user-images.githubusercontent.com/41232036/42723747-b0ab61b2-8796-11e8-992a-b58d27c7e30a.png)

# OS
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch

# Emacs
GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.11, cairo version 1.14.8) of 2018-07-14

**Comment by manateelazycat** [comment]
我试了一下, 没有问题,你怎么重现的?

**Comment by kkeidl** [comment]
# 步骤
$ emacs -Q

M-x load-file
~/.emacs.d/root/vendor/emacs-application-framework/eaf.el

M-x eaf-open
xxx.pdf

M-x eaf-open
xxx.mp4

# WM
i3wm
不知道是不是与窗口管理器有关？

**Comment by manateelazycat** [comment]
@kkeidl 我这边无法重现， 你换一个传统的窗口管理器  mutter/kwin 试一下。
Tile WM 一版的窗口协议实现不完整。

**Comment by kkeidl** [comment]
@manateelazycat GNOME 下可以复现
$ gnome-shell --version
GNOME Shell 3.22.3

**Comment by manateelazycat** [comment]
在同一个emacs window的座标区域， 是不可能有两个窗口， 因为 eaf View 都被销毁了。
gnome-shell 现在都不是用 x11, 用的 wayland。

我在想 wayland 和 i3 都无法正常的支持 x11 reparent
