### ISSUE TITLE
elisp: render HTML region

### ISSUE THREAD

**Issue by JulienMasson** [manateelazycat/emacs-application-framework#181]
Is it possible to render HTML region in a buffer ?

The goal I have in mind is to replace the current html render of my MUA with *eaf*.
I've been able to export the html part of my mail and open it in an external buffer with *eaf*.
The rendering is perfect, it's really good thanks for your work.
But I was wondering if it's possible to render only the body (html) of my mail buffer.
Something similar to `shr-render-region`.
I don't know if it's possible with the XReparent technology ...

Thanks

**Comment by MatthewZMD** [comment]
A possible solution I can think of right now is create a function that creates a html file at the `/tmp` directory, then eaf-open it

**Comment by manateelazycat** [comment]
no its not possible to do that,eaf design to replace all buffer content,it can not mix eaf in emacs buffer region

**Comment by MatthewZMD** [comment]
```
(defun eaf-render-region-as-html ()
  "Assuming marked region is HTML, create a tmp file and use EAF to render the region."
  (interactive)
  (when mark-active
    (let ((tmp-file "/tmp/eaf-render-region.html"))
      (write-region (region-beginning) (region-end) tmp-file)
      (eaf-open tmp-file)
      (delete-file tmp-file))))
```

Here is a function fulfilling your request. 

Dunno whether I should push it to upstream or not. @manateelazycat

**Comment by JulienMasson** [comment]
@manateelazycat, okay yes I expected that behavior.

@MatthewZMD, yes I wrote similar function for my case:
```
(defun mail-open-external-browser (html)
  (interactive)
  (let* ((filename (concat (make-temp-name "mail-") ".html"))
	 (file (concat (temporary-file-directory) filename)))
    (with-temp-file file
      (insert html))
    (eaf-open file)))
```

For rendering an html region I was thinking about this kind of case:
```
(defun compose-html-mail (html)
  (compose-mail)
  (message-goto-body)
  (let ((beg (point-min)))
    (insert html)
    (eaf-render-region beg (point-max))))
```

**Comment by MatthewZMD** [comment]
Are you using mu4e? I am thinking EAF should support an option to automatically render html emails when possible. Would you mind expanding your function on extracting `html` content of the email and either make a PR to here or to the Wiki, that would be best.

**Comment by JulienMasson** [comment]
Euh not anymore I wrote my mua but I have used/hacked different mua like gnus, notmuch, mu4e. 

But yes I can definitely make a PR, the "tricky" part is that each mua has his own way to retrieve html info from a mail buffer.
So I need to do something like detect the mua and call the corresponding function to get the html from the current mail buffer.

**Comment by MatthewZMD** [comment]
You have a lot of experience with different MUAs, that's great. I personally use mu4e, and I've heard a lot of people uses gnus. I'm not sure about notmuch, but we can start by integrating with these two MUAs first :)

**Comment by manateelazycat** [comment]
> You have a lot of experience with different MUAs, that's great. I personally use mu4e, and I've heard a lot of people uses gnus. I'm not sure about notmuch, but we can start by integrating with these two MUAs first :)

maybe best solution is we build multi-thread mail client with eaf technology :)

notmuch ui, multi-thread backend mail fetch and render mail content with webengine

**Comment by MatthewZMD** [comment]
> multi-thread backend mail fetch and render mail content with webengine

Make a multi-thread backend is a possible solution, however I don't suggest render *all* email content with webengine, it's best to render emails that are HTML-based
