### ISSUE TITLE
python3.8扫码上传功能不能使用

### ISSUE THREAD

**Issue by loverainye** [manateelazycat/emacs-application-framework#182]
python3.8 cgi escape 已经被移除 .

> parse_qs, parse_qsl, and escape are removed from the cgi module. They are deprecated in Python 3.2 or older. They should be imported from the urllib.parse and html modules instead.

> [https://docs.python.org/3/whatsnew/3.8.html](https://docs.python.org/3/whatsnew/3.8.html)

**Comment by manateelazycat** [comment]
谢谢反馈，有空的时候看看，最近估计没时间。

谢谢。
