### ISSUE TITLE
terminal fish 输入回车后自动添加"OM"字符

### ISSUE THREAD

**Issue by loverainye** [manateelazycat/emacs-application-framework#183]
```
输入回车后
fish: Unknown command OM
```

bash zsh无此问题, 目前我的解决方案是修改emacs SHELL环境变量.

**Comment by MatthewZMD** [comment]
Are you receiving this error on EAF Terminal? I do not use fish shell and cannot reproduce.

**Comment by loverainye** [comment]
操作系统环境  manjaro arch kde . 两台电脑都有这种问题。

**Comment by manateelazycat** [comment]
qtermwidget 不是一个完全功能的终端模拟器，支持最好的是 VTE 这种库，但是VTE无法嵌入到Qt中。
这个问题估计跟 fish 这种小众的 shell 也有关系。

我目前不用 fish ， 无法帮助你，只能看看别的开发者有没有能力去修复。

**Comment by manateelazycat** [comment]
终端后端已经换成 wetty + xterm.js 的形式，现在不会出现这种问题了。

https://github.com/manateelazycat/emacs-application-framework/commit/ac3cebabe360d3e7cceefefc7f694a6057126c33
