### ISSUE TITLE
Qt app does not receive keys

### ISSUE THREAD

**Issue by clemera** [manateelazycat/emacs-application-framework#184]
I'm trying to follow a tutorial on Qt and trying examples with eaf, however I can not make the following work:

    from PyQt5.QtWidgets import *
    from PyQt5.QtCore import *
    from PyQt5.QtGui import *

    from core.buffer import Buffer

    class AppBuffer(Buffer):
        def __init__(self, buffer_id, url, arguments):
            Buffer.__init__(self, buffer_id, url, arguments, True, QColor(0, 0, 0, 255))
            self.add_widget(DemoWidget())

    class DemoWidget(QMainWindow):

        def __init__(self):
            super(DemoWidget, self).__init__()
            text = QPlainTextEdit()
            self.setCentralWidget(text)

The editor shows, but it does not receive my keys. What is wrong with it? I figured the following works:

    class AppBuffer(Buffer):
        def __init__(self, buffer_id, url, arguments):
            Buffer.__init__(self, buffer_id, url, arguments, True, QColor(0, 0, 0, 255))
            self.add_widget(QPlainTextEdit())

But what if I want to embed the editor like shown above, is there a way?

**Comment by manateelazycat** [comment]
check out interface https://github.com/manateelazycat/emacs-application-framework/blob/8c5dae92eb189b5e56f01fa5da9f744819ab970a/core/buffer.py#L235

you need return widget list by this interface for receive key event

**Comment by clemera** [comment]
Thank you! Sorry for asking dump questions here ;)

**Comment by clemera** [comment]
I got it working but the menu still does not work, on click it get blue but no poup shows:

    from PyQt5.QtWidgets import *
    from PyQt5.QtCore import *
    from PyQt5.QtGui import *

    from core.buffer import Buffer

    class AppBuffer(Buffer):
        def __init__(self, buffer_id, url, arguments):
            Buffer.__init__(self, buffer_id, url, arguments, True, QColor(0, 0, 0, 255))
            self.receivers = []
            self.add_widget(DemoWidget(self))

        def get_key_event_widgets(self):
            return self.receivers



    class DemoWidget(QMainWindow):

        def __init__(self, bw):
            super(DemoWidget, self).__init__()

            text = QPlainTextEdit()

            self.setCentralWidget(text)

            menu = self.menuBar()
            menu.addMenu("&File")
            close = QAction("&Close")
            close.triggered.connect(self.close)
            menu.addAction(close)

            bw.receivers = [menu, text]

**Comment by manateelazycat** [comment]
eaf will switch focus to emacs once you click eaf widget,to make sure emacs always get keyboard event first
