### ISSUE TITLE
Support Emacs 27.1 new XDG path for emacs config path

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#186]
New Emacs 27.1 use XDG path for configuration path now. I think EAF should support for this too. Read elisp side variabel `user-emacs-directory` instead of hardcode in source code `~/.emacs.d/`.

I found EAF browser and EAF RSS reader both store files in `~/.emacs.d/` hardcoded.

**Comment by manateelazycat** [comment]
~/.emacs.d/ write in Python source code, it's okay, not need change user-emacs-directory since it's Python code.

**Comment by stardiviner** [comment]
I mean pass `user-emacs-directory` from Elisp to Python, so that Python side will recognize the correct path instead of hardcoded.

**Comment by MatthewZMD** [comment]
I am working on this

**Comment by manateelazycat** [comment]
> I am working on this

You can pass the elisp var when eaf startup
