### ISSUE TITLE
Feature request: org-mode preview

### ISSUE THREAD

**Issue by fbob** [manateelazycat/emacs-application-framework#19]
You're back with an awesome project !
Congratulations :)

I've just seen that you've made a markdown preview.
Do you think it could be possible to have the same for org-mode file ? 
It could be an awesome application for Emacs world domination ...

It's perhaps too difficult at present time but a thread was initiated on reddit on this subject with perhaps good ideas to grab as starting point:

https://www.reddit.com/r/emacs/comments/57nps0/orgmode_need_a_realtime_document_preview/
 
At this time emacs-application-framework was not born, so the world was not the same :)
Anyway many many thanks for this awesome project !

Regards,

**Comment by manateelazycat** [comment]
@fbob 

It's done: https://github.com/manateelazycat/emacs-application-framework/commit/6ddd3f376386efacf81d235a243ef03fc5d22c5b

Update to newest, then type command eaf-open and org file.

You can see screenshot at:
https://github.com/manateelazycat/emacs-application-framework/blob/master/screenshot/org_previewer.gif

**Comment by fbob** [comment]
Wahoo ... my jaw falls
Just made a tweet to inform that Emacs is ready for total world domination ... Genius :)
