### ISSUE TITLE
Touchpad scroll issue

### ISSUE THREAD

**Issue by zsxh** [manateelazycat/emacs-application-framework#197]
It seems eaf window do not scroll correctly when using touchpad.
触摸板滚动eaf窗口定位有些问题

![深度录屏_emacs_20200110101156](https://user-images.githubusercontent.com/10348978/72120189-1e035c80-3392-11ea-845a-26887eb2c8f6.gif)

OS: manjaro 18.1.5
DE: deepin
emacs-version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13)
 of 2020-01-09

**Comment by manateelazycat** [comment]
有可能是deepin窗口管理器对焦点的处理，请测试一下KDE,看看有没有问题

**Comment by zsxh** [comment]
KDE 5.65.0 / Plasma 5.17.4 还是有类似的问题

![深度录屏_emacs_20200110194745](https://user-images.githubusercontent.com/10348978/72151687-d3123500-33e3-11ea-8d81-9d4c6d10ed16.gif)

**Comment by manateelazycat** [comment]
我感觉你的触摸板不是产生的是窗口拖动事件，而不是滚动事件？

有些触摸板，比如小米的笔记本这方面就不好用。

我没法重现你的问题。

**Comment by MatthewZMD** [comment]
我也无法重现这个问题。

**Comment by zsxh** [comment]
下面的录屏我分别试了初始时单窗口，分窗口，改变frame大小等操作，window size改变时我都会对水平、垂直方向上进行滚动测试。在我这里发现，如果是单窗口或是窗口从小变大这样的操作，滚动大体上没问题(有时会有较小位移)，感觉又好像不是滚动事件问题。

![深度录屏_emacs_20200110230834](https://user-images.githubusercontent.com/10348978/72163142-3ad57980-33fe-11ea-8d14-27984db64334.gif)

**Comment by manateelazycat** [comment]
我建议你直接装 manjaro KDE，先不要安装 DDE， 做一个干净环境的对比测试。

**Comment by zsxh** [comment]
找了台机子装了manjaro kde，确认了manjaro kde没有问题，看来还是dde问题。
