### ISSUE TITLE
core dump problem  ---- python dependencies on Arch Linux

### ISSUE THREAD

**Issue by shinygnu** [manateelazycat/emacs-application-framework#203]
Hi folks, Great job with this project. It is really exciting. 
Arch Linux highly recommends installing all python modules as packages (not through pip). However, in my case, only pip has succeeded in fixing the core dump problem you've all flagged in the readme. I am wondering if you could clarify what the list of packages to install would be through pacman/yay(aur). 

Currently, even after running the following:

`yay -S dbus-python python-xlib pyqt5 python-pyqtwebengine python-pymupdf python-grip python-qrcode python-feedparser --noconfirm`

I get the error message in emac's *eaf* buffer:
`qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`

Even after also installing the below packages, the problems persists.

python-xcffib python-xpybutil qt5-webglplugin 

Any ideas?

**Comment by manateelazycat** [comment]
Why not just use PIP ?

Sorry I haven't time figure out why Arch package have this problem.

You need figure out yourself, sorry I can't help.
