### ISSUE TITLE
Support open Org pdf file link with EAF?

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#205]
```elisp
(defun eaf-org-open-file (file &optional link)
  "An wrapper function on `eaf-open'."
  (eaf-open file))

;; use `emacs-application-framework' to open PDF file: link
(add-to-list 'org-file-apps '("\\.pdf\\'" . eaf-org-open-file))
```
Here is a tiny patch might is great for user who want to open Org file links with EAF.

**Comment by stardiviner** [comment]
BTW, If `eaf-open` support PDF file page number will be great.

**Comment by MatthewZMD** [comment]
I am not sure about the wrapper, but this certainly is something that can be added to the Wiki.

**Comment by stardiviner** [comment]
Hmm, sounds reasonable. I agree.
