### ISSUE TITLE
Yesterday's fix broke eaf

### ISSUE THREAD

**Issue by iris-garcia** [manateelazycat/emacs-application-framework#208]
```
Traceback (most recent call last):
  File "/home/igarcia/.emacs.d/lib/emacs-application-framework/eaf.py", line 427, in <module>
    eaf = EAF(sys.argv[1:])
  File "/home/igarcia/.emacs.d/lib/emacs-application-framework/eaf.py", line 58, in __init__
    self.update_emacs_var_dict(var_dict_string)
  File "/home/igarcia/.emacs.d/lib/emacs-application-framework/eaf.py", line 79, in update_emacs_var_dict
    (var_name, var_value) = var_pair.split("ᛝ")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by MatthewZMD** [comment]
What are the producible steps? What is your EAF config?

**Comment by manateelazycat** [comment]
I think you just need reboot Emacs.
You eaf.el pass old version data to Python process.

**Comment by iris-garcia** [comment]
So here is what I found:
- Starting a new emacs process then calling `eaf-*` works perfectly fine.
- Starting emacs as a daemon, then using any emacsclient eaf shows the error I mention in the first message.

**Comment by MatthewZMD** [comment]
I cannot reproduce this bug in emacsclient

**Comment by iris-garcia** [comment]
Ok, did some more testing and here are my findings:
- Running `emacs --daemon` then `emacsclient -c`: works perfectly fine.
- Running `emacs` directly works perfectly fine.
- Running `emacs --daemon` froma systemd definition as show below then using `emacsclient -c` fails.

```
[Unit]
Description=Emacs: the extensible, self-documenting text editor

[Service]
Type=forking
ExecStart=emacs --daemon
ExecStop=emacsclient --eval "(save-buffers-kill-emacs)"
Restart=always

# Remove the limit in startup timeout, since emacs
# cloning and building all packages can take time
TimeoutStartSec=0

[Install]
WantedBy=default.target
```

**Comment by MatthewZMD** [comment]
Interesting, the error doesn't look like related to whether Emacs is started from a daemon or not. Can you also paste your EAF config?

**Comment by iris-garcia** [comment]
Sure, I am using a very basic configuration:
```
  (use-package eaf
    :load-path "~/.emacs.d/lib/emacs-application-framework"
    :custom
    (eaf-find-alternate-file-in-dired t)
    :config
    (eaf-bind-key scroll_up "RET" eaf-pdf-viewer-keybinding)
    (eaf-bind-key scroll_down_page "DEL" eaf-pdf-viewer-keybinding)
    (eaf-bind-key scroll_up "k" eaf-pdf-viewer-keybinding)
    (eaf-bind-key scroll_down "i" eaf-pdf-viewer-keybinding)
    (eaf-bind-key scroll_up "k" eaf-browser-keybinding)
    (eaf-bind-key scroll_down "i" eaf-browser-keybinding)
    (eaf-bind-key take_photo "p" eaf-camera-keybinding))```

**Comment by MatthewZMD** [comment]
Does the error occur when you start EAF?

**Comment by iris-garcia** [comment]
No, it happens when I try any `eaf-` command like:
- `eaf-open-browser`

**Comment by manateelazycat** [comment]
Can not reproduce if there are further clues, welcome to submit a new issue.

**Comment by manateelazycat** [comment]
Can not reproduce if there are further clues, welcome to submit a new issue.

**Comment by ykhurshid** [comment]
I'm having the exact same error. I've installed it through the aur and it neither works with the daemon or vanilla mode.
