### ISSUE TITLE
eaf-open打开image后，split window，然后再另一个window中eaf-open pdf，发现modeline混乱了

### ISSUE THREAD

**Issue by lujun9972** [manateelazycat/emacs-application-framework#21]
![](https://raw.githubusercontent.com/lujun9972/images/master/eaf_bug.gif)

**Comment by manateelazycat** [comment]
EAF 依赖桌面环境正常执行  xlib reparent ， 这样可以把 PyQT5 的窗口粘贴到正常的 emacs buffer/window 坐标。

混乱的不是 modeline, 而是 xlib reparent 没有正常工作。

请使用本地系统 KDE, Gnome2, Gnome3/X11 尝试， 以使得 xlib parent 可以正常工作。

**Comment by manateelazycat** [comment]
如果 KDE, Gnome2, Gnome3/X11 的本地系统都有问题， 请重新打开此 issue
