### ISSUE TITLE
EAF Blinking

### ISSUE THREAD

**Issue by tumashu** [manateelazycat/emacs-application-framework#214]
我将emacs的背景设置为红色，以点开网页连接，截了闪烁的过程，希望有同学可以找到解决的办法或者hack的办法。

![IMG_20200202_093036](https://user-images.githubusercontent.com/67725/73601612-90d1b300-459f-11ea-9fba-a77347919a59.jpg)
![IMG_20200202_093114](https://user-images.githubusercontent.com/67725/73601613-93340d00-459f-11ea-95a1-97c7f6a3566e.jpg)
![IMG_20200202_093126](https://user-images.githubusercontent.com/67725/73601614-962efd80-459f-11ea-8729-947cc53a0414.jpg)
![IMG_20200202_093134](https://user-images.githubusercontent.com/67725/73601616-98915780-459f-11ea-875e-85f1659b94a0.jpg)
![IMG_20200202_093143](https://user-images.githubusercontent.com/67725/73601617-9af3b180-459f-11ea-9925-d30aa8dfc057.jpg)

**Comment by manateelazycat** [comment]
我严重怀疑你的Debian系统或者显卡驱动问题很老，导致X11 Reparent的时候，闪烁严重

**Comment by tumashu** [comment]
我用的是debian10，昨天已经从 unstable 安装了 intel 显卡驱动，还是不行，难道和xserver有关系？

**Comment by manateelazycat** [comment]
如果有条件可以对比测试一下Manjaro, 我用Manjaro KDE

**Comment by tumashu** [comment]
换manjaro工作量太大，我也不太喜欢kde，所以我现在想怎么可以临时设置 emacs 的背景颜色，让闪烁不那么刺眼，不过到目前为止，还没有头绪，不知道那个红色来自于哪里

**Comment by tumashu** [comment]
我试着把 eaf buffer 变成白色，不过似乎没有效果
```
(defun eaf--create-buffer (url app-name)
  "Create an EAF buffer given URL and APP-NAME."
  (eaf--gen-keybinding-map (eaf--get-app-bindings app-name))
  (let* ((eaf-buffer-name (if (equal (file-name-nondirectory url) "")
                              url
                            (file-name-nondirectory url)))
         (eaf-buffer (generate-new-buffer eaf-buffer-name)))
    (with-current-buffer eaf-buffer
      (erase-buffer)
      (insert
       (propertize
        (make-string 10000 ?f)
        'face 'eaf-buffer))
      (goto-char (point-min))
      (redisplay)
      (eaf-mode)
      ;; `eaf-buffer-url' should record full path of url, otherwise `eaf-open' will open duplicate PDF tab for same url.
      (set (make-local-variable 'eaf--buffer-url) url)
      (set (make-local-variable 'eaf--buffer-app-name) app-name)
      (run-hooks (intern (format "eaf-%s-hook" app-name)))
      (setq mode-name (concat "EAF/" app-name)))
    eaf-buffer))

```

**Comment by manateelazycat** [comment]
无法重现，估计跟桌面环境，窗口管理器或者显卡驱动有关。
