### ISSUE TITLE
Add Resize Options to EAF Image Viewer 

### ISSUE THREAD

**Issue by tumashu** [manateelazycat/emacs-application-framework#218]
我今天试着将 eaf 集成到我的工作环境，但是使用图片查看器的时候，遇到一些问题，我有许多文档照片，当用图片查看器打开这些文档照片之后，字太小了，根本没法看，能不能添加缩放功能？

**Comment by manateelazycat** [comment]
已经在Todo list里面了，但是最近估计没有时间折腾图片管理器。

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/emacs-application-framework/commit/8d50b5f1f4218ad9dc6e4e8e58d1dedf372c7aea

**Comment by tumashu** [comment]
cool!

**Comment by manateelazycat** [comment]
New keybinding please check: https://github.com/manateelazycat/emacs-application-framework/wiki/Keybindings
