### ISSUE TITLE
How to send <CTRL>+key or <ALT>+key to eaf-terminal?

### ISSUE THREAD

**Issue by pietrodito** [manateelazycat/emacs-application-framework#235]
Pretty straight question.

**Comment by manateelazycat** [comment]
By EAF framework, it's hard to send Ctrl/Alt  keybinding to Python process.

**Comment by pietrodito** [comment]
Too bad! I have tried the Framework to use a terminal able to display the result of interactive shell command like `zsh-peco-history`. But if I cannot send `C-r` to the terminal...

**Comment by MatthewZMD** [comment]
Yes, by the current design, to ensure C/M-keys are treated by Emacs, they do not get sent directly to EAF. Some design improvements will have to be made.

**Comment by pietrodito** [comment]
For process like REPL or terminal, emacs send C-c if the user type it twice C-c C-c. Is it possible to do something like that ?

**Comment by manateelazycat** [comment]
No, terminal plugins just render correctly.

**Comment by manateelazycat** [comment]
@pietrodito I believe you said the latest version has fix your issue.

You can add new key and binding with command `eaf-send-key-sequence' if you found some key missing in default eaf-terminal-keybinding.
