### ISSUE TITLE
(eaf-setq eaf-browse-default-zoom "3.0") doesn't work

### ISSUE THREAD

**Issue by FirstLoveLife** [manateelazycat/emacs-application-framework#238]
the default (eaf-setq eaf-browser-default-zoom "1.25") is still too small for me. So I tried to set it to "3.0", but the actual font size still unchanged.

**Comment by manateelazycat** [comment]
I have try ```(eaf-setq eaf-browser-default-zoom "3.0")``` works.

You lost 'r' char in browser word.

**Comment by nlfiasel** [comment]
https://github.com/manateelazycat/emacs-application-framework/wiki/Customization

wiki上的少了个r😂

**Comment by manateelazycat** [comment]
> https://github.com/manateelazycat/emacs-application-framework/wiki/Customization
> 
> wiki上的少了个r

我的错，已经修复，感谢反馈！ ;)

**Comment by FirstLoveLife** [comment]
haha
