### ISSUE TITLE
按键时报错！

### ISSUE THREAD

**Issue by marshalyyx2000** [manateelazycat/emacs-application-framework#239]
Quit
[EAF/browser] Opening https://www.zhihu.com/question/26689723/answer/551610078
dbus-call-method: D-Bus error: "Traceback (most recent call last):
  File \"/usr/local/lib/python3.6/dist-packages/dbus/service.py\", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File \"/home/marshal/.emacs.d/site-lisp/emacs-application-framework-master/eaf.py\", line 281, in execute_function
    buffer.execute_function(function_name)
  File \"/home/marshal/.emacs.d/site-lisp/emacs-application-framework-master/core/buffer.py\", line 263, in execute_function
    getattr(self, function_name)()
  File \"/home/marshal/.emacs.d/site-lisp/emacs-application-framework-master/core/browser.py\", line 605, in open_link
    self.buffer_widget.get_link_markers()
  File \"/home/marshal/.emacs.d/site-lisp/emacs-application-framework-master/core/browser.py\", line 279, in get_link_markers
    return self.execute_js(self.get_markers_raw.replace(\"%1\", self.buffer.emacs_var_dict[\"eaf-marker-letters\"]));
KeyError: 'eaf-marker-letters'

**Comment by marshalyyx2000** [comment]
前一版本没有该问题。

**Comment by MatthewZMD** [comment]
C-h v eaf-var-list显示什么

**Comment by marshalyyx2000** [comment]
((eaf-camera-save-path . "~/Downloads")
 (eaf-browser-enable-plugin . "true")
 (eaf-browser-enable-javascript . "true")
 (eaf-browser-remember-history . "true")
 (eaf-browser-default-zoom . "1.5")
 (eaf-browser-blank-page-url . "https://www.sogou.com")
 (eaf-browser-dark-mode . "true"))
Original value was 
((eaf-camera-save-path . "~/Downloads")
 (eaf-browser-enable-plugin . "true")
 (eaf-browser-enable-javascript . "true")
 (eaf-browser-remember-history . "true")
 (eaf-browser-default-zoom . "1.0")
 (eaf-browser-blank-page-url . "https://www.google.com")
 (eaf-browser-dark-mode . "false")
 (eaf-browser-scroll-behavior . "auto")
 (eaf-browser-download-path . "~/Downloads")
 (eaf-browser-aria2-proxy-host . "")
 (eaf-browser-aria2-proxy-port . "")
 (eaf-marker-letters . "ASDFHJKLWEOPCNM"))

**Comment by manateelazycat** [comment]
你是最新版吗？我没有重现你的问题。

**Comment by manateelazycat** [comment]
一直没有重现问题，如果有稳定重现步骤，欢迎重新打开issue.
