### ISSUE TITLE
How to catch click event in QT app from emacs

### ISSUE THREAD

**Issue by vuquangtam** [manateelazycat/emacs-application-framework#247]
I research the code and saw this event send position (x, y). Can you suppport to add QT event type to this. 
```
(dbus-register-signal
 :session "com.lazycat.eaf" "/com/lazycat/eaf"
 "com.lazycat.eaf" "focus_emacs_buffer"
 #'eaf-focus-buffer)

(defun eaf-focus-buffer (msg)
  (let* ((coordinate-list (split-string msg ","))
         (mouse-press-x (string-to-number (nth 0 coordinate-list)))
         (mouse-press-y (string-to-number (nth 1 coordinate-list))))
    (catch 'find-window
      (dolist (window (window-list))
        (let ((buffer (window-buffer window)))
          (with-current-buffer buffer
            (if (derived-mode-p 'eaf-mode)
                (let* ((window-allocation (eaf-get-window-allocation window))
                       (x (nth 0 window-allocation))
                       (y (nth 1 window-allocation))
                       (w (nth 2 window-allocation))
                       (h (nth 3 window-allocation))
                       )
                  (when (and
                         (< x mouse-press-x (+ x w))
                         (< y mouse-press-y (+ y h)))
                    (select-window window)
                    (throw 'find-window t))))))))))
```

Thanks

**Comment by manateelazycat** [comment]
Can you tell me what your goal?

Perhaps I can provide a better API interface

**Comment by vuquangtam** [comment]
> 
> 
> Can you tell me what your goal?
> 
> Perhaps I can provide a better API interface

I want to capture when event is click and trigger some external command in emacs.
I'm using WSL, It's lose focus whenever i click on widget. I just want to add some fix to make it work on WSL.

**Comment by manateelazycat** [comment]
> > Can you tell me what your goal?
> > Perhaps I can provide a better API interface
> 
> I want to capture when event is click and trigger some external command in emacs.
> I'm using WSL, It's lose focus whenever i click on widget. I just want to add some fix to make it work on WSL.

In EAF, has core/view.py have code:
```self.setAttribute(Qt.WA_X11DoNotAcceptFocus, True)```

That's mean EAF widget always not accept focus even mouse click on EAF widget, input focus always on Emacs window.

```focus_on_emacs``` method not use to change window focus, use to select window with click coordinate.

I guess WSL haven't full feature X11 window manager to handle WA_X11DoNotAcceptFocus X11 message, that's the problem.

**Comment by vuquangtam** [comment]
Perhaps it's root cause. Let me check again. Thanks
