### ISSUE TITLE
Use page title as file name when saving page to pdf?

### ISSUE THREAD

**Issue by zbelial** [manateelazycat/emacs-application-framework#252]
First of all, thanks. 
Don't you think using page tilte is better?

**Comment by manateelazycat** [comment]
Title perhaps include invalid file char.

**Comment by zbelial** [comment]
Ok, I see, thanks.

**Comment by manateelazycat** [comment]
Maybe we can save as host name, then try rename it with title.

If success, everybody happy, if failed, host name is okay.

**Comment by zbelial** [comment]
Yes, I think yours is better.
Another way is replacing/removing invalid chars, but maybe it's unnecessarily complicated.

**Comment by manateelazycat** [comment]
> Yes, I think yours is better.
> Another way is replacing/removing invalid chars, but maybe it's unnecessarily complicated.

Because title not just ASCII char, perhaps include Chinese, so replace invalid chars is not always good way.

**Comment by manateelazycat** [comment]
Please update newest version, I believe title.pdf will works in most situation.

I start with the design when ready to use the title as the file name,
thanks to discuss with you, I thought of a better way, thank you for your suggestion. ;)

**Comment by zbelial** [comment]
Updated eaf and it works as expected. Great. Thanks.
