### ISSUE TITLE
Cannot input shortcut chars when using mail.qq.com

### ISSUE THREAD

**Issue by zbelial** [manateelazycat/emacs-application-framework#253]
Hi
When trying to login qq mail, I cannot input some chars, such as 'j', 'y', 's', ..etc and all of these chars are shortcuts.  Do you guys have this problem? 

Latest eaf, PyQtWebEngine 5.13.2 and Emacs 27.0.90

**Comment by manateelazycat** [comment]
QQ mail looks have some security mechanism that block javascript fetch input content by ```activeElement.value```

Newest version have fix this issue.
