### ISSUE TITLE
Can't move focus to EAF-Window by mouse.

### ISSUE THREAD

**Issue by WeissP** [manateelazycat/emacs-application-framework#260]
Environment: Manjaro + KDE
![out](https://user-images.githubusercontent.com/38898031/77850371-5ddc2200-71d2-11ea-9acb-bc7941b7e566.gif)

**Comment by manateelazycat** [comment]
我没法重现这个问题，我这边一直可以。

**Comment by WeissP** [comment]
> 我没法重现这个问题，我这边一直可以。

有什么排查的方法吗，我本来以为 eaf 本来就不能通过鼠标换焦点，结果原来是我一个人的问题。我用了最小配置也依然不行。

**Comment by manateelazycat** [comment]
> > 我没法重现这个问题，我这边一直可以。
> 
> 有什么排查的方法吗，我本来以为 eaf 本来就不能通过鼠标换焦点，结果原来是我一个人的问题。我用了最小配置也依然不行。

你是点击鼠标，还是只是把鼠标移动到EAF窗口？

**Comment by WeissP** [comment]
点击鼠标，我甚至在 eaf 窗口选中了文字都没法转移焦点。

**Comment by manateelazycat** [comment]
> 点击鼠标，我甚至在 eaf 窗口选中了文字都没法转移焦点。

你的桌面环境和我一样，你新建一个用户看看，是不是桌面环境配置的问题？

我没法重新你说的问题。

**Comment by WeissP** [comment]
依旧不行，这回 emacs 啥配置都没，第一行是 load-path 第二行就是 require ...... 我用的 emacs 是 27 的，你呢？然后会不会是因为你有什么配置导致你没问题啊

**Comment by manateelazycat** [comment]
> 依旧不行，这回 emacs 啥配置都没，第一行是 load-path 第二行就是 require ...... 我用的 emacs 是 27 的，你呢？然后会不会是因为你有什么配置导致你没问题啊

我没有什么配置。我Emacs26和Emacs28都没有问题。

**Comment by manateelazycat** [comment]
./emacs-application-framework/core/buffer.py

第166行

self.trigger_focus_event.emit("{0},{1}".format(event.globalX(), event.globalY()))

你看点击的时候，这里有没有数据？

**Comment by WeissP** [comment]
![image](https://user-images.githubusercontent.com/38898031/77912624-28e3d400-7293-11ea-96c9-3767772b6f40.png)

你意思是像这样直接插在里面？这样的话，启动 eaf 时就直接报错了。

**Comment by manateelazycat** [comment]
> ![image](https://user-images.githubusercontent.com/38898031/77912624-28e3d400-7293-11ea-96c9-3767772b6f40.png)
> 
> 你意思是像这样直接插在里面？这样的话，启动 eaf 时就直接报错了。

我的意思是在166行下面插入 print("********")

**Comment by WeissP** [comment]
实在抱歉，还是没懂。
    
![image](https://user-images.githubusercontent.com/38898031/77913853-49ad2900-7295-11ea-8448-d974e207490a.png)

像这两种方式还是会报错，放到 super... 下面也一样。

**Comment by manateelazycat** [comment]
> 实在抱歉，还是没懂。
> 
> ![image](https://user-images.githubusercontent.com/38898031/77913853-49ad2900-7295-11ea-8448-d974e207490a.png)
> 
> 像这两种方式还是会报错，放到 super... 下面也一样。

你先去学习一下Python吧，然后把PyQt也学习一下吧，zetcode这个网站就有不错的教程。
你这样没有Python基础，我教你成本太高了。
