### ISSUE TITLE
Request: mouseless browsing

### ISSUE THREAD

**Issue by lcabrini** [manateelazycat/emacs-application-framework#270]
I installed eaf primarily to be able to copy text from wordreference.com and past it into an org buffer, all from withing Emacs (I can't get eww to cooperate with wordreference). This works, but in order to select text, I have to use the mouse, which gets annoying really fast. I was hoping to navigate a webpage like any other Emacs buffer, move to the start of text, mark the text and copy it, all via the keyboard.

Is that possible with eaf? I haven't been able to figure it out. I also saw this in the todo list which may be what I'm looking for:

> Browser: smart select text area by cursor.

**Comment by MatthewZMD** [comment]
Yes, this is part of the TODO list :-)

**Comment by manateelazycat** [comment]
It's in todo list.

I think it's need much JavaScript code.

If you're good at JavaScript, welcomes the submission PR. ;)

**Comment by lcabrini** [comment]
Hm.. Javascript is not really something I dabble in, but in the end it is just another programming language (albeit a bad one) and this is functionality that is really important to me so let me have a look and see what I can come up with.

So, if I get it right: one would need to inject Javascript into the page to handle things like scroll buffer up/down, mark region, copy, etc, right? And the EAF provides a bridge between LISP and the PyQT application? I'm sorry, I think I have to read up on how EAF works.

**Comment by manateelazycat** [comment]
> Hm.. Javascript is not really something I dabble in, but in the end it is just another programming language (albeit a bad one) and this is functionality that is really important to me so let me have a look and see what I can come up with.
> 
> So, if I get it right: one would need to inject Javascript into the page to handle things like scroll buffer up/down, mark region, copy, etc, right? And the EAF provides a bridge between LISP and the PyQT application? I'm sorry, I think I have to read up on how EAF works.

You can research emacs-application-framework/core/browser.py, this file is enough

**Comment by AlonTzarafi** [comment]
QT has the option QWebSettings::CaretBrowsingEnabled but PyQt doesn't have it

**Comment by manateelazycat** [comment]
This request exist in https://github.com/manateelazycat/emacs-application-framework/wiki/Todo-List

Close this issue now.

**Comment by manateelazycat** [comment]
This issue has fixed by recent patches.
