### ISSUE TITLE
Support `org-store-link` in EAF applications

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#279]
I have following feature requests. I original just want to get a video file and timestamp link from EAF app. But later I tried PDF viewer app, it does not support `org-store-link` too. So I expand this idea to following apps.

- [ ] support PDF viewer with link to PDF file and pages
- [ ] support EPUB viewer with link to EPUB file and pages
- [ ] support Video player with link to video file and timestamp
- [ ] support Image viewer with link to image file
- [ ] support Web Browser app with link to current tab URL
- [ ] support MindMap app with link to mindmap file

**Comment by manateelazycat** [comment]
I don't use org-store-link, any PR are welcome! ;)

**Comment by stardiviner** [comment]
Ok, I will take a try. Not soon, maybe later. Thanks for your work, @manateelazycat

**Comment by AloisJanicek** [comment]
Here is a function for storing link and title using `org-protocol-store-link ` 
```elisp
(defun eaf-browser-org-store-link ()
  "Store web link from eaf browser buffers."
  (interactive)
  (when (eq major-mode 'eaf-mode)
    (when (string-equal "browser" eaf--buffer-app-name)
      (require 'org-protocol)
      (org-protocol-store-link (list :url eaf--buffer-url :title eaf--bookmark-title)))))
```
and here is a function for capturing url and title using `org-protocol-capture` in the same way like you would do from Firefox or Chromium

```lisp
(defun eaf-browser-org-capture-link ()
  "Capture web link from eaf browser buffers."
  (interactive)
  (when (eq major-mode 'eaf-mode)
    (when (string-equal "browser" eaf--buffer-app-name)
      (require 'org-protocol)
      ;; see https://github.com/sprig/org-capture-extension for information on capture templates for org-protocol
      (let ((protocol-url (concat "template=L&url=" eaf--buffer-url "&title=" eaf--bookmark-title)))
        (org-protocol-capture (org-protocol-parse-parameters protocol-url t))))))
```

I don't use other EAF apps, so this is all I have.

**Comment by stardiviner** [comment]
This is very awesome! Thanks @AloisJanicek

**Comment by AloisJanicek** [comment]
Even if there is nothing wrong with those two functions itself, it would make much sense to include them in more complete PR covering all EAF apps.
I just posted them so the fellow users can add them to their emacs configs until this issue is addressed properly in EAF itself.

**Comment by stardiviner** [comment]
@AloisJanicek Is it possible to not use `org-protocol`? Just like normal org-store-link functions, directly construct link?
