### ISSUE TITLE
Can eaf  based on file manager develop kinds of application?

### ISSUE THREAD

**Issue by tszluopengxu** [manateelazycat/emacs-application-framework#28]
As a whole computer system , no matter what kinds of version linux, Mac and windows, all based file manager, I think emacs should do this too, espacially for amzoning eaf. For example, before open images or pdfs and other files with application, we first in the file manager, and then hit enter ,it auto run its application.i think if do this ,emacs can be described as the system fact.
As the file manager , the total commander is the best ,but shortcut the vim is the best. so if can combise the vim shortcut and the total commander function to implemente file manager ,eaf may be as described the really computer system

**Comment by tszluopengxu** [comment]
几年不用英语了，写着真累。直接汉语吧，我是一个产品经理，也不写代码。我觉得文件管理用emacs内置的dired完全能实现total commander的核心功能，并且结合vim按键，来实现一个牛逼的文件管理系统，这样先通过这个牛逼的文件管理系统，接着运行eaf的程序。dire+和dried-hack这个仓库的在功能应该可以参考，如果你觉得行得通的话，我可以详细做需求，先把最牛逼的功能提取出来
https://github.com/Fuco1/dired-hacks

**Comment by manateelazycat** [comment]
谢谢， 我不敢兴趣再造一个 dired, dired 工作的挺好的。

EAF 的目的是补强Emacs不擅长的GUI的工作，但是像编辑器和文件管理这些文本的工作emacs做的足够好， 我挺喜欢 dired 的， 不感兴趣做 GUI 的文件管理器。

谢谢你的建议。
