### ISSUE TITLE
EAF Not Recognising Text Field For Input

### ISSUE THREAD

**Issue by phealeyh** [manateelazycat/emacs-application-framework#286]
Hi,

I am running a browser terminal on google cloud platform but I am not able to input any text on it. The terminal is embedded into the web-page but EAF is not recognising it as an input-field. 

Is there any way I can toggle an insert mode where I can disable all EAF browser bindings and directly send keys?

![gcp_console_terminal](https://user-images.githubusercontent.com/8462246/80671216-89fa0400-8aec-11ea-9575-68691b88e6a9.png)

**Comment by MatthewZMD** [comment]
Can you paste the URL here?

It is a known problem that EAF's vimium isn't compatible with every javascript webpage. Javascript is such a massive language that every single person use it somewhat differently, so this is a case by case problem.

**Comment by MatthewZMD** [comment]
> Is there any way I can toggle an insert mode where I can disable all EAF browser bindings and directly send keys?

Not yet, but something worth considering

**Comment by phealeyh** [comment]
Thanks for the reply! The link is https://console.cloud.google.com/home/

You will have to log in with your google account and then click on the terminal icon on the top right (found in the cluster of icons) and a new terminal will appear at the bottom. This is where you won't be able to send any keys directly.

**Comment by MatthewZMD** [comment]
Yikes, sometimes I hate those fancy webpages. The fancier the webpage, the weirder is the underlying javascript.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/emacs-application-framework/commit/e93411598287c16523bc9271e5d328d430fdcd47

This patch has fixed this issue, thanks for report!
