### ISSUE TITLE
HiDPi Problem: pdf-viewer does not display page number fully

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#287]
As this screenshot shows:

![EAF pdf-viewer page number](https://user-images.githubusercontent.com/378699/81147973-f32abd00-8fad-11ea-98c1-24e5220ae53f.png)

**Comment by manateelazycat** [comment]
发给PDF文件给我看看？

**Comment by stardiviner** [comment]
我这边所有PDF都是这样的。我发上来你测试下

**Comment by stardiviner** [comment]
[麦肯锡全球研究院-重启全球化：中国如何引领新进程_讨论文件.pdf](https://github.com/manateelazycat/emacs-application-framework/files/4585496/-._.pdf)

**Comment by manateelazycat** [comment]
我这边是正常的，感觉像你系统字体折腾出问题了。

**Comment by stardiviner** [comment]
ok，我试试更换字体。这个字体用的是系统字体还是Emacs的字体？
我系统字体用的是KDE自带的Noto

![image](https://user-images.githubusercontent.com/378699/81153271-566c1d80-8fb5-11ea-9a6d-464c1edb7e4b.png)

**Comment by stardiviner** [comment]
会不会是由于 HiDPI 屏幕的缘故？

**Comment by manateelazycat** [comment]
> 会不会是由于 HiDPI 屏幕的缘故？

我没有高分屏，没法帮你测试，你可以暴力改一下PDF的代码做一下实验。

**Comment by stardiviner** [comment]
好主意。谢谢

**Comment by stardiviner** [comment]
I modified pdf-viewer/buffer.py source code,
Like this diff:
```diff
modified   app/pdf-viewer/buffer.py
@@ -401,10 +401,10 @@ class PdfViewerWidget(QWidget):
         else:
             painter.setPen(self.page_annotate_light_color)
 
-        painter.drawText(QRect(self.rect().x(),
-                               self.rect().y() + self.rect().height() - self.page_annotate_height - self.page_annotate_padding_bottom,
+        painter.drawText(QRect(self.rect().x() - 150,
+                               self.rect().y() + self.rect().height() - 100 - self.page_annotate_height - self.page_annotate_padding_bottom,
                                self.rect().width() - self.page_annotate_padding_right,
-                               self.page_annotate_height),
+                               self.page_annotate_height * 2),
                          Qt.AlignRight,
                          "{0}% ({1}/{2})".format(int((start_page_index + 1) * 100 / self.page_total_number), start_page_index + 1, self.page_total_number))
```

Then I got correct displaying page number:

![image](https://user-images.githubusercontent.com/378699/81909698-8a6ec080-95fd-11ea-8147-1fda891158fe.png)

My guess the problem is because of my MacBook Pro (installed Arch Linux) HiDPI screen, so the page number height calculation is not correct. WDYT?

**Comment by manateelazycat** [comment]
我没有高分屏的设备，暂时没法修复。

**Comment by stardiviner** [comment]
I find two Qt HiDPI Displays support links, might be helpful.

- https://www.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6
- https://doc.qt.io/qt-5/highdpi.html

I checked out this Arch Wiki (https://wiki.archlinux.org/index.php/HiDPI#Qt_5)
I have KDE global scale settings, like this:

![image](https://user-images.githubusercontent.com/378699/82003155-3a8e0900-9692-11ea-95cf-17712d0d846f.png)

I indeed have system environment variable `QT_AUTO_SCREEN_SCALE_FACTOR=0`. according to upper wiki described:

> Note:
>
>    If you manually set the screen factor, it is important to set QT_AUTO_SCREEN_SCALE_FACTOR=0 otherwise some applications which explicitly force high DPI enabling get scaled twice.

**Comment by stardiviner** [comment]
I have an idea, why not put this page number info in Emacs mode-line?

**Comment by manateelazycat** [comment]
because i dont use modeline

**Comment by stardiviner** [comment]
哈哈哈，好吧。倒也是，这种情况也要考虑。

**Comment by manateelazycat** [comment]
@stardiviner Hi, I buy Dell XPS 13 yesterday, It has 4k screen.

I belive newest version has fix this issue.

Thanks for report.
