### ISSUE TITLE
HiDPi Problem: No browser is displayed, the emacs window stays empty

### ISSUE THREAD

**Issue by leoc** [manateelazycat/emacs-application-framework#288]
Hi there,
I am running Emacs 28.0.50 from Archlinux AUR emacs-git package (unchanged, as can be found here https://aur.archlinux.org/packages/emacs-git/) and followed the instructions from the readme. When I want to use `eaf-open-browser` and type google.de **I get an empty window**. 

The `*eaf*` buffer contains:

```
EAF process starting...
Session is not restored, as no data present in session file.
Session is not restored, as no data present in session file.
js: Invalid 'X-Frame-Options' header encountered when loading 'https://consent.google.de/intro/?continue=https://www.google.de/&origin=https://www.google.de&if=1&gl=DE&hl=de&pc=s': 'ALLOW-FROM https://www.google.de' is not a recognized directive. The header will be ignored.
```

How would I debug this the best? :-)

**Comment by MatthewZMD** [comment]
(setq eaf-enable-debug t)

**Comment by leoc** [comment]
Thanks I enabled it but I don't really have a clue what I should do.

*eaf*

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe3454700 (LWP 251164)]
[Detaching after fork from child process 251165]
EAF process starting...
[New Thread 0x7fffdbfff700 (LWP 251173)]
[New Thread 0x7fffdaa18700 (LWP 251174)]
[Detaching after fork from child process 251175]
[Detaching after fork from child process 251176]
[New Thread 0x7fffda087700 (LWP 251179)]
[New Thread 0x7fffd96f6700 (LWP 251180)]
[New Thread 0x7fffd8d65700 (LWP 251181)]
[New Thread 0x7fffc3fff700 (LWP 251182)]
[New Thread 0x7fffc366e700 (LWP 251183)]
[New Thread 0x7fffc2cdd700 (LWP 251184)]
[New Thread 0x7fffc234c700 (LWP 251185)]
[New Thread 0x7fffc19bb700 (LWP 251186)]
[New Thread 0x7fffabfff700 (LWP 251188)]
[New Thread 0x7fffc102a700 (LWP 251187)]
[New Thread 0x7fffab66e700 (LWP 251189)]
[New Thread 0x7fffaacdd700 (LWP 251190)]
[New Thread 0x7fffa99bb700 (LWP 251192)]
[New Thread 0x7fffaa34c700 (LWP 251191)]
[New Thread 0x7fffa902a700 (LWP 251193)]
[New Thread 0x7fff8ffff700 (LWP 251194)]
[New Thread 0x7fff8f66e700 (LWP 251195)]
Session is not restored, as no data present in session file.
[New Thread 0x7fff8ecdd700 (LWP 251208)]
[Thread 0x7fffabfff700 (LWP 251188) exited]
[Thread 0x7fffc19bb700 (LWP 251186) exited]
[Thread 0x7fffc2cdd700 (LWP 251184) exited]
[Thread 0x7fffd8d65700 (LWP 251181) exited]
```

The window stays empty. Emacs is really slow as long I have the emacs window open.

Do you have an idea how I should proceed? Thank you very much!

**Comment by MatthewZMD** [comment]
It's very likely to be some issue with HiDPI. Have you taken a look at #60 ?

**Comment by leoc** [comment]
Thank you for the referencel. The symptoms on my machine seem to be different. I do not see anything, but this issue addresses the fact that the xwindows are visible but not rescaled. I have tried the supposed work-arounds from this thread, but unfortunately to no avail :-(

**Comment by MatthewZMD** [comment]
Yeah.. there are some weird bugs working with HiDPI. Unfortunately I don't own a HiDPI screen, so cannot investigate further.

**Comment by manateelazycat** [comment]
Sorry, we are unable to reproduce this issue.

I believe this problem nothing with HiDPI, if you have more clues, feedback welcome.
