### ISSUE TITLE
Emacs no respond when magit-commit open when has EAF pdf-viewer window

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#289]
Steps to reproduce:

1. open an PDF file with EAF
2. open an Git repo and use magit commit
3. you will find that Emacs has no response (no response even I press any key, even I press [C-g]. I checked emacs process in htop, not high CPU issue, it's normal)
4. when I switch KDE virtual desktop to another, then switch back, Emacs is normal again.

I guess this might related to KDE?

**Comment by MatthewZMD** [comment]
Yes, I'm able to reproduce this bug with an EAF browser buffer and a magit buffer side by side. Will look into it.

**Comment by stardiviner** [comment]
起床好早阿，我今天是失眠，所以爬起来弄电脑了。 :)
第一次报的 EAF 问题能够重现的。哈哈哈

**Comment by MatthewZMD** [comment]
KDE一个很快的workaround就是M-SPC打开KDE的快速搜索，然后ESC关闭，一切恢复正常。

**Comment by stardiviner** [comment]
是的，就是暂时把窗口focus转到别的地方，再回来，Emacs就正常了。我猜测和EAF的focus有关。

**Comment by manateelazycat** [comment]
今天晚上我研究了一会函数 x-focus-frame 可以做到抢占焦点，我尝试在 eaf-monitor-configuration-change 函数中加上 x-focus-frame 来解决问题。

最后我发现其实时 magit 的代码里面有 focus out frame 和 focus in frame 的操作。

我认为是 magit 里面有很多 hacking code 导致焦点混乱的问题。

如果有完美的 workaround patch, 我也乐于合并到EAF中。

**Comment by manateelazycat** [comment]
EAF 从原理上没有问题。

**Comment by manateelazycat** [comment]
应该和 https://github.com/manateelazycat/emacs-application-framework/issues/408 这个问题一个原因，最新版已经修复了。

**Comment by stardiviner** [comment]
Fix confirmed. Thanks
