### ISSUE TITLE
emacs 端能否获取 eaf-browser is_focus()函数的值.

### ISSUE THREAD

**Issue by loyalpartner** [manateelazycat/emacs-application-framework#290]
我想使用 eaf-browser 里面的 is_focus 函数

(setq temp-var (eaf-call "call_function" eaf--buffer-id "is_focus"))

返回下面的错误
dbus-call-method: D-Bus error: "Traceback (most recent call last):
  File \"/usr/lib/python3.8/site-packages/dbus/service.py\", line 755, in _message_cb
    _method_reply_return(connection, message, method_name, signature, *retval)
  File \"/usr/lib/python3.8/site-packages/dbus/service.py\", line 256, in _method_reply_return
    reply.append(signature=signature, *retval)
TypeError: Expected a string or unicode object

**Comment by MatthewZMD** [comment]
修复了，现在会返回string "True"或者"False"
