### ISSUE TITLE
support for chemacs

### ISSUE THREAD

**Issue by longlu** [manateelazycat/emacs-application-framework#297]
https://github.com/plexus/chemacs

doest it support chemacs?

That will help more people try this out!

**Comment by manateelazycat** [comment]
I don't use chemacs, I haven't any plan on anything that I not use.

Any PR are welcome, I can't ensure the patch will merge.

Thanks for post.

**Comment by HollowMan6** [comment]
Hi guys! I can confirm that EAF supports chemacs, and I have made instructions for configuration. See #309
