### ISSUE TITLE
执行eaf-open后没有任何反应

### ISSUE THREAD

**Issue by Saltychtao** [manateelazycat/emacs-application-framework#30]
Ubuntu 16.04.1 LTS
emacs26

使用```M-x eaf-open``` 打开 pdf时，没有任何反应，\*message\* buffer中的信息为:
```
EAF process starting...
Opening /home/xxx/papers/1.pdf with eaf.pdfviewer
```
\*eaf\* buffer的信息为：
```
EAF process start.
```
使用M-x eaf-open www.baidu.com 时，\*message\* buffer中显示：
```
and :Symbol's value as variable is void: thing-at-point-short-url-regexp
```
\*eaf\* buffer中无任何显示。

**Comment by manateelazycat** [comment]
执行 eaf-stop-process 以后再执行 eaf-star-process 最后执行 eaf-open

出错了，粘贴一下 eaf buffer 或 messages buffer 的出错信息

**Comment by Saltychtao** [comment]
重新安装PyQt5后，已正常启动。

**Comment by manateelazycat** [comment]
@Saltychtao  Nice to hear that.
