### ISSUE TITLE
[Feature Request] Add an painting application

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#305]
I would like EAF can have an painting application.
I saw similar on this video: https://media.emacsconf.org/2019/02.html
And here is the conference notes: https://github.com/sachac/emacs-conf-2019-community-update/blob/master/index.org

I can see the paints setup, but can't know what's the technology.

Sacha is drawing painting in Emacs. Don't know what technology she use.

**Comment by manateelazycat** [comment]
Qt or JavaScript in Browser can do that.

But I hope someone can do this, not every app write by me.

IMO, Use EAF visit Google Docs is enough.

**Comment by stardiviner** [comment]
> IMO, Use EAF visit Google Docs is enough.

I have not used Google Docs, so I open it https://docs.google.com/. Only found offices document, presentation, sheet etc. No painting application found. Also Google service not works fine in China.

I tried to do a search on GitHub about painting application. There are some simple painting apps, But I don't know which one is suitable for EAF. Not even know how to integrate into EAF.

Anyway, this is not urgent task, I will keep an mind on this. Maybe someday I might can take a try. :)

**Comment by MatthewZMD** [comment]
You might want to have a look into https://github.com/chuntaro/epaint

Right, EAF could make a paint app in the future.

**Comment by manateelazycat** [comment]
> > IMO, Use EAF visit Google Docs is enough.
> 
> I have not used Google Docs, so I open it https://docs.google.com/. Only found offices document, presentation, sheet etc. No painting application found. Also Google service not works fine in China.
> 
> I tried to do a search on GitHub about painting application. There are some simple painting apps, But I don't know which one is suitable for EAF. Not even know how to integrate into EAF.
> 
> Anyway, this is not urgent task, I will keep an mind on this. Maybe someday I might can take a try. :)

Google have "Google Paint" in Google Drive Icon, it's very powerful.

**Comment by stardiviner** [comment]
I found some similar drawing diagram apps, but still can't find the "Google Paint". Hmm, I also did a search in "connect to more apps". Not found. Maybe your're using pro version?

![image](https://user-images.githubusercontent.com/378699/82785030-611f2180-9e94-11ea-8f60-b74c046517fc.png)

**Comment by manateelazycat** [comment]
> I found some similar drawing diagram apps, but still can't find the "Google Paint". Hmm, I also did a search in "connect to more apps". Not found. Maybe your're using pro version?
> 
> ![image](https://user-images.githubusercontent.com/378699/82785030-611f2180-9e94-11ea-8f60-b74c046517fc.png)

google drawing

为什么不多探索一下呢？

**Comment by stardiviner** [comment]
嗯嗯，我去探索下。

**Comment by manateelazycat** [comment]
这个放在Wiki中，看看有没有人愿意实现吧。
