### ISSUE TITLE
keyboard locking

### ISSUE THREAD

**Issue by jamzattack** [manateelazycat/emacs-application-framework#312]
This is my first time using eaf in a few weeks.

I opened a pdf using: 
M-x eaf-open RET some-file.pdf RET

Then, I could not issue any emacs commands using the keyboard.  If I switch to another window with the mouse, keyboard commands started working.  But when the eaf buffer is selected again, the same thing happens.  The mouse works fine within the eaf buffer.

Using Emacs 28.0.50 built yesterday from commit 8ef84632 and eaf from the latest commit 7a55c74

**Comment by MatthewZMD** [comment]
> I could not issue any emacs commands using the keyboard.

Does Emacs respond anything? Can you do the EAF supported commands like `C-n` or `C-p`?

**Comment by jamzattack** [comment]
No keys work at all -- not eaf bindings or normal Emacs bindings.  The mouse does work both in the eaf buffer and for Emacs window movement.

I initially assumed it was an EXWM problem, but I can reproduce it in twm as well with `emacs -q` (eaf is installed in site-lisp).

I feel like I'm not being very helpful -- is there anything in the way of log files?  I can only find webengine cache but that's hardly useful.

**Comment by MatthewZMD** [comment]
> No keys work at all -- not eaf bindings or normal Emacs bindings.  The mouse does work both in the eaf buffer and for Emacs window movement.

This somewhat feels similar to #289.

> I initially assumed it was an EXWM problem, but I can reproduce it in twm as well with `emacs -q` (eaf is installed in site-lisp).

I've heard issues regarding EAF with EXWM, though I never had the opportunity to look into it, and i'm not too sure about twm, it's a lightweight WM, might be missing something that i'm not aware of.

Were you able to get EAF working with EXWM before?

**Comment by jamzattack** [comment]
> This somewhat feels similar to #289.
After reading a bit of that issue, I tried installing xfce which still didn't work with my build of Emacs.  Switching to 26.3 fixed it, even in twm.

> Were you able to get EAF working with EXWM before?
It worked fine for me with EXWM on 27 4 months ago.

IMO this is still a bug, but you mentioned in #291 that new builds of Emacs aren't supported.  I'll leave you to decide whether or not to close this issue.

**Comment by MatthewZMD** [comment]
> It worked fine for me with EXWM on 27 4 months ago.

That's please to hear.

> Switching to 26.3 fixed it, even in twm.

Have you tried 27 this time? I believe it should also work. 28 is way too new to dedicate enough interest to support it for now.
