### ISSUE TITLE
What is the filebrowser-bin reciprocal package in Ubuntu 18.04?

### ISSUE THREAD

**Issue by Tiancheng-Luo** [manateelazycat/emacs-application-framework#313]
Excuse me, I'm really a newbie trying to use EAF. And I cannot find one of the dependencies. 
What is the Arch's reciprocal package `filebrowse-bin` in `Ubuntu 18.04`? Can anyone help me with that?

**Comment by MatthewZMD** [comment]
Please check their [Github](https://github.com/filebrowser/filebrowser) and [installation page](https://filebrowser.org/installation).
