### ISSUE TITLE
PDF Dark样式不受控制

### ISSUE THREAD

**Issue by EvanMeek** [manateelazycat/emacs-application-framework#318]
设置eaf-pdf-dark-mode为false，打开PDF仍然是黑色主题。

如果能直接提供一个函数用来切换各个工具的主题，那么真是太棒了，目前是不能直接通过设置eaf-pdf/browser/mindmap-dark-mode，然后eaf-restart-process来切换样式的么？好像必须得重启Emacs.

**Comment by manateelazycat** [comment]
PDF应用比较复杂，除了 eaf-pdf-dark-mode 变量来控制以外，它还会在关闭的时候记录当前的背景颜色，等下次打开同样的PDF文件时，自动恢复关闭时的背景颜色。

现在的颜色优先级逻辑是：

1.eaf-pdf-dark-mode为True的时候，显示黑色主题
2.eaf-pdf-dark-mode为False的时候，跟随Emacs主题
3.当上次退出的时候是黑色主题的时候，会恢复关闭前的背景模式，并且覆盖 1 和 2 的代码逻辑

你说的问题应该是步骤3引起的问题。

欢迎一起讨论一下更好的交互模式，我们讨论好一个更好方案后，我会负责调整对应的代码逻辑的。;)

感谢你的反馈。

**Comment by MatthewZMD** [comment]
我觉得可以把eaf-*-dark-mode全部设成这几种选项：true，false，follow。
true是暗色，false是亮色，follow跟随emacs主题，步骤3有点confusing

**Comment by manateelazycat** [comment]
> 我觉得可以把eaf-*-dark-mode全部设成这几种选项：true，false，follow。
> true是暗色，false是亮色，follow跟随emacs主题，步骤3有点confusing

步骤3是在主题follow模式和eaf-pdf-dark-mode变量之前的代码。
当后面加入主题follow模式的时候，前后两个阶段的代码产生了冲突。

**Comment by EvanMeek** [comment]
我认为可以保留目前的状态，可以新增手动切换主题，不需要重启Emacs，如果这样不用重构太多的话..这样既给了普通用户理所应当的体验，又给了其他用户定制的方法，个人感觉不错。

**Comment by manateelazycat** [comment]
> 我认为可以保留目前的状态，可以新增手动切换主题，不需要重启Emacs，如果这样不用重构太多的话..这样既给了普通用户理所应当的体验，又给了其他用户定制的方法，个人感觉不错。

有，Wiki里面有EAF快捷键。

用户可以在PDF文件中按i来手动切换主题，下次打开的时候会自动记住最后一次设置状态。

**Comment by MatthewZMD** [comment]
我重新梳理了一下逻辑，现在应该更明确易懂了：

1. eaf-pdf-dark-mode为true的时候，显示黑色主题
2. eaf-pdf-dark-mode为false的时候，显示白色主题
3. eaf-pdf-dark-mode为follow的时候，跟随Emacs主题
3. eaf-pdf-dark-mode为ignore的时候，会恢复关闭前的背景模式
