### ISSUE TITLE
Summer 2020/2020 中国开源之夏

### ISSUE THREAD

**Issue by HollowMan6** [manateelazycat/emacs-application-framework#328]
Hello community!

This is the issue page for [Open Source Promotion Plan - Summer 2020](https://isrc.iscas.ac.cn/summer2020/#/organisations/emacs) of [EAF](https://manateelazycat.github.io/eaf/emacs/2020/05/10/eaf-community.html). It's an honor to be the one who was chosen to do this project. The aim is to complete all the easy task, 7 medium task, 1 hard task in the [To-do List](https://github.com/manateelazycat/emacs-application-framework/wiki/Todo-List) from 1 Jul. to 30 Sep..

Here are [the tasks I choose](https://isrc.iscas.ac.cn/gitlab/summer2020/students/proj-2012153/issues) and [my project repository](https://isrc.iscas.ac.cn/gitlab/summer2020/students/proj-2012153).

Please do not hesitate to share your ideas here if you have some thoughts about what I'm doing or what exactly the function should be. 

Thanks! :-)

---
大家好!
 这里是[EAF项目](https://manateelazycat.github.io/eaf/emacs/2020/05/10/eaf-community.html)的[开源软件供应链点亮计划-暑期2020](https://isrc.iscas.ac.cn/summer2020/#/organisations/emacs)议题页面，很荣幸我此次被社区选中参加该项目。此项目要求在7.1到9.30之间完成[任务表](https://github.com/manateelazycat/emacs-application-framework/wiki/Todo-List)中所有低难度项目，7个中等难度项目，1个高难度项目。
这里是[我选择的任务](https://isrc.iscas.ac.cn/gitlab/summer2020/students/proj-2012153/issues) 和 [我的项目仓库](https://isrc.iscas.ac.cn/gitlab/summer2020/students/proj-2012153)。
如果您对我的任务有任何功能上的或者细节上的想法，请不要犹豫，立刻在此议题分享您的想法。您的意见对我来说十分重要！
谢谢！:-)

**Comment by HollowMan6** [comment]
@MatthewZMD  @manateelazycat  您好！能否介绍一下Mindmap: Support multi-line insert dons nodes中什么是dons nodes。谢谢！

**Comment by manateelazycat** [comment]
> @MatthewZMD @manateelazycat 您好！能否介绍一下Mindmap: Support multi-line insert dons nodes中什么是dons nodes。谢谢！

这个任务的详细需求：

1. Mindmap 按一个按键后，在窗口底部弹出一个小buffer
2. 在小buffer里面输入多行文字，按C-c C-c会自动插入多个节点到思维导图中，每行文字一个节点
3. 在小buffer里面按C-c C-k取消编辑，整个交互类似 Browser app 的编辑输入框的交互逻辑

**Comment by HollowMan6** [comment]
@MatthewZMD @manateelazycat 您好！能否介绍一下Mindmap: Export org with correct indent level这个任务，以目前我所了解的看来似乎缩进级别没有问题，请问什么情况下会出错？

**Comment by manateelazycat** [comment]
> @MatthewZMD @manateelazycat 您好！能否介绍一下Mindmap: Export org with correct indent level这个任务，以目前我所了解的看来似乎缩进级别没有问题，请问什么情况下会出错？

就是正常的三级思维导图的时候，导出org缩进等级会差一位，主要是解析 * 的那地方代码不够完善

**Comment by yqu212** [comment]
@HollowMan6 实现浏览器相关功能时，除Vimium外，推荐参考[Surfingkeys](https://github.com/brookhong/Surfingkeys)。

**Comment by HollowMan6** [comment]
> @HollowMan6 实现浏览器相关功能时，除Vimium外，推荐参考[Surfingkeys](https://github.com/brookhong/Surfingkeys)。

好的，谢谢您的建议

**Comment by manateelazycat** [comment]
@HollowMan6 我先把这个issue关闭了，有什么问题直接问，我和 MT 会尽快回复的。
