### ISSUE TITLE
EAF MindMap内容丢失

### ISSUE THREAD

**Issue by EvanMeek** [manateelazycat/emacs-application-framework#339]
mindmap的每个项的内容被**<>**包住的都会丢失，就像这样。
![eaf-mindmap内容丢失](https://user-images.githubusercontent.com/27056033/87333512-c972b100-c56f-11ea-8ffe-b810c78bfee6.png)

**Comment by manateelazycat** [comment]
Emacs传入数据的时候可以hash一下，然后在JS端提取一下 hash 值，这样可以避免特殊字符被过滤。
