### ISSUE TITLE
thing-at-point-short-url-regexp

### ISSUE THREAD

**Issue by 275761919** [manateelazycat/emacs-application-framework#34]
`eaf-open` 输入不带 `https://` 的网址时，得到错误：

`and: Symbol’s value as variable is void: thing-at-point-short-url-regexp`

`eaf-open` 输入带 `https://` 的网址时, 得到错误：

`EAF: /www.baidu.com is not exists.`

`*eaf*` buffer 中均没有内容。

按照 #30 的方法重装 `pyqt5` 也没有效果，但我是一直可以打开 pdf。

我感觉是依赖问题，因为在我的家里和公司的两台电脑上都复现了，打开video是提示别的。。。

两台电脑上都是装的 ArchLinux 虚拟机，没有装桌面环境，只装了自己需要的一些软件，不知道还缺少什么依赖。。。

**Comment by manateelazycat** [comment]
https 的问题已经修复了： https://github.com/manateelazycat/emacs-application-framework/commit/a5f66368677e2f0f29a87300c48bdf55218def4e

视频的问题， 需要粘贴 eaf 或者 Messages buffer 的错误信息， 我才能确定问题。

谢谢你的反馈
