### ISSUE TITLE
(Question) Remote stuff

### ISSUE THREAD

**Issue by qlibp** [manateelazycat/emacs-application-framework#342]
Is it possible to open and browse a pdf file in remote machine via local eaf?

**Comment by MatthewZMD** [comment]
Unfortunately not at the moment. I'll see if I can implement this feature when I have time.

**Comment by manateelazycat** [comment]
I suggestion use sshfs for this.
Because Mupdf library need read pdf file quickly, tramp is not best for this.

**Comment by qlibp** [comment]
> I suggestion use sshfs for this.
> 
> Because Mupdf library need read pdf file quickly, tramp is not best for this.

Thx for mentioning sshfs! It does help!

Also, could eaf help integrate mupdf with org-noter? pdf-tools is quite slow… If not yet, is it possible? If there is a way to achieve this, I hope that I could have a try on implementing this.

**Comment by MatthewZMD** [comment]
> Also, could eaf help integrate mupdf with org-noter?

cc @weirdNox
