### ISSUE TITLE
EAF, multiple xscreen and emacsclient issue

### ISSUE THREAD

**Issue by d3v-S** [manateelazycat/emacs-application-framework#344]
In my 3 monitor setup -

DISPLAY=0.1         0.0                   0.2
[ Xscreen 1]     [Xscreen 0]     [Xscreen 2] 

Issue : The emacsclient opening the first eaf-browser ends up creating  frames in the same monitor/DISPLAY, even if the requests are sent from other emacsclient running in different display.

Reproduction:
- run emacsclient in DISPLAY=0.1 and google test
- run emacsclient in DISPLAY=0.2 and google test2

The screen containing google page of test2 is created in DISPLAY 1 and closing of emacsclient in DISPLAY 2, wont shut down the frame created in DISPLAY 1. we need to close the emacsclient in DISPLAY 1 to close that frame.

**Comment by manateelazycat** [comment]
EAF  only design for current DISPLAY,  don't use it in multiple DISPLAY。
