### ISSUE TITLE
symbol lookup error for browser

### ISSUE THREAD

**Issue by ransomts** [manateelazycat/emacs-application-framework#353]
eaf-open-browser fails on startup for me. I'm running the latest manjaro distribution so I'm pulling the packages from the arch repos suggested in the readme. 

Here is the error that EAF is spitting out:

```
/usr/bin/python3: symbol lookup error: /usr/lib/python3.8/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5DBus.so.5: undefined symbol: _ZdlPvm, version Qt_5
```
and to be fair, running `readelf -Ws libQt5DBus.so.5 | grep ZdlPvm` produces this
```
  1645: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _ZdlPvm@@Qt_5
```
Is there a way to install the correct libraries I need through pacman/yay or would I need to compile my qt libs from source?

**Comment by MatthewZMD** [comment]
Can you run the installation command again:
```
yay -S python-pyqt5 python-pyqt5-sip python-pyqtwebengine python-qrcode python-feedparser python-dbus python-pyinotify python-markdown nodejs aria2 libreoffice python-pymupdf python-grip filebrowser-bin
```
If the problem persists, please paste the versions of these dependencies.

What DE/WM are you using btw?

**Comment by ransomts** [comment]
Thanks for the quick reply!

Running gnome version 3.36.4

Same result after running the yay command, including doing a cleanbuild of the aur packages

Here are the versions of the dependencies I'm pulling in, copied from the output of yay
```
Packages (11) aria2-1.35.0-2  libreoffice-fresh-6.4.5-2  nodejs-14.5.0-1  python-dbus-1.2.16-1
              python-feedparser-5.2.1-6  python-markdown-3.1.1-4  python-pyinotify-0.9.6-7  python-pyqt5-5.15.0-3
              python-pyqt5-sip-12.8.0-1  python-pyqtwebengine-5.15.0-2  python-qrcode-6.1-4

  -> Downloading PyMuPDF-1.17.4.tar.gz...
  -> Downloading python-grip-4.5.2.tar.gz...
==> Making package: filebrowser-bin 2.6.1-1 (Wed 29 Jul 2020 04:23:01 PM EDT)
  -> Downloading linux-amd64-filebrowser-2.6.1.tar.gz...
```

**Comment by MatthewZMD** [comment]
Never seen this error before, and I'm on the same version with you, however using Manjaro KDE instead.

Weird behaviors with qt 5.15, as well as #352 , ugh!

**Comment by ransomts** [comment]
Cool, thanks qt! Well just happy to report then :)

**Comment by manateelazycat** [comment]
I think it's system dependency problem, not EAF bug.
