### ISSUE TITLE
[QUESTION] Don't want Arch AUR package python-pymupdf is installed into user virtualenv dir

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#354]
I failed to setup EAF under Ubuntu system, also with some other reasons, I
switched backto Arch Linux now. I setup EAF requirements again, but got one
problem that I have not noticed before.

I use command `yay -S python-pymupdf` to install fitz module. Then I start Emacs
from KDE krunner. It can't open PDF file, reports error missing module 'fitz'.
Then I try to start Emacs from zsh which has 'virtualenv' enabled. I saw command
`yay -S python-pymupdf` installed package in my Python virtualenv. This time,
EAF can open PDF file now.

I realized I should install without virtualenv enabled. I did this. Then install
again. Seems this AUR package "python-pymupdf" still installed in user home
virtualenv directory.

What should I do?

**Comment by MatthewZMD** [comment]
You might need to reinstall it manually. 

Nevertheless, if it works then it works, where the dependency is located doesn't really matter.

**Comment by stardiviner** [comment]
I see, thanks @MatthewZMD
