### ISSUE TITLE
D-Bus error: No connection to bus, :session

### ISSUE THREAD

**Issue by salvarubiomartinez** [manateelazycat/emacs-application-framework#36]
Hi,
I installed the pytho librearies and included eaf in my init.el.
But when I start emacs I get this error:

Debugger entered--Lisp error: (dbus-error "No connection to bus" :session)
  signal(dbus-error ("No connection to bus" :session))
  byte-code("\306\307\"\204\310	@	A\"\210\202+\n\203\311\312\"\210\313\314\315#\316\f
\317&\210\306\207" [rule err dbus-debug bus dbus-service-dbus dbus-path-dbus string-match "eavesdrop" signal message "Removing eavesdrop from rule %s" replace-regexp-in-string ",eavesdrop='true'" "" dbus-call-method "AddMatch" dbus-interface-dbus] 7)
  dbus-register-signal(:session "com.lazycat.eaf" "/com/lazycat/eaf" "com.lazycat.eaf" "message_to_emacs" message)
  eval-buffer(#<buffer  *load*-377932> nil "/home/srubio/.emacs.d/elpa/eaf/eaf.el" nil t)  ; Reading at buffer position 14243
  load-with-code-conversion("/home/srubio/.emacs.d/elpa/eaf/eaf.el" "/home/srubio/.emacs.d/elpa/eaf/eaf.el" nil t)
  require(eaf)
  eval-buffer(#<buffer  *load*> nil "/home/srubio/.emacs.d/init.el" nil t)  ; Reading at buffer position 62
  load-with-code-conversion("/home/srubio/.emacs.d/init.el" "/home/srubio/.emacs.d/init.el" t t)
  load("/home/srubio/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

**Comment by lloydhuang** [comment]
I also had the problem. Fixed it as below.

    $> eval $(dbus-launch)
    $> export DBUS_SESSION_BUS_ADDRESS
    $> emacs
