### ISSUE TITLE
eaf-pdf-outline mode does not generate link for jumping

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#362]
When I press `o` in EAF PDF buffer, I got the PDF outline buffer, but it has not link for jumping to corresponding sections.

`pdf-tools` has same outline feature but has links for jumping. I think EAF should be able to implement this feature too.

**Comment by manateelazycat** [comment]
You just need move to some section, and press Enter to jump.

**Comment by stardiviner** [comment]
I tried, it did not jump. Instead it move to next line.

I recorded an video:

链接: https://pan.baidu.com/s/1C6WEJdmQxqoTf5--dqm_AA 提取码: shxc

And I checked the key `[RET]` bind command, it's `View-scroll-line-forward`.
```
RET (translated from <return>) runs the command View-scroll-line-forward (found
in view-mode-map), which is an interactive compiled Lisp function in
‘view.el’.

It is bound to RET, C-j.

(View-scroll-line-forward &optional LINES)

Scroll forward one line (or prefix LINES lines) in View mode.
See also ‘View-scroll-page-forward’, but note that scrolling is limited
to minimum of LINES and one window-full.
```

And I checked the `major-mode`, It's value is `fundamental-mode`. Seems the outline buffer is not major mode in `eaf-pdf-outline-mode`. But I check the value of `eaf-pdf-outline-mode`, It is `t` in outline buffer.

**Comment by stardiviner** [comment]
I tried different PDF documents, all not working. Should not be PDF file problem.

**Comment by loyalpartner** [comment]
@stardiviner 
(define-key 'af-pdf-outline-mode-map (kbd "RET") 'eaf-pdf-outline-jump)

**Comment by stardiviner** [comment]
@loyalpartner Thanks for your tips, I tried, still not working.

**Comment by stardiviner** [comment]
I finally figured out why caused this weird behavior.
I have a setting `(setq view-read-only t)` in my init file for presentation to press `SPACE` to scroll down.

Should this to add PR for EAF to prevent this behavior?

**Comment by MatthewZMD** [comment]
Show us the PR first

**Comment by stardiviner** [comment]
I added PR in #373
