### ISSUE TITLE
How hard would it be to add support for full-featured python browser (namely, qutebrowser)?

### ISSUE THREAD

**Issue by yantar92** [manateelazycat/emacs-application-framework#369]
**Is your feature request related to a problem? Please describe.**

EAF seems to re-implement keyboard-driven browser here. However, this does not seem to be competitive with full-featured browsers in long term. It would be great if there was support for existing full-featured and actively developed browsers. Specifically, I have qutebrowser in mind.

**Describe the solution you'd like**

I would like to be able to embed qutebrowser window into emacs buffer and interact with it using EAF framework. Ideally, with elisp module supporting native qutebrowser userscript / extension functionality.

**Describe alternatives you've considered**
A clear and concise description of an alternative solutions or features you've considered, if any.

There is built-in EAF browser indeed, but (as I descibed earlier) I do not feel like it will be on-par with larger browser project in long term. 

**Additional context**

**Comment by manateelazycat** [comment]
EAF can't embed any progrom in emacs
EAF only can embed EAF app follow with EAF framework and API interface.

Anyway, thanks for your suggestions, we can not embed qutebrowser.

And EAF browser is full feature browser for everyday use

**Comment by yantar92** [comment]
> EAF can't embed any progrom in emacs
> EAF only can embed EAF app follow with EAF framework and API interface.

Now I am confused. 

In FAQ section you mentioned that EAF is capable of

> Integrate PyQt program window into Emacs frame using QWindow Reparent technology.

Qutebrowser is essentially PyQt program. I imagine that it should be doable to implement some version of `PyQt5 widget` containing qutebrowser instead of qutebrowser's native frame. Am I missing something?

**Comment by MatthewZMD** [comment]
> EAF seems to re-implement keyboard-driven browser here. However, this does not seem to be competitive with full-featured browsers in long term

Can you elaborate in what way EAF Browser is not a full-featured browser, and please keep in mind that the goal of EAF is to use modern GUI applications *within Emacs*, it does not compete with standalone browsers including and not limited to qutebrowser.

> Qutebrowser is essentially PyQt program. I imagine that it should be doable to implement some version of PyQt5 widget containing qutebrowser instead of qutebrowser's native frame. Am I missing something?

We did tried it a long time ago, but it does not work as well as it seems. Qutebrowser is too bloated with respect to qtwebengine.

**Comment by yantar92** [comment]
> Can you elaborate in what way EAF Browser is not a full-featured browser, and please keep in mind that the goal of EAF is to use modern GUI applications within Emacs, it does not compete with standalone browsers including and not limited to qutebrowser.

It is indeed a full-featured browser. However, the development is not as active as in bigger browser projects. That's why I expect it to run behind bigger projects in long term. I thought that it would be much more beneficial to directly support, for example, qutebrowser and benefit from the developer community around it. 

In any case, if support is not possible there is not much point talking about what if qutebrowser was supported.

**Comment by MatthewZMD** [comment]
> qutebrowser and benefit from the developer community around it.

We also have a huge Emacs community, and you are very welcome to contribute to EAF as well :-)
