### ISSUE TITLE
EAF-Browser无法读取Emacs快捷键

### ISSUE THREAD

**Issue by SpringHan** [manateelazycat/emacs-application-framework#375]
**Describe the bug**
在打开了EAF Browser之后，再打开连续分屏的窗口(例如使用magit提交commit)会导致进入EAF Browser buffer时无法读取Emacs的快捷键（浏览器的快捷键可以读取）

**To Reproduce**
[74fbeea](https://github.com/manateelazycat/emacs-application-framework/commit/74fbeea2eb626cbfdf2bcc9b64f476eda92ad2f0)

**Expected behavior**
在任何情况下（除了关闭了EAF进程）能够正常使用Emacs快捷键

**Versions (please complete the following info):**
 - Distro and DE/WM: Xfce4
 - Versions of Dependencies: 使用Arch,全都是最新
 - M-x emacs-version: 28.0.50

**Comment by SpringHan** [comment]
我去尝试在KDE里进行以上操作，但依旧遇到这样的问题

**Comment by MatthewZMD** [comment]
感觉与#289 是同一个问题。你切换buffer看看能不能恢复？

**Comment by SpringHan** [comment]
试了一下那个issue的方法，的确可行，谢谢！
