### ISSUE TITLE
Problem when loggin in to github in EAF browser 

### ISSUE THREAD

**Issue by yantar92** [manateelazycat/emacs-application-framework#376]
**Describe the bug**

When trying to login to github, I am getting error page:

```
What‽
Your browser did something unexpected. Please contact us if the problem persists.
```

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

1. Open github.com
2. Open "Sign in" link from top of the page
3. Enter correct username and password
4. Hit enter

**Expected behavior**

I would like to be able to login ;)

**Versions (please complete the following info):**
 - Distro and DE/WM:
 - Versions of Dependencies:
 - M-x emacs-version:

Gentoo Linux yantar92-laptop 5.7.6-gentoo, Awesome WM 4.2-r3
PyQt5 5.14.12
PyQt5-sip 4.19.22
PyQtWebEngine 5.14.0
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2020-08-08

**Screenshots**

![eaf-browser](https://user-images.githubusercontent.com/10819266/89888901-52c6e300-dc03-11ea-8ee8-34c11581fd87.png)

**Additional context**

**Comment by MatthewZMD** [comment]
Huh, this is very weird. I'm not sure it is an EAF issue, I am replying to your issue through EAF Browser. Try clearing the cache or look at [here](https://stackoverflow.com/questions/61493358/how-to-resolve-the-your-browser-did-something-unexpected-error-when-logging-in) or [here](https://stackoverflow.com/questions/55594875/why-cant-the-github-account-be-logged-in)

**Comment by yantar92** [comment]
> Huh, this is very weird. I'm not sure it is an EAF issue, I am replying to your issue through EAF Browser. Try clearing the cache or look at here or here

As I understand, they suggested to clear cache, cookies, and make sure that password is not wrong.

I have no clue how to clear eaf's cache, but I tried to clear cookies and history. That did not help.

My password is correct - I just logged out and logged in using qutebrowser (with same version of qtwebengine). If it matters, I have 2FA with SMS code being send after I enter password. The page asking to enter the SMS code appears in qutebrowser, but I see the page from the screenshot in eaf.

**Comment by yantar92** [comment]
I recently tried to login to github using firefox and figured that I have FIDO autothentification enabled (though it is not working in qutebrowser). It might be possible that it is the reason I cannot login in eaf.

**Comment by yantar92** [comment]
Disabling the FIDO did help and I was able to login. So, the issue appears to be with the FIDO key.

**Comment by MatthewZMD** [comment]
I don't use any FIDO key, glad it finally works for you.

**Comment by yantar92** [comment]
> I don't use any FIDO key, glad it finally works for you.

I wish if FIDO worked with eaf-browser (or at least the page would not throw error). Not sure if the problem is with qtwebengine or with eaf-browser itself.  

I think the following threads may help if you consider fixing this:

https://github.com/qutebrowser/qutebrowser/issues/4049 - this looks like similar error when website requesting FIDO fails to load. They mentioned a QT bug and some workaround.
https://github.com/qutebrowser/qutebrowser/issues/3043 - this is discussion about FIDO support
