### ISSUE TITLE
Rotate PDF 90 degrees 

### ISSUE THREAD

**Issue by y2klol** [manateelazycat/emacs-application-framework#379]
Is there a way to rotate pdfs in the pdf reader 90 degrees left and right?

**Comment by HollowMan6** [comment]
Hi @y2klol ! The PR #385 has been merged into master, I think it meets your requirements. If there exists any issue, please don't hesitate to give feedbacks to me. Thanks!

**Comment by y2klol** [comment]
@HollowMan6 Just updated eaf today. Seems to be working perfectly. Exactly what I need for those two page scans. Thank you so much!
