### ISSUE TITLE
Mediaplayer - no service found

### ISSUE THREAD

**Issue by alastairdb** [manateelazycat/emacs-application-framework#38]
I can get the browser, image and pdf viewers to work fine but I have problems playing videos. I see the following message in the `*eaf*` buffer:
```
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
```
Am I missing a dependency?

**Comment by manateelazycat** [comment]
@alastairdb Looks backend of qtmediaplayer not installed success.

https://stackoverflow.com/questions/39563308/qmediaplayer-doesnt-play-anything-on-ubuntu-16-04-qt-5-6 will help?

**Comment by alastairdb** [comment]
I found a way to get videos working. I am using Ubuntu 18.04. When I set up a virtual environment and use `pip` to install PyQt5 into this environment, it does not work. If I use the PyQt5 from the standard Python interpreter (installed via `apt`), it does work

**Comment by manateelazycat** [comment]
@alastairdb I think apt or pip is same, just apt install some dependences that need by PyQt5.

Anyway, glad you make EAF works.
