### ISSUE TITLE
eaf-mermaid cannot preview

### ISSUE THREAD

**Issue by keke-cute** [manateelazycat/emacs-application-framework#384]
**Describe the bug**
eaf-mermaid cannot preview
**Versions (please complete the following info):**
 - Distro and DE/WM:
Gentoo/Openbox
 - Versions of Dependencies:
dev-python/PyQt5-5.15.0-r1::gentoo
dev-python/sip-4.19.24:0/12::gentoo
dev-python/pyinotify-0.9.6::gentoo 
dev-python/markdown-3.2.2::gentoo
dev-python/PyQtWebEngine-5.15.1_pre2006110847::gentoo
 - M-x emacs-version:27.1

**Screenshots**
<img width="1144" alt="Screen Shot 2020-08-20 at 1 17 19 AM" src="https://user-images.githubusercontent.com/37539103/90668823-38d07480-e283-11ea-86e7-40b991c513de.png">

**Comment by manateelazycat** [comment]
注意语法是否写错？ mermaid容错性还不是很强，我原来遇到过，稍微出点错误就没法预览了。

**Comment by keke-cute** [comment]
> 注意语法是否写错？ mermaid容错性还不是很强，我原来遇到过，稍微出点错误就没法预览了。

谢谢，我再多学学语法看看
