### ISSUE TITLE
退出Caret模式SPC快捷键会失效

### ISSUE THREAD

**Issue by yqu212** [manateelazycat/emacs-application-framework#386]
**Describe the bug**
退出Caret模式SPC快捷键会失效。eaf-evil里面是进入normal状态就动态绑定 按键。似乎退出Caret模式后没有进入normal状态。

**To Reproduce**
进入Caret模式，按ESC退出caret模式，按spc，页面滚动

**Expected behavior**
进入Caret模式，按ESC退出caret模式，按spc，激活leader key

**Versions (please complete the following info):**
 - Distro and DE/WM:
WSL 2, archwsl
 - Versions of Dependencies:
 - M-x emacs-version:
28.0.50

**Screenshots**

**Additional context**

**Comment by MatthewZMD** [comment]
@loyalpartner can you look into this?

**Comment by loyalpartner** [comment]
@yqu212 eaf-evil-leader-key 建议设置成 C-spc 或者 M-spc, 因为 eaf 有许多应用，不仅仅只有浏览器，在别的eaf应用里面，像 eaf-terminal ， 把 leader key 设置成 spc, 你会无法输入 空格， 我的做法是
eaf-evil-leader-key 不修改
```
  (define-key key-translation-map (kbd "SPC")
    (lambda (prompt)
      (if (derived-mode-p 'eaf-mode)
          (if (and (member eaf--buffer-app-name (list "browser" "pdf-viewer"))
                   (not (eaf-call "call_function" eaf--buffer-id "is_focus")))
              (kbd "C-SPC")
            (kbd "SPC"))         
        " ")))

```

**Comment by yqu212** [comment]
多谢回复。这是个好主意。我去试试。
