### ISSUE TITLE
eaf-open-browser

### ISSUE THREAD

**Issue by KiteAB** [manateelazycat/emacs-application-framework#388]
**Is your feature request related to a problem? Please describe.**
当我使用eaf-open-browser时  我总会遇到一些问题  比如不同页面的不同缩放  内置vimium的配置等

**Describe the solution you'd like**
能够添加自己的chrome书签  缩放  设置  以及vimium配置

**Describe alternatives you've considered**
尝试拾回chrome  但是达不到live in emacs的目的

**Comment by MatthewZMD** [comment]
vimium配置？现在已经有vimium功能了，可以详细说说你想要什么吗

**Comment by KiteAB** [comment]
> 现在已经有vimium功能了，可以详细说说你想要什么吗
vimium不能自定义键位  和一些自己的设置 像原生的vimium一样
> 现在也可以控制缩放：
我这人需求有点奇怪  不同的页面需要不同的缩放  比如github要200% b站动态要125% 主站要150%   /笑哭

**Comment by manateelazycat** [comment]
> > 现在已经有vimium功能了，可以详细说说你想要什么吗
> 
> vimium不能自定义键位 和一些自己的设置 像原生的vimium一样
> 
> > 现在也可以控制缩放：
> 
> 我这人需求有点奇怪 不同的页面需要不同的缩放 比如github要200% b站动态要125% 主站要150% /笑哭

vimium的按键都可以自定义啊？看一下Wiki

**Comment by KiteAB** [comment]
?我是傻逼   那缩放呢

**Comment by KiteAB** [comment]
只看了README  /lac

**Comment by KiteAB** [comment]
呃vimium-like的配置没找到
> vimium的按键都可以自定义啊？看一下Wiki

**Comment by MatthewZMD** [comment]
默认启动的，你直接hjkl

**Comment by KiteAB** [comment]
> 默认启动的，你直接hjkl

我colemak咋hjkl。。

**Comment by manateelazycat** [comment]
修改 eaf-browser-keybinding 里面的按键绑定就可以更改 vimium 的按键
