### ISSUE TITLE
EAF docker dbus issue

### ISSUE THREAD

**Issue by HumHongeKamyaab** [manateelazycat/emacs-application-framework#391]
I am using Ubuntu 18.04 LTS, for which I have followed https://github.com/manateelazycat/emacs-application-framework/wiki/Docker

While running following command,
```
docker run -e DISPLAY -e DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus --rm -it -v /tmp/.X11-unix/:/tmp/.X11-unix -v ${DBUS_SESSION_BUS_ADDRESS#*=}/:/run/user/1000/bus/ -v ~/.Xauthority:/home/eaf/.Xauthority  eaf
```
I am getting following error in emacs due to which I can't use eaf.
```
dbus-register-signal: D-Bus error: "No connection to bus", :session
```

**Comment by manateelazycat** [comment]
Did you run docker with root user?

**Comment by HumHongeKamyaab** [comment]
Directly running following command gives `permission denied` error
```
docker run -e DISPLAY -e DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus --rm -it -v /tmp/.X11-unix/:/tmp/.X11-unix -v ${DBUS_SESSION_BUS_ADDRESS#*=}/:/run/user/1000/bus/ -v ~/.Xauthority:/home/eaf/.Xauthority  eaf
```
while following (using *sudo*) gives `D-Bus error: "No connection to bus"` error
```
sudo docker run -e DISPLAY -e DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus --rm -it -v /tmp/.X11-unix/:/tmp/.X11-unix -v ${DBUS_SESSION_BUS_ADDRESS#*=}/:/run/user/1000/bus/ -v ~/.Xauthority:/home/eaf/.Xauthority  eaf
```

**Comment by manateelazycat** [comment]
NO，eaf need session bus，root user only have system bus，not session bus provide

**Comment by HumHongeKamyaab** [comment]
@manateelazycat 
I didn't understand. Can you elaborate more what should I do. How to get rid of permission denied without using `sudo` and root user.

**Comment by manateelazycat** [comment]
> @manateelazycat
> I didn't understand. Can you elaborate more what should I do. How to get rid of permission denied without using `sudo` and root user.

I didn't use docker, docker patch is commit by other contributor.

DBus have two bus, generate user use  "session bus", such as EAF.
Root user use "system bus", if you use sudo, docker will use root permission, then system will start "system bus", so EAF can't found "session bus".

You need find way to fix permission problem and avoid to use sudo.
