### ISSUE TITLE
eaf-open-browser can add a feature to remember the zoom size of each page and keep this zoom size when the page is opened next time

### ISSUE THREAD

**Issue by KiteAB** [manateelazycat/emacs-application-framework#392]
All as the title

**Comment by manateelazycat** [comment]
We need add "zoom dict" search code in browser.py/reset_default_zoom

**Comment by manateelazycat** [comment]
@HollowMan6 Can you help this issue.

I think we can store website zoom (just record hostname with zoom scale factor) like PasswordDB
In function browser.py/reset_default_zoom, use current url search from DB, and adjust zoom factor instead default zoom.

**Comment by HollowMan6** [comment]
> @HollowMan6 Can you help this issue?
> 
> I think we can store website zoom (just record hostname with zoom scale factor) like PasswordDB
> In function browser.py/reset_default_zoom, use current url search from DB, and adjust zoom factor instead default zoom.

OK, I'll do this when I have time later, since I have to attend classes in weekdays.

**Comment by MatthewZMD** [comment]
@HollowMan6 Thank you! 😁

**Comment by KiteAB** [comment]
ty all! close this issue now or wait 4 the new feature 2 be launched?

**Comment by manateelazycat** [comment]
@HollowMan6 Can you commit a PR? Thanks, great work!

**Comment by HollowMan6** [comment]
> @HollowMan6 Can you commit a PR? Thanks, great work!

OK, I was just going to do it

**Comment by KiteAB** [comment]
Thx!
