### ISSUE TITLE
Have you thought about doing a presentation in emacsconf2020?

### ISSUE THREAD

**Issue by kidd** [manateelazycat/emacs-application-framework#400]
It'd be just cool to show this project there!
https://emacsconf.org/2020/cfp/

Cheers!

**Comment by MatthewZMD** [comment]
Sounds like a cool idea!

**Comment by manateelazycat** [comment]
@MatthewZMD I think you are the best candidate for show EAF project in EmacsConf

My oral English is very, very bad.

**Comment by kidd** [comment]
yay! Thanks for the quick response :). The CFP deadline has been extended to Oct 7th so there's plenty of time to pick on the details.

Cheers
