### ISSUE TITLE
EAF/Browser 白屏问题

### ISSUE THREAD

**Issue by SpringHan** [manateelazycat/emacs-application-framework#402]
**Describe the bug**
有时在关闭网页buffer时，其它网页会出现白屏问题，快捷键没问题，只是内容全部消失。F5刷新网页以后网页恢复。

**To Reproduce**
https://github.com/manateelazycat/emacs-application-framework/tree/937e5300a41aea80c15fc74ad8fe5d7153c4f13c

**Expected behavior**
希望能够解决这个问题。

**Versions (please complete the following info):**
 - Distro and DE/WM: DWM
 - Versions of Dependencies: The lastest version
 - M-x emacs-version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-29

**Screenshots**
![photo](https://github.com/SpringHan/issue-photos/blob/master/eaf-browser-issue.png?raw=true)

**Comment by MatthewZMD** [comment]
hmmm，没见过这个问题

**Comment by manateelazycat** [comment]
每次窗口变动的时候会产生一次 X11/wayland reparent 的事件。

像重量级的 Gnome/KDE, 对X11/Wayland协议支持比较完善。

轻量级的窗口管理器对这方面支持比较差。

可以考虑在 Reparent 的时候加一个 Hook 信号，Reparent的时候加一些自定义的操作来绕过这个问题。

**Comment by manateelazycat** [comment]
@SpringHan 

找到 core/view.py 文件，里面有一个reparent函数。
在 reparent 函数加一个 qwindow.requestUpdate() 的代码，保存后重启Emacs.

实验一下，能不能解决你的问题？

**Comment by SpringHan** [comment]
```python
def reparent(self):
    qwindow = self.windowHandle()
    qwindow.setParent(QWindow.fromWinId(self.emacs_xid))
    qwindow.setPosition(QPoint(self.x, self.y))
    qwindow.requestUpdate()
```
加入了这行代码，重启后打开示例网页依旧有问题。

**Comment by manateelazycat** [comment]
> ```python
> def reparent(self):
>     qwindow = self.windowHandle()
>     qwindow.setParent(QWindow.fromWinId(self.emacs_xid))
>     qwindow.setPosition(QPoint(self.x, self.y))
>     qwindow.requestUpdate()
> ```
> 
> 加入了这行代码，重启后打开示例网页依旧有问题。

那估计就是窗口管理器自己协议实现的问题了。

**Comment by SpringHan** [comment]
知道了，我有时间换个桌面环境试试。  
不过我之前似乎没有出现过这样的问题。
