### ISSUE TITLE
Segmentation fault eaf-open-browser

### ISSUE THREAD

**Issue by xircon** [manateelazycat/emacs-application-framework#403]
The *eaf* buffer is empty.  EndeavourOS KDE.

Have removed and reinstalled the AUR package.  Not sure how to debug this, any ideas?

**Comment by xircon** [comment]
Fixed.  Removed all repo pyqt packages and re-installed from pip.

**Comment by MatthewZMD** [comment]
> reinstalled the AUR package

The AUR emacs-eaf is made by the community and not officially supported by us, it's *possible* that the AUR side is out of date (I haven't personally verify this claim).

> Not sure how to debug this, any ideas?

To debug a Seg Fault in the future, first set `(setq eaf-enable-debug t)` and look at the `*eaf*` buffer.

> EndeavourOS KDE.

What you experienced seems to be related to python dependency issues, different distros may differ slightly in ways of handling the Python library dependencies. Although EndeavourOS is an arch-based distro, maybe something weird is going on in there, as EAF is verified to work very nicely in Manjaro KDE by simply installing the `pyqt-` packages.

Anyways, I'm glad you found a solution, it ultimately shouldn't matter whether you install the python package from pip or from the AUR.

**Comment by xircon** [comment]
Agreed, had no problems on Manjaro.  Endeavour is Arch with an installer, so shouldn't make any difference.
