### ISSUE TITLE
eaf-org-store-link not working

### ISSUE THREAD

**Issue by xueeinstein** [manateelazycat/emacs-application-framework#404]
As a new eaf user, I just found this repo already implemented `eaf-org-store-link` in `eaf-org.el` to create org links. However, when I execute this function in a pdf buffer that is created by `eaf-open`, it doesn't work at all. 

Is this a bug? Or am I trying to use it in a wrong way?

**Comment by MatthewZMD** [comment]
This should be fixed now in the latest commit.

To use it, in a pdf file, use `C-c l` or `M-x org-store-link` to save the link, then in a org-file, use `C-c C-l` or `M-x org-insert-link` to insert the link with the description autofilled.

**Comment by xueeinstein** [comment]
@MatthewZMD Thanks for your fix!
