### ISSUE TITLE
Arch Linux: EAF application dependencies command gives errors.

### ISSUE THREAD

**Issue by dboneham** [manateelazycat/emacs-application-framework#406]
See the following pastebin. The command comes from the README. Any ideas?

https://pastebin.com/sEjDs0Fu

**Comment by zbelial** [comment]
It seems that you have installed python-dbus using pip, right? 
You can use the following command to check:
```bash
pip3 show dbus-python
```

**Comment by dboneham** [comment]
pip3 show dbus-python
WARNING: Package(s) not found: dbus-python

**Comment by dboneham** [comment]
sudo pacman -Q dbus-python
python2-dbus 1.2.16-1

**Comment by zbelial** [comment]
Sorry, my fault. 
Maybe other people using Archlinux can help you.

**Comment by MatthewZMD** [comment]
This is a problem with installing existing python packages using pacman, try fixes [here](https://unix.stackexchange.com/questions/490949/pacman-filename-exists-in-filesystem) or [here](https://emacs.stackexchange.com/questions/22717/what-does-require-package-mean-for-emacs-and-how-does-it-differ-from-load-fil)

**Comment by stefanhusmann** [comment]
dboneham, install python-dbus. python2-dbus is not python-dbus under Arch.
