### ISSUE TITLE
eaf-monitor-configuration-change makes some window(minibuffer window in my case) flicker

### ISSUE THREAD

**Issue by zbelial** [manateelazycat/emacs-application-framework#408]
**Describe the bug**
As the title says, `eaf-monitor-configuration-change` being added to `window-configuration-change-hook` results in that in some situations, minibuffer window flickers and doesn't display what should be.
Maybe issue #207 was caused by this too. 

**To Reproduce**
1. init.el 
```elisp
(add-to-list 'load-path "~/.emacs.d/packages/emacs-application-framework/")
(require 'eaf)
```

2. use `emacs -Q` to start emacs

3. open init.el and `eval-buffer`

4. use `eaf-open` to open a pdf file

5. switch to \*scratch\* and run the following code in \*scratch\*
```elisp
(read-key "read-key:
a 
b
c")  ;; C-x C-e here
```

6. minibuffer window flickers and read-key's PROMT does display.  If you now press a key, such as `a`, read-key will print "97 (#o141, #x61, ?a)"

**Expected behavior**
minibuffer window expands and displays `read-key`'s PROMT.

**Versions (please complete the following info):**
 - Distro and DE/WM:  Gentoo, KDE
 - Versions of Dependencies:  almost all the latest
 - M-x emacs-version: 27.1

**Additional context**
if remove `eaf-monitor-configuration-change` from `window-configuration-change-hook`,  then `read-key` works as expected.

**Comment by MatthewZMD** [comment]
```
(add-hook 'window-buffer-change-functions #'eaf-monitor-configuration-change)
```
Adding to `window-buffer-change-functions` instead seems to fix the problem, but we need to further investigate why is `window-configuration-change-hook` causing this problem.

**Comment by manateelazycat** [comment]
> ```
> (add-hook 'window-buffer-change-functions #'eaf-monitor-configuration-change)
> ```
> 
> Adding to `window-buffer-change-functions` instead seems to fix the problem, though introducing some delaying side-effects, we need to further investigate why is `window-configuration-change-hook` causing this problem.

这样不行，是添加这个hook，emacs窗口变化或者buffer大小变化后，qt5窗口不会跟着变。

**Comment by zbelial** [comment]
> 
> 这样不行，是添加这个hook，emacs窗口变化或者buffer大小变化后，qt5窗口不会跟着变。

The only purpose of `eaf-monitor-configuration-change` is to adjust eaf window's size when emacs's size changes, right?  
I removed `eaf-monitor-configuration-change` from `window-configuration-change-hook`, and eaf's windows can still change size according to emacs's size, just with a longer delay.  I've only tested eaf-pdf. 

我打算先从hook里删掉它用一段时间看看，`eaf-monitor-window-size-change`好像足够处理大多数窗口变化的情况了。现在虽然有点慢，但是像`read-key`函数是可以正常工作了。

另外就是，移除`eaf-monitor-configuration-change`然后再加回来，`read-key`也正常了。不过这点还没有尝试过重现，不确定是不是完全可重现的。

**Comment by manateelazycat** [comment]
> > 这样不行，是添加这个hook，emacs窗口变化或者buffer大小变化后，qt5窗口不会跟着变。
> 
> The only purpose of `eaf-monitor-configuration-change` is to adjust eaf window's size when emacs's size changes, right?
> I removed `eaf-monitor-configuration-change` from `window-configuration-change-hook`, and eaf's windows can still change size according to emacs's size, just with a longer delay. I've only tested eaf-pdf.
> 
> 我打算先从hook里删掉它用一段时间看看，`eaf-monitor-window-size-change`好像足够处理大多数窗口变化的情况了。现在虽然有点慢，但是像`read-key`函数是可以正常工作了。
> 
> 另外就是，移除`eaf-monitor-configuration-change`然后再加回来，`read-key`也正常了。不过这点还没有尝试过重现，不确定是不是完全可重现的。
> 
> PS. 中英都有，是希望如果有老外看，到时候不至于一脸懵。

正确的方式是写一个新的 window-configuration-change-hook，在监听窗口变化的同时排除minibuffer window

这样既可以让eaf窗口实时响应，又可以避免read-key的这种问题

我的英语不好，这种核心讨论还是用中文吧，避免浪费大家时间，老外会用google翻译看懂我们的讨论的，哈哈哈哈

**Comment by MatthewZMD** [comment]
> > ```
> > (add-hook 'window-buffer-change-functions #'eaf-monitor-configuration-change)
> > ```
> > 
> > 
> > Adding to `window-buffer-change-functions` instead seems to fix the problem, though introducing some delaying side-effects, we need to further investigate why is `window-configuration-change-hook` causing this problem.
> 
> 这样不行，只添加这个hook，emacs窗口变化或者buffer大小变化后，qt5窗口不会跟着变。

我之前测试了一下，窗口会变的，只是会有0.几秒的延迟

**Comment by zbelial** [comment]
> 正确的方式是写一个新的 window-configuration-change-hook，在监听窗口变化的同时排除minibuffer window
> 
> 这样既可以让eaf窗口实时响应，又可以避免read-key的这种问题
> 
> 我的英语不好，这种核心讨论还是用中文吧，避免浪费大家时间，老外会用google翻译看懂我们的讨论的，哈哈哈哈

我可以尝试改一下看看，不一定能成。有问题我再跟两位请教。

**Comment by zbelial** [comment]
> 我之前测试了一下，窗口会变的，只是会有0.几秒的延迟

这个有没有可能是因为`eaf-monitor-window-size-change`？ 这个函数里也会调用`eaf-monitor-configuration-change`。

我试了下，把这两个函数从hook里都移除，eaf窗口就不显示内容了。

**Comment by MatthewZMD** [comment]
> 这个有没有可能是因为`eaf-monitor-window-size-change`？ 这个函数里也会调用`eaf-monitor-configuration-change`。

是这样

`window-configuration-change-hook` 是C实现的，要调整起来可能有点麻烦，我回头想想

**Comment by manateelazycat** [comment]
> > 这个有没有可能是因为`eaf-monitor-window-size-change`？ 这个函数里也会调用`eaf-monitor-configuration-change`。
> 
> 是这样
> 
> `window-configuration-change-hook` 是C实现的，要调整起来可能有点麻烦，我回头想想

可以在elisp端写一个

**Comment by MatthewZMD** [comment]
> 在监听窗口变化的同时排除minibuffer window

不应该排除minibuffer，现在的情况是多行minibuffer没有成功显示。

我发现了这两点：
1. 基于1楼的`read-key`函数，如果在scratch buffer里非常快速地按`C-x C-e`，多行minibuffer就不会显示；但如果先按`C-x`等几百毫秒后按`C-e`，minibuffer就会正常显示。
2. 不需要当前frame存在eaf buffer，只要eaf在后台运行，这个bug就会出现

**Comment by zbelial** [comment]
添加了个异步的eaf-call：
```elisp
(defun eaf-call-async (method handler &rest args)
  "Call EAF Python process using `dbus-call-method' with METHOD and ARGS."
  (apply #'dbus-call-method-asynchronously
                       :session     ; use the session (not system) bus
                       "com.lazycat.eaf"  ; service name
                       "/com/lazycat/eaf" ; path name
                       "com.lazycat.eaf"  ; interface name
                       method
                       handler
                       :timeout 1000000
                       args)
    )
```

然后把`eaf-monitor-configuration-change`改为使用这个异步函数，简单测了一下`read-key`好象是没问题了。
猜测是`dbus-call-method`的同步执行或者执行结果的返回干扰了`read-key`。
今天没精力继续研究了，先睡觉了。

**Comment by manateelazycat** [comment]
> 添加了个异步的eaf-call：
> 
> ```emacs-lisp
> (defun eaf-call-async (method handler &rest args)
>   "Call EAF Python process using `dbus-call-method' with METHOD and ARGS."
>   (apply #'dbus-call-method-asynchronously
>                        :session     ; use the session (not system) bus
>                        "com.lazycat.eaf"  ; service name
>                        "/com/lazycat/eaf" ; path name
>                        "com.lazycat.eaf"  ; interface name
>                        method
>                        handler
>                        :timeout 1000000
>                        args)
>     )
> ```
> 
> 然后把`eaf-monitor-configuration-change`改为使用这个异步函数，简单测了一下`read-key`好象是没问题了。
> 猜测是`dbus-call-method`的同步执行或者执行结果的返回干扰了`read-key`。
> 今天没精力继续研究了，先睡觉了。

这个推理应该是正确的，再多测一下，没啥问题就可以合并。

**Comment by zbelial** [comment]
我平时用pdf/mindmap/browser，用几天看看。

**Comment by MatthewZMD** [comment]
如果我没弄错这个bug也会影响lsp-mode进入新的project时的popup，你也可以试试

**Comment by zbelial** [comment]
> 如果我没弄错这个bug也会影响lsp-mode进入新的project时的popup，你也可以试试

是的。我就是因为用lsp时的这个问题才查到eaf这的。改了之后lsp也没问题了。

**Comment by MatthewZMD** [comment]
> 添加了个异步的eaf-call：
> 
> ```emacs-lisp
> (defun eaf-call-async (method handler &rest args)
>   "Call EAF Python process using `dbus-call-method' with METHOD and ARGS."
>   (apply #'dbus-call-method-asynchronously
>                        :session     ; use the session (not system) bus
>                        "com.lazycat.eaf"  ; service name
>                        "/com/lazycat/eaf" ; path name
>                        "com.lazycat.eaf"  ; interface name
>                        method
>                        handler
>                        :timeout 1000000
>                        args)
>     )
> ```
> 
> 然后把`eaf-monitor-configuration-change`改为使用这个异步函数，简单测了一下`read-key`好象是没问题了。
> 猜测是`dbus-call-method`的同步执行或者执行结果的返回干扰了`read-key`。
> 今天没精力继续研究了，先睡觉了。

eaf-call-async看起来没问题，不过注意一下这个函数要跟eaf-call尽量相似，比如return t或者nil。

我马上会push一个新的commit修小bug，你过会rebase一下。

**Comment by zbelial** [comment]
> eaf-call-async看起来没问题，不过注意一下这个函数要跟eaf-call尽量相似，比如return t或者nil。

没太明白。返回是在handler里处理的（对应eaf-call里的cond那部分），handler是回调函数。如果只针对这个issue里的问题，我觉得handler传nil就可以。后续如果还有需要用这个异步函数的地方，再具体考虑是否需要修改。如何？

**Comment by MatthewZMD** [comment]
```
(defun eaf-call (method &rest args)
  "Call EAF Python process using `dbus-call-method' with METHOD and ARGS.

Return t or nil based on the result of the call."
  (let ((result (apply #'dbus-call-method
                       :session     ; use the session (not system) bus
                       "com.lazycat.eaf"  ; service name
                       "/com/lazycat/eaf" ; path name
                       "com.lazycat.eaf"  ; interface name
                       method
                       :timeout 1000000
                       args)))
    (cond ((equal result "True") t)
          ((equal result "False") nil)
          (t result))))
```
参考eaf-call，为了一致性最好将eaf-call-async也写成这样

**Comment by zbelial** [comment]
我是觉得没必要也不合适；所以还是不清楚你觉得应该怎样写才一致。要不就你写一个吧？

**Comment by MatthewZMD** [comment]
没事，你就先这样吧。

**Comment by zbelial** [comment]
有点怀疑你没注意到`dbus-call-method-asynchronously`但是又觉得不应该。你如果有更好的实现方法（包括你说的代码一致性方面）还是希望你能分享一下，总比合并不够好的代码进EAF更好，不过我确实是想不到了。

**Comment by MatthewZMD** [comment]
我的意思是，尽管现在eaf-call-async所需要跑的python函数不会返回boolean "True/False"，但以后可能会。所以我建议在设计的时候跟eaf-call一样，提前准备好转换True为t/False为nil的handler是比较好的做法。但毕竟是以后的事情，暂时不急。

> 后续如果还有需要用这个异步函数的地方，再具体考虑是否需要修改。

**Comment by manateelazycat** [comment]
我已经按照zbelial的方法在最新版修复了这个问题。

DBus异步的回调处理先这样吧，以后异步方法多了，我们再定义回调函数的处理标准。
