### ISSUE TITLE
High memory and cpu usage

### ISSUE THREAD

**Issue by rustamusmanov973** [manateelazycat/emacs-application-framework#411]
**Describe the bug**
Opening 80 buffers (eaf-open-url) results in drastic increase in resource consumption (from htop):
 LA 0.54 -> 14.31
thr 378 -> 1234
MEM 3.78 -> 13.1 GB

For comparison: If i open this 80 urls as tabs in firefox (in exwm):
MEM -> ~6.5 GB
LA    -> ~1.5 
If I open this 80 urls as windows in firefox (exwm):
MEM -> ~ 14 GB
LA -> ~1.5

**To Reproduce**
You can run this command with some 80 tabs: 
`(mapcar 'eaf-open-url (split-string "https://github.com/manateelazycat/emacs-application-framework/wiki
https://github.com/manateelazycat/emacs-application-framework
.... (76 lines) ...
https://nixos.wiki/wiki/Python
https://www.google.com/search?client=firefox-b-d&q=too+high+cpu+load+eaf+browser+emacs" "\n"))`

**Expected behavior**
Eaf browser consumes less cpu resources (like firefox)

**Versions (please complete the following info):**
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Kernel Version: 5.8.11-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 23.4 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530
 - M-x emacs-version:
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-28
![eaf](https://user-images.githubusercontent.com/27998534/96365913-c37f0400-114c-11eb-8492-360124bcdfae.png)

**Comment by manateelazycat** [comment]
EAF browser base on chromium，chromium use high memory than firefox。
