### ISSUE TITLE
eaf-open video only have sound, window is all black

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#42]
When I open a mp4 video with `eaf-open`. It has sound but window is all black.
Emacs version: GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05

**Comment by stardiviner** [comment]
I almost forgot this issue.
I checked out, it's some mp4 video and .mkv video format. I confirmed some video can play with image display.

The .mkv video I was download from YouTube here https://www.youtube.com/watch?v=4f3fiWcNt7Y with command-line tool `youtube-dl` (which can be installed through command `pip install youtube-dl`).
eaf report warning for the .mkv video file:
```
EAF doesn’t know how to open /home/stardiviner/Downloads/Oz - static site generation with live code reloading-4f3fiWcNt7Y.mkv.
```
About another .mp4 video, I uploaded to Baidu Yun here:
链接: https://pan.baidu.com/s/1yNQe3jPLwrD7E0Gl7oFyJg 提取码: 4y6w 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by manateelazycat** [comment]
I have add patch to support mkv file https://github.com/manateelazycat/emacs-application-framework/commit/33b67a698ca10f3871d5ede340f73400f5133dba

I need figure out why mp4 file is blank.

**Comment by manateelazycat** [comment]
我测试了一下，感觉是视频的问题也。

我用 vlc 和 mpv 播放都没法查看画面，只有声音

**Comment by manateelazycat** [comment]
如果其他播放器可以播放，但是EAF视频播放器没法播放，请重新打开此issue

**Comment by stardiviner** [comment]
I confirmed that this video can't be play by `mpv`. Weird, I remember I can play it before (about 5 monthes ago .... :)  ) Anyway, added `.mkv` video type is great. And other `mp4` videos work fine.
And thanks @manateelazycat
