### ISSUE TITLE
Refresh a PDF open with eaf-open on file change

### ISSUE THREAD

**Issue by darcamo** [manateelazycat/emacs-application-framework#421]
**Is your feature request related to a problem? Please describe.**

EAF can open PDFs and its really great specially due to the continuous scrolling. However, if the file change in the disk there is no apparent way to refresh the buffer. The only way seems to be killing the buffer and opening the PDF again. Reverting the buffer on a file change is specially important when one is creating the PDF through Latex.

**Describe the solution you'd like**
A keybinding to allow eaf-open to refresh the file content and/or respect `auto-revert-mode`.

**Describe alternatives you've considered**
No alternative besides closing the file and opening it again, as far as i could tell.

**Comment by manateelazycat** [comment]
I add refresh_file command in newest version.

Can you try it?

**Comment by manateelazycat** [comment]
Close issue, please re-open this issue if have any problem.

Thanks for feedback.

**Comment by czikus** [comment]
I'm having trouble with the refresh_file binding. It does not seem to work for me. How can I debug it?

**Comment by manateelazycat** [comment]
> I'm having trouble with the refresh_file binding. It does not seem to work for me. How can I debug it?

show you code?

**Comment by czikus** [comment]
Not exactly sure what you mean? I'm using the master branch and simply open a PDF using `(eaf-open "file.pdf")`. Then pressing 'r' does nothing (does not refresh the file), despite it being listed as a binding for refresh_file.

**Comment by manateelazycat** [comment]
> Not exactly sure what you mean? I'm using the master branch and simply open a PDF using `(eaf-open "file.pdf")`. Then pressing 'r' does nothing (does not refresh the file), despite it being listed as a binding for refresh_file.

if pdf file is not change after eaf-open，refresh_file is so fast reload that you can't feeling change

**Comment by czikus** [comment]
I refer to the situation when the file has changed. Still `r` does nothing.

**Comment by manateelazycat** [comment]
> I refer to the situation when the file has changed. Still `r` does nothing.

Can you give me change pdf way? 

More details, If I can reappear problem, I can fix it.

**Comment by czikus** [comment]
More specifically, I'm using org mode and export an org note to PDF using `org-latex-export-to-pdf`. Then I do `(eaf-open pdffile)`. The first time, when EAF buffer is not yet open, the up-to-date PDF is displayed. The next time, the PDF is not updated when `(eaf-open pdffile)` is called, and also when I press `r` in the EAF buffer. Besides the problem with the binding, it would be great if the PDF was refreshed when `(eaf-open pdffile)` is called the second time.

**Comment by manateelazycat** [comment]
@luhuaei Can you help fix this issue?

Press r in EAF PDF buffer to refresh content.

**Comment by luhuaei** [comment]
I try reappear this problem, then fix it. :smile:

**Comment by manateelazycat** [comment]
test newest version，re-open issuse if still have problem

**Comment by czikus** [comment]
Great, changes to the PDF are now detected automatically.
