### ISSUE TITLE
Change font in EAF browser

### ISSUE THREAD

**Issue by KiteAB** [manateelazycat/emacs-application-framework#424]
![](https://i.loli.net/2020/10/24/iS1oLYH3gPOTdUQ.png)
Like "置" character, many Chinese characters don’t look good, so how to modify the English and Chinese fonts in the EAF browser

**Comment by manateelazycat** [comment]
check https://github.com/manateelazycat/emacs-application-framework/commit/184ede6c679c22efceefc196b946c29b6f7ed979
