### ISSUE TITLE
eaf-terminal cannot scroll down or up

### ISSUE THREAD

**Issue by mackong** [manateelazycat/emacs-application-framework#430]
**Describe the bug**
in eaf-terminal cannot scroll down or up by M-v, C-v, M-n, M-p

**To Reproduce**
open eaf-terminal, enter M-v

**Expected behavior**
Scroll down page.

**Versions:**
OS: Manjaro Linux, Gnome 3.36.6
QT: 5.15.0-5
PyQT: 5.15.1
Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-09-03

**Screenshots**

**Additional context**
Already tried with *emacs -Q*, same problem

**Comment by manateelazycat** [comment]
No idea now, any PR are welcome.

I guess we can fix this issue from xterm.js options or CSS file?

**Comment by mackong** [comment]
pr #433 fix this issue.
