### ISSUE TITLE
eaf-browser markers not support Web Dingtalk very well

### ISSUE THREAD

**Issue by mackong** [manateelazycat/emacs-application-framework#436]
**Describe the bug**
eaf-browser markers not support Web Dingtalk very well

**To Reproduce**
open [https://im.dingtalk.com/](Web Dingtalk) in eaf-browser, enter *f*

**Expected behavior**
Element such as dingtalk group item has markers.

**Versions (please complete the following info):**
 OS: Manjaro Linux, Gnome 3.36.6
QT: 5.15.0-5
PyQT: 5.15.1
Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-09-03

**Screenshots**
![image](https://user-images.githubusercontent.com/2212586/97783184-0de29500-1bd1-11eb-85b9-facffe03f930.png)

**Additional context**

**Comment by MatthewZMD** [comment]
I don't have a dingtalk account, I am unable to investigate into this issue further

**Comment by mackong** [comment]
好的，我自己试试看能不能搞定。

**Comment by MatthewZMD** [comment]
#445 should fix it.
