### ISSUE TITLE
使用出现错误

### ISSUE THREAD

**Issue by hengyuancao** [manateelazycat/emacs-application-framework#44]
每个命令都会出现这个错误 *eaf* exited abnormally with code 1  

我想了解这个错误代码1可能是我哪里出现问题了

**Comment by manateelazycat** [comment]
一般都是 python 的包没有装, 找 *eaf* 的 buffer 看出错日志.

**Comment by hengyuancao** [comment]
####  这个原因找到了，是因为dbus-python不能pip直接装，不过这个弄好了。  

#### 又出现一个问题，打开链接、视频时没有错误提示，但是画面显示为空。  

*  一个现象：打开链接时底下状态栏会显示|about:blank|,就像IE浏览器没有输入地址一样
-----------------------------------------------------------------------------------------------
EAF process start.
Traceback (most recent call last):
  File "/home/yuan/.emacs.d/elsp/emacs-application-framework/eaf.py", line 325, in restore_buffer_session
    session_dict = json.load(session_file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
No data in session file, no need restore session.

**Comment by manateelazycat** [comment]
这个报错没有问题, 你的是什么Linux发行版? 用的啥窗口管理器?

把详细的环境和截图报一下

**Comment by hengyuancao** [comment]
#### 1.系统环境
*  在清华开源站下载的xubuntu18
* 版本名称：*xubuntu-18.04.1-desktop-amd64.iso*
* 我没有对系统进行过修改美化
#### 2.emacs 版本
GNU Emacs 27.0.50
Copyright (C) 2018 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
#### 3.python环境
Python2.7   
python3.6（默认）

**Comment by manateelazycat** [comment]
EAF使用的是技术需要 X11 和 Composite 支持.

也就是说, Gnome3/Wayland是不支持的(没有X11 reparent支持), XFce/LXDE是不支持的(没有混合支持)

目前我能够知道可以工作的环境只有 KDE/DDE/Unity, 建议你直接用 KDE 吧, 没有问题.

因为EAF用的都是操作系统底层技术, 所以没法让所有桌面环境都可以运行, 抱歉.

**Comment by hengyuancao** [comment]
好的谢谢 @manateelazycat
