### ISSUE TITLE
html5 player is not supported?

### ISSUE THREAD

**Issue by KiteAB** [manateelazycat/emacs-application-framework#440]
![2020-11-11_20-26.png](https://i.loli.net/2020/11/11/mk23GqtgbUYZ7CI.png)

**Comment by MatthewZMD** [comment]
发一下链接，B站是默认支持html5视频的。

**Comment by KiteAB** [comment]
> 发一下链接，B站是默认支持html5视频的。

我这边打开的所有视频都是这个界面

**Comment by MatthewZMD** [comment]
![DeepinScreenshot_select-area_20201112055035](https://user-images.githubusercontent.com/12422335/98930771-12e5f500-24ab-11eb-8c8c-4d8a490a0452.png)

不知道你的b站出了什么问题，我不论从Chrome还是EAF Browser打开B站视频，如果设置的是Flash，都会提供用html5播放的选项的，建议你去问问B站客服。

**Comment by KiteAB** [comment]
> ![DeepinScreenshot_select-area_20201112055035](https://user-images.githubusercontent.com/12422335/98930771-12e5f500-24ab-11eb-8c8c-4d8a490a0452.png)
> 
> 不知道你的b站出了什么问题，我不论从Chrome还是EAF Browser打开B站视频，如果设置的是Flash，都会提供用html5播放的选项的，建议你去问问B站客服。

客服给出的解释是换个浏览器  但是我寻思着我几天之前还可以用eaf看视频啊……

**Comment by MatthewZMD** [comment]
很奇怪，可以去emacs-china论坛上问问有没有其他人遇到过你这个问题。

**Comment by Eason0210** [comment]
我也遇到一样的问题。@KiteAB 你解决了吗？ 

Windows 10  
Emacs 28

**Comment by KiteAB** [comment]
> 我也遇到一样的问题。@KiteAB 你解决了吗？
> 
> Windows 10
> Emacs 28

我重装了所有环境就可以了
