### ISSUE TITLE
[eaf-mindmap] escape/unescape makes jsmind's support_html invalid

### ISSUE THREAD

**Issue by zbelial** [manateelazycat/emacs-application-framework#444]
To solve the problem in issue #339 , escape/unescape was added. But it makes html tags in topics have no effect.

**Comment by zbelial** [comment]
我本来是想用<br/>来换行，要不有些行比较长，看起来不方便。我看了下，应该是escape导致这些 tag 都没起作用。
但是像 #339 里的问题确实需要解决。

我现在想到的方法，是判断topic的开头如果是某个特定字符，例如空格或者‘（单引号）之类的，就不做escape/unescape，这样可以部分解决问题。

**Comment by zbelial** [comment]
有点新的想法。
想法的前提是使用jsmind的support_html功能，也就是要去掉目前的escape/unescape。

1. 加一个配置项，用来配置是否开启support_html，默认是不开启。
    这样即使去掉了escape/unescape，也不会给目前的使用者造成问题。
2. （可选）可以加一个动态开关support_html功能的函数，在编辑mindmap的时候切换。

这种全局配置support_html感觉不够灵活，但是没想到能做到node级别控制的好方法。

**Comment by manateelazycat** [comment]
> 有点新的想法。
> 想法的前提是使用jsmind的support_html功能，也就是要去掉目前的escape/unescape。
> 
> 1. 加一个配置项，用来配置是否开启support_html，默认是不开启。
>    这样即使去掉了escape/unescape，也不会给目前的使用者造成问题。
> 2. （可选）可以加一个动态开关support_html功能的函数，在编辑mindmap的时候切换。
> 
> 这种全局配置support_html感觉不够灵活，但是没想到能做到node级别控制的好方法。

我看了 support_html 代码，比较简单：
```
if(this.opts.support_html){
                    $h(d,node.topic);
                }else{
                    $t(d,node.topic);
                }
```
就三处，add, edit, update

我想到比较一个好的方法是，在创建节点的时候区分，有两种创建节点的方法：
1. 创建普通节点
2. 创建html节点

通过创建节点的时候，给 node 设置一个 type 的属性，然后现有 support_html 的代码都换成 node.type === plain 或 node.type === html 的方式。

这样默认用普通节点，喜欢html的用html节点，不过这种方法还要处理 type 保存到文件和从文件恢复的情况。

**Comment by zbelial** [comment]
这种方法代码改动相对有点多，当然我不懂js，不清楚是不是改起来比较复杂。

我还是挺倾向于通过空格之类的来标识一下是否需要escape，改动小，学习成本我觉得也低。唯一的问题就是不够优雅。

所以，我觉得先考虑下要不要支持html，如果要支持，评估一个方法是否可接受的标准是什么？

**Comment by zbelial** [comment]
这种方法代码改动相对有点多，当然我不懂js，不清楚是不是改起来比较复杂。

我还是挺倾向于通过空格之类的来标识一下是否需要escape，改动小，学习成本我觉得也低。唯一的问题就是不够优雅。

所以，我觉得先考虑下要不要支持html，如果要支持，评估一个方法是否可接受的标准是什么？

**Comment by manateelazycat** [comment]
> 这种方法代码改动相对有点多，当然我不懂js，不清楚是不是改起来比较复杂。
> 
> 我还是挺倾向于通过空格之类的来标识一下是否需要escape，改动小，学习成本我觉得也低。唯一的问题就是不够优雅。
> 
> 所以，我觉得先考虑下要不要支持html，如果要支持，评估一个方法是否可接受的标准是什么？

支持Html的目的本质是换行，如果通过CSS样式可以强制限定Node的最大宽度，我觉得不用支持Html更好。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/emacs-application-framework/commit/ea2f671f600cfdaf7ebf5055b9a10c749bd22706 已经增加了max-width, 所以不用支持 html 就可以自动换行了。
