### ISSUE TITLE
Support native Wayland with pgtk emacs

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/emacs-application-framework#449]
This is a continuation of the discussion from akirakyle/emacs-webkit#10 about EAF supporting native Wayland so it works with pgtk emacs.

Currently, EAF works with Wayland through XWayland, since EAF uses `QWindow::setParent`, which uses `xcb` in its source code, and does not work natively (using emacs `--with-pgtk`).

It is also reported that

> I just realized another issue that EAF would need to overcome to work on wayland, but I can't think of any way it can be solved as it seems to go against wayland's design. EAF currently uses the x11 XID that Emacs reports in the window-id frame-parameter. AFAIK there is no equivalent to an XID on wayland as applications shouldn't really be able to identify and tell the compositor to affect another app's windows (yay security?!). Thus emacs --with-pgtk reports the pointer to the GtkWindow in window-id. I don't think there's anything useful Qt could do with this Gtk pointer.

**Comment by manateelazycat** [comment]
Has add todo list, close issue.

**Comment by VitalyAnkh** [comment]
Are there any updates for this issue?
Why not make this a tracking issue for EAF wayland support? I'm yearning for the wayland support for I'm using pgtk emacs and stuck for this.

**Comment by manateelazycat** [comment]
> Are there any updates for this issue?
> Why not make this a tracking issue for EAF wayland support? I'm yearning for the wayland support for I'm using pgtk emacs and stuck for this.

its in todolist, I don't think this issue can fix in short time

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/commit/af392dc299c9ab3a1e000598b471ab540c9603f5

I haven't used the pgtk version of Emacs. The above patch is a patch that I wrote blindly based on the EAF principle.

This patch means that when EAF finds that Emacs is in the Wayland native (also known as the pgtk version) environment, it will use the same strategy as macOS: "Show the EAF window when Emacs is focused, and hide the EAF window when Emacs loses focus. "Although it is not as perfect as multi-process reparent in X11 and XWayland environments, it should be no problem for daily use.

Welcome to try it, and welcome feedback.

**Comment by manateelazycat** [comment]
EAF has support Wayland native https://github.com/emacs-eaf/emacs-application-framework/commit/8df41d0058a59affbec19f013b504259305109cc

**Comment by MatthewZMD** [comment]
Related #1019

**Comment by manateelazycat** [comment]
Support by https://github.com/emacs-eaf/emacs-application-framework/commit/29a5e56e6e0fdad161bc83064f4f04dbda7d8d59

If you are using Wayland environment, you need to execute the command `cp -r emacs-application-framework/gnome-shell/eaf-wayland@emacs-eaf.org ~/.local/share/gnome-shell/extensions` and activate the Gnome-Shell plugin `eaf-wayland@emacs-eaf.org` in Gnome3.
