### ISSUE TITLE
Some Gentoo recommendations

### ISSUE THREAD

**Issue by Phate6660** [manateelazycat/emacs-application-framework#451]
Python must be compiled with the `sqlite` USE flag.

Emacs must be compiled with the `dbus` USE flag.

When installing PyQt5 you will need to have the following USE flags enabled:
- `gui`
- `network`

When installing qtwebengine, I would enable the `jumbo-build` USE flag as it should drastically decrease the compile time.

**Comment by manateelazycat** [comment]
Can you write Gentoo docs in Wiki ?

Or send doc here, I help you post it in Wiki.

Thanks for help! ;)

**Comment by Phate6660** [comment]
Sure, no problem. More than happy to help. I was just unsure, because I didn't want to fully go through with it.

But actually, I think I will. I'd feel bad for including incomplete info.

Give me a while to install everything, since I'm on Gentoo I'll have a lot of compiling to do. Especially QtWebEngine which is notorious for taking forever.

**Comment by manateelazycat** [comment]
Thanks man.

**Comment by manateelazycat** [comment]
@Phate6660 I have change Wiki setting, everyone can edit wiki pages now.

Free feel to add Gentoo page in Wiki.

Thanks again! ;)

**Comment by Phate6660** [comment]
No problem. I will continue to update my original post in this issue until I believe I have everything, and will then edit the wiki once complete.

**Comment by Phate6660** [comment]
I've now gotten at least `eaf-open-browser` working.

I'll create a wiki page, and update it whenever I find something not working with more that needs to be done.

**Comment by Phate6660** [comment]
Just wanted to say that this is really cool!

It really was worth compiling everything.

**Comment by Phate6660** [comment]
https://github.com/manateelazycat/emacs-application-framework/wiki/Some-Gentoo-Specific-Instructions-and-Recommendations

**Comment by MatthewZMD** [comment]
Thank you! Very glad you find it fun and meningful!!

**Comment by Phate6660** [comment]
I'm going to assume that the issue is Gentoo related (probably just a missing USE flag again), but I can't get the terminal to launch. It opens for less than a second and closes.

All that the `messages` buffer told me is:

```
[EAF] Process starting...
[EAF/terminal] Opening /home/valley/
[EAF] *eaf* aborted
[EAF] Process already terminated.
```

I do in fact have NodeJS installed. Is there a way to debug log EAF, or perhaps a way to test through NodeJS what the issue could be?

**Comment by Phate6660** [comment]
Actually, just found this after switching through my buffers:

```
EAF process starting...
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /index.html HTTP/1.1" 200 -
Session is not restored, as no data present in session file.
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm/lib/xterm.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm-addon-attach/lib/xterm-addon-attach.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm-addon-fit/lib/xterm-addon-fit.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm-addon-search/lib/xterm-addon-search.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm-addon-web-links/lib/xterm-addon-web-links.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /dark_theme.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Nov/2020 14:52:32] "GET /node_modules/xterm/css/xterm.css HTTP/1.1" 200 -
js: WebSocket connection to 'ws://127.0.0.1:59399/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
Traceback (most recent call last):
  File "/home/valley/.emacs.d/emacs-application-framework/app/terminal/buffer.py", line 95, in focus_terminal
    QApplication.sendEvent(self.buffer_widget.focusProxy(), event)
RuntimeError: wrapped C/C++ object of type BrowserView has been deleted
```

**Comment by Phate6660** [comment]
This seems like a separate issue, so I'll open a new one.
