### ISSUE TITLE
Forcing color inversion for PDFs with pages that are entirely images

### ISSUE THREAD

**Issue by Jdogzz** [manateelazycat/emacs-application-framework#453]
**Is your feature request related to a problem? Please describe.**
I have found the PDF color inversion to work perfectly for example PDFs which consist of text with images throughout. However, for PDFs which are full page images, the color inversion does not activate and leaves the document rendered as it originally appears. To the best of my knowledge, the color inversion keybinding `i` has no effect on documents that fit this criteria (I seem to presently be suffering from #237 but I have been able to successfully toggle color inversion on other documents which consist of text with some images, so I think I would have been able to do the same with the documents that are full page images). I have gone through the list of keybindings and see no alternative color inversion which would force documents like this to be inverted. 

**Describe the solution you'd like**
I would like to have a key binding which forcefully applies the color inversion irrespective of regions classified as images.

**Describe alternatives you've considered**
Another possible acceptable solution is to add a third toggle when using `i` which cycles through: dark (leave images alone), dark (including images), original color.

**Comment by manateelazycat** [comment]
@HollowMan6 can you look this issue?

**Comment by MatthewZMD** [comment]
@HollowMan6 Can you add a variable that exclude #308 changes?

**Comment by HollowMan6** [comment]
> @HollowMan6 Can you add a variable that exclude #308 changes?

Ok, but I'm busy with exams this week, and I'll look into this at the weekends when I have time.

**Comment by HollowMan6** [comment]
Hi @Jdogzz , I've made the patch #457 adopting your alternative solution cuz I think it's a better way. Please feel free if you have any other suggestions. Thanks!
