### ISSUE TITLE
README fix - EXWM rebinding

### ISSUE THREAD

**Issue by xgqt** [manateelazycat/emacs-application-framework#454]
In README.md:

>EXWM is an X11 Window Manager, it manages and controls other software using a keyboard, but it cannot modify, customize and extend the behavior of other software. For example, it cannot modify the behavior when you press a key in Chrome or a PDF viewer.

But EXWM can do it

```elisp
  (exwm-input-set-simulation-keys
   '(
     ;; movement
     ([?\C-b] . left)
     ([?\M-b] . C-left)
     ([?\C-f] . right)
     ([?\M-f] . C-right)
     ([?\C-p] . up)
     ([?\C-n] . down)
     ([?\M-v] . prior)
     ([?\C-v] . next)
     ([?\C-k] . (S-end delete))
     ;; cut/paste
     ([?\C-w] . ?\C-x)
     ([?\M-w] . ?\C-c)
     ([?\C-y] . ?\C-v)
     ;; search
     ([?\C-s] . ?\C-f)
     ))
```

It is true that "it cannot modify [...] other software" but in case of key presses they can be changed.

**Comment by manateelazycat** [comment]
done

**Comment by xgqt** [comment]
thanks for cooperation

**Comment by MatthewZMD** [comment]
Right, tho the point from the EmacsConf still stands
