### ISSUE TITLE
[Improve] Hide mouse cursor when watching video or inputting texts

### ISSUE THREAD

**Issue by KiteAB** [manateelazycat/emacs-application-framework#456]
As the title.

**Comment by manateelazycat** [comment]
Why need hide cursor when input?

**Comment by manateelazycat** [comment]
Hide mouse when browser fullscreen has implement.

I don't think we need hide cursor when input text, it's very confuse user.

**Comment by KiteAB** [comment]
This is clearly not necessary. But with a small probability, the cursor will block the input text

**Comment by manateelazycat** [comment]
> This is clearly not necessary. But with a small probability, the cursor will block the input text

hide mouse when input, will case many bugs

because you don't know how javascript will write
