### ISSUE TITLE
Can't use global Emacs keybindings inside EAF-modes

### ISSUE THREAD

**Issue by AuroraDragoon** [manateelazycat/emacs-application-framework#461]
When opening any EAF mode, I lose the ability to use my global emacs keybindings, most importantly M-x. This is a rather big deal as I would ideally like to be able to use commands from inside these modes (primarily have the ability to switch buffers). Not sure if this is intended or not but its very annoying for me. 

**To Reproduce**
I followed the installation instructions on the README, opened the EAF browser and pdf-viewer (I would assume this is the behavior in all the EAF modes though) and couldn't use any keybindings.

**Expected behavior**
The ability to use M-x and other keybindings globally set by me, or even the Emacs defaults at the very least 

**Versions (please complete the following info):**
 - Distro and DE/WM: Manjaro Qtile 
 - Versions of Dependencies: Most of them I just installed from the AUR so latest version of all of them
 - M-x emacs-version: GNU Emacs 27.1

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
works on kde, gnome, xfce and lxde

i believe it's bug of wm

**Comment by AuroraDragoon** [comment]
Do you possibly know what exactly is causing it. I could try to help with fixing this if you give me a guideline of where to look for it. Collaboration for fixing bugs is kind of the essence of FOSS projects

**Comment by manateelazycat** [comment]
> Do you possibly know what exactly is causing it. I could try to help with fixing this if you give me a guideline of where to look for it. Collaboration for fixing bugs is kind of the essence of FOSS projects

many wm is incomplete implement of x11 wm protocl

sorry, so many linux wm exists, i havent time to debug cause

please switch standard desktop environment, such as, kde,gnome,xfce

**Comment by MatthewZMD** [comment]
You're not the first person encountering this issue on a WM, we _suspect_ that it might be related to some Window Managers not implementing some x11 protocols properly, as EAF works fine in KDE/xfce/gnome etc.

At this point we really don't know how to fix them or what exactly is wrong in the WM (or maybe in the EAF code) so unfortunately cannot provide you any further guides, and we don't even use these WMs ourselves, so we lack proper investigation in them. :(

So the quickest workaround we can provide is to use some DE that we know works very well instead.

**Comment by AuroraDragoon** [comment]
I think I found a workaround for the problem, it ain't perfect, but it will have to do, as I definitely want to use this package. The problem lies on the mouse's location. If inside the emacs window, nothing works, if on the edge of the window or in your bar, everything works perfectly. Now, why I have absolutely no clue. 

I initially figured this out by checking the source and finding the variable "eaf-wm-focus-fix-wms". If given a value of your current WM, it puts the mouse on the edge of the window and everything works perfectly... Until you move the mouse back into your Emacs buffer. I then tried moving the mouse outside the window again and to my surprise everything worked.

Since basically all twm users (cause I assume the issue is with these kind of window managers) have a bar in their setup, this isn't a bad workaround. I am not sure if this troubleshooting can help you figure out what the issue is, but in a keyboard driven application such as Emacs, using a keyboard driven window manager, the mouse tends to be trivial for all but a few tasks so I honestly don't mind it. 

If you don't find a solution for it, I would recommend mentioning this somewhere (either the wiki or the initial README) as a lot of  Emacs users do use tiling wms and this could be a dealbreaker for them. 

Thanks for the awesome package, and happy to help you guys, if you do find the underlying problem and solve it I would appreciate a message either in this issue thread (as I am emailed when someone replies to it)  or in reddit to u/AuroraDraco. But even if you don't, its all good, this is a decent workaround and I can probably live by it.

**Comment by MatthewZMD** [comment]
Good to hear that you found the workaround. What is your value you put in `eaf-wm-focus-fix-wms`? I'll add it to the list.

**Comment by manateelazycat** [comment]
I guess some clue like this https://github.com/manateelazycat/emacs-application-framework/commit/2e1e5f6c9574617f71e0d1c53f0c6b00105b9d18

I will figure out why EAF not works with some WM in future

**Comment by AuroraDragoon** [comment]
> Good to hear that you found the workaround. What is your value you put in `eaf-wm-focus-fix-wms`? I'll add it to the list.

Oh, forgot to mention it. Its value was "i3" (which also worked for i3, checked it as I also have i3 on my system) and I changed it to "qtile". I assume its the same for all tiling window managers.

**Comment by manateelazycat** [comment]
> > Good to hear that you found the workaround. What is your value you put in `eaf-wm-focus-fix-wms`? I'll add it to the list.
> 
> Oh, forgot to mention it. Its value was "i3" (which also worked for i3, checked it as I also have i3 on my system) and I changed it to "qtile". I assume its the same for all tiling window managers.

works now?

**Comment by AuroraDragoon** [comment]
As long as the mouse is on my bar, or on the edge of the window things will work perfectly. What that variable does is when launching the app sets the mouse on the borded of the window so if you dont move the mouse at all it will never break. But even if it does, you fix it by moving the mouse back on the bar

**Comment by manateelazycat** [comment]
I post newest patch: https://github.com/manateelazycat/emacs-application-framework/commit/95e1de99ba2fe3ae6074f857094466d77f477b2b

I found the following law happend in KDE, i3 and qtile:
1. If the mouse is in the EAF window area, then switch back to Emacs, Emacs cannot get the input focus. (Cause by QEvent.ShortcutOverride)
2. If the mouse is out of EAF window area, then switch back to Emacs, Emacs can get the input focus.

So newest patch fix focus by below logic:
1. Call elisp function eaf-move-mouse-to-frame-bottom when switch back to Emacs. (Test with QTile)
2. Or use wmctrl activate on Emacs window after Alt + Tab operation. (Test with KDE)

I have test QTile, can you guys help me confirm this fix?
Thanks!

**Comment by Aeres-u99** [comment]
@manateelazycat is there any way I can test this out on my machine without reinstalling? I am using i3 at the moment and having exact same issue. Apparently inputting the same key twice sort of does the trick, and also I did try to remap all of the non `C-` or `M-` keys to nill but that didnt seem to work. 
`(eaf-bind-key insert_or_select_left_tab "nil" eaf-browser-keybinding)`

**Comment by MatthewZMD** [comment]
@Aeres-u99 are you experiencing this issue on the latest EAF's commit?

**Comment by Aeres-u99** [comment]
Yes, I can see the mouse cursor moving in and out :P but it doesnt seems to work. I have to press same key twice to input in M-x buffer

**Comment by manateelazycat** [comment]
> Yes, I can see the mouse cursor moving in and out :P but it doesnt seems to work. I have to press same key twice to input in M-x buffer

i3 should works if mouse cursor moving when you press key in EAF buffer.
Because I have test it.

I suggest you create new user, then test standard i3 config with EAF.

**Comment by Aeres-u99** [comment]
I dont feel i3 config is interfering with it in anyway, but I will certainly give that a try as well
http://imgur.com/a/JjRdXSJ

Here is the video trying to repliacte the behaviour. I had tried remapping all the Non control and non meta keys to nil but that didn't seem to work out well.

**Comment by manateelazycat** [comment]
> I dont feel i3 config is interfering with it in anyway, but I will certainly give that a try as well
> http://imgur.com/a/JjRdXSJ
> 
> Here is the video trying to repliacte the behaviour. I had tried remapping all the Non control and non meta keys to nil but that didn't seem to work out well. @manateelazycat
> EDIT: tagged!

I watch your video, it looks you customize i3 lots.

Can you try new linux user with standard i3 config? Then you don't need reinstall your system, just delete new user home directory after test.

I'm not i3 user and expert, I just test i3 default config.

**Comment by Aeres-u99** [comment]
Here, just moved the default config away and did it with base config of i3, the user is same though.
https://imgur.com/a/ebImoHl @manateelazycat

**Comment by manateelazycat** [comment]
> Here, just moved the default config away and did it with base config of i3, the user is same though.
> https://imgur.com/a/ebImoHl @manateelazycat

You mean, EAF is work, but your minibuffer-plugin is broken?

**Comment by Aeres-u99** [comment]
@manateelazycat could that really be? let me try and disable that and see it again

**Comment by manateelazycat** [comment]
> @manateelazycat could that really be? let me try and disable that and see it again

Can you test standard i3 with "emacs -Q" ?

Just test EAF with standard i3 is compare solution, exclude the impact of EMACS plug-ins and additional I3 configuration.

**Comment by Aeres-u99** [comment]
hi, @manateelazycat I tried all night yesterday but I couldnt do it, like how can I disable all plugins except EAF? give me a bit of guidance on that. I am new to Emacs.

**Comment by manateelazycat** [comment]
> hi, @manateelazycat I tried all night yesterday but I couldnt do it, like how can I disable all plugins except EAF? give me a bit of guidance on that. I am new to Emacs.

you can only install core depend, other plug not use， won't cause error

**Comment by MatthewZMD** [comment]
> hi, @manateelazycat I tried all night yesterday but I couldnt do it, like how can I disable all plugins except EAF? give me a bit of guidance on that. I am new to Emacs.

Only put EAF related configs in your .emacs.d/init.el

**Comment by Aeres-u99** [comment]
@manateelazycat @MatthewZMD alright, so it was minibuffer plugin that was broken for me. Thank you very much. 
Also, for record purposes if someone needs to disable everything and only test whether EAF is working or not following is the configuration for that 
```
;;(require 'package)
;;(add-to-list 'package-archives
;;             '("melpa-stable" . "https://stable.melpa.org/packages/"))
;;{{{ Set up package and use-package

(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://stable.melpa.org/packages/")))

(package-initialize)
(use-package eaf
  :load-path "~/.emacs.d/site-lisp/emacs-application-framework" ; Set to "/usr/share/emacs/site-lisp/eaf" if installed from AUR
  :custom
  (eaf-find-alternate-file-in-dired t)
  :config
  (eaf-bind-key scroll_up "C-n" eaf-pdf-viewer-keybinding)
  (eaf-bind-key scroll_down "C-p" eaf-pdf-viewer-keybinding)
  (eaf-bind-key take_photo "p" eaf-camera-keybinding))
```
