### ISSUE TITLE
Provide a global one-click installation script for EAF

### ISSUE THREAD

**Issue by aancel** [manateelazycat/emacs-application-framework#464]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would be interested in a global one-click installation script to make the installation of EAF easier

**Describe alternatives you've considered**
I've already made a script to install EAF. It uses virtualenv as I'd rather not install python dependencies in my system, but in contained environments. Here it is:
```bash
#!/bin/bash

set -eu

sudo apt-get install git nodejs aria2 libreoffice wmctrl xdotool
# Missing in Ubuntu: filebrowser-bin

# Use .emacs.d if not present
export EMACS_ROOT="$XDG_CONFIG_HOME"/emacs

if [ ! -d "$EMACS_ROOT" ]; then
    export EMACS_ROOT="$HOME"/emacs

    if [ ! -d "$EMACS_ROOT" ]; then
        echo "Could not determine the location of your Emacs config directory."
        exit 1
    fi
fi

export EAF_ROOT="$EMACS_ROOT"/eaf
mkdir -p "$EAF_ROOT"/git "$EAF_ROOT"/venv "$EAF_ROOT"/bin

if [ ! -d "$EAF_ROOT"/git/emacs-application-framework ]; then
    git clone https://github.com/manateelazycat/emacs-application-framework.git --depth=1 "$EAF_ROOT"/git/emacs-application-framework
fi

if type virtualenv &>/dev/null; then
    virtualenv "$EAF_ROOT"/venv/emacs-application-framework
else
    echo "Cannot find virtualenv. Please install it."
    exit 1
fi

source "$EAF_ROOT"/venv/emacs-application-framework/bin/activate

PIP_DEPS=(PyQt5 PyQt5-sip PyQtWebEngine qrcode feedparser dbus-python pyinotify Markdown grip qtconsole pymupdf)
if type pip &>/dev/null; then
    pip install "${PIP_DEPS[@]}"
elif type pip &>/dev/null; then
    pip3 install "${PIP_DEPS[@]}"
else
    echo "Cannot find pip. Please install it !"
    exit 1
fi

LAUNCH_SCRIPT="$EAF_ROOT"/bin/emacs-eaf.sh
echo "Creating Emacs-EAF shortcut"
{
    echo "#!/bin/bash" ;
    echo "" ;
    echo "" ;
    echo "source $EAF_ROOT/venv/emacs-application-framework/bin/activate"
    echo "emacs"
} > "$LAUNCH_SCRIPT"
chmod u+x "$LAUNCH_SCRIPT"

echo "EAF is now installed !"
echo "Remaining steps:"
echo "- Set EAF load-path to: $EAF_ROOT/git/emacs-application-framework"
echo "- Add $EAF_ROOT/bin to your PATH variable, e.g. export PATH=$EAF_ROOT/bin:\$PATH"
echo "- Launch EAF-enabled Emacs via emacs-eaf.sh"
```
It is currently working on debian-variants and I can adapt it to make it work on other Linux variants, so if you like the idea, I'd happily open a PR for it.
If you'd prefer not having such a script, no problem about it and you can close this issue :thumbsup: 

**Additional context**
None

**Comment by JuanPabloMF** [comment]
+1 for this (ubuntu user).

Also had problems with dbus-python install. Is it a deprecated package?

**Comment by JuanPabloMF** [comment]
> +1 for this (ubuntu user).
> 
> Also had problems with dbus-python install. Is it a deprecated package?

This is fixed with:

```
sudo apt install libglib2.0-dev libdbus-1-3 libdbus-1-dev
```

Might be interesting to add to aancel script?

**Comment by Aaronzinhoo** [comment]
Was also trying to figure out how to make this work on Ubuntu! This really is a game changer. I suggest to do this in a previous issue I raised, but I'm glad someone beat me to the punch 😄

**Comment by aancel** [comment]
I'm glad that this proposition finds an echo in the community :smile:    
I think that such a script could ease even further the adoption of EAF !

Regarding your comments @JuanPabloMF @Aaronzinhoo, I'll be making sure that everything works if I open a PR !
I'm just trying to assess if this is something the authors would like to have for now.

P.S. : An additional thing that could be done is generating an user .desktop entry for the eaf-enabled version of Emacs to make it easier to launch.

**Comment by Aaronzinhoo** [comment]
@aancel I believe that is the right way to go. Unfortunately I tried to use the script and am facing [#245](https://github.com/manateelazycat/emacs-application-framework/issues/245) issue. Maybe WSL2 Ubuntu just is not made to have EAF and I  should switch to Arch on wsl. =(

**Comment by MatthewZMD** [comment]
@aancel This is a great idea! Since you're already working on it, I'll leave the task to you :)

Two suggestions:
1. We could make it into an emacs command similar to how lsp-mode prompts to automatically install lsp servers.
2. The script should be platform independent, it's alright to support only ubuntu's apt-install and arch's yay/pacman for now, but it should be taken into account when designing the script.

**Comment by aancel** [comment]
@Aaronzinhoo Hum that is annoying, did you try with another version of pyqtwebengine maybe ? :thinking:    
I have version 5.15.2 installed and it is working fine (but on native Linux). It could also come from the Ubuntu version you are using, are you using 18.04 or 20.04 ?

@MatthewZMD Ok great, I'll open a PR once I get a more advanced version of the script.
I also think that 1. is a really good idea, but you would still have to find a way to enable the python environment within emacs (maybe with pyenv ?) or did you mean installing the packages in the system ?
Regarding 2., yes I'll try my best to do so and I'll welcome suggestion on the PR to improve that

**Comment by Aaronzinhoo** [comment]
@aancel also I think you can follow something to the way elpy is setup. [Elpy ](https://github.com/jorgenschaefer/elpy) has a backend that fetches the packages from a virtual env that is seperate from the virtual env you use for development. This sort of architecture would help a lot so you would not have to load the virtual env before opening emacs. If this is not a good solution or I am misunderstanding something here pleas enlighten me. 

Also I using Ubuntu 20.04. I will check my versions just to make sure. I do suspect versions of some packages may be a culprit. If that is the case then it would be nice to include those in the installation to ensure a reliable installation phase as well.

**Comment by manateelazycat** [comment]
I suggest script need consider release version, not just linux distrustion.
This is a very large maintenance work, because we have to consider different version of the LINUX distribution repository compatibility work.

Arch is easy because it is a scrolling linux distribution.

Ubuntu or Debian is hard to support, because each version of the software repository is completely different, LTS version is even supported more than 5 years.

I'm pre-CTO of deepin operating system, I know this mission is hard to work, because there have many bugs exist in OS repository, we need track repository change then update install script.

I personally don't support such a job, let developers caught infinite maintenance, sacrificing the health of the developers. 

Anyway, if community developers willing to maintain this script together, I am happy this script job.

**Comment by MatthewZMD** [comment]
As people mentioned in #472, I think these are needed dependencies for ubuntu as well:

> sudo apt-get install python3-pyqt5.qtwebengine python3-pyqt5.qtmultimedia

**Comment by aancel** [comment]
I've pushed a first version of a script, I'll open a PR for suggestions.

Several points I'd like to mention:
- @manateelazycat I totally agree with the points you mention and how it can be hard/unrewarding regarding maintenance, but if users are willing to contribute this could be maintainable
- I've take the decision to offload as many packages to pip, using a requirements.txt file, to reduce the number of dependencies that would need to be installed with package managers. I think that this could ease the maintenance, as we would be making sure to use compatible versions of packages
- Regarding the integration directly in elisp like other packages, I'm not sure to be confident enough with my elisp to do that, so contributions would be most welcome on this side. I've also thought that we could do this integration in two steps: First solve this issue to have a working shell script, then on another issue work on the elidp integration, what do you think about this ?

Of course, in the end, if you prefer not to integrate this code, there is no problem !

**Comment by manateelazycat** [comment]
> I've pushed a first version of a script, I'll open a PR for suggestions.
> 
> Several points I'd like to mention:
> 
> * @manateelazycat I totally agree with the points you mention and how it can be hard/unrewarding regarding maintenance, but if users are willing to contribute this could be maintainable
> * I've take the decision to offload as many packages to pip, using a requirements.txt file, to reduce the number of dependencies that would need to be installed with package managers. I think that this could ease the maintenance, as we would be making sure to use compatible versions of packages
> * Regarding the integration directly in elisp like other packages, I'm not sure to be confident enough with my elisp to do that, so contributions would be most welcome on this side. I've also thought that we could do this integration in two steps: First solve this issue to have a working shell script, then on another issue work on the elisp integration, what do you think about this ?
> 
> Of course, in the end, if you prefer not to integrate this code, there is no problem !

Thanks, looks my suggestions at https://github.com/manateelazycat/emacs-application-framework/pull/483

**Comment by JuanPabloMF** [comment]
> @aancel I believe that is the right way to go. Unfortunately I tried to use the script and am facing [#245](https://github.com/manateelazycat/emacs-application-framework/issues/245) issue. Maybe WSL2 Ubuntu just is not made to have EAF and I should switch to Arch on wsl. =(
> 
> Surprisingly, `eaf-open-demo` works and shows an image, but `eaf-open-browser` does not.

I tried for 3 months WSL2 but abandoned it (emacs would have many issues -for example not launching GUI because of unknown issue communicating with window manager- all the more when there were OS updates) and reinstalled double booting. Guess this kind of behavior might be expected also with EAF.

**Comment by manateelazycat** [comment]
done
