### ISSUE TITLE
M-x eaf-open-browser [No match]

### ISSUE THREAD

**Issue by hongyi-zhao** [manateelazycat/emacs-application-framework#465]
On Ubuntu 20.04, I compiled the latest git master version of emacs and try to use the emacs-application-framework as a web browser as following:

`$ git clone https://github.com/manateelazycat/emacs-application-framework.git ~/manateelazycat/emacs-application-framework.git`

Then I put the following settings into .emacs:
```
(use-package eaf
  :load-path "~/manateelazycat/emacs-application-framework.git" ; Set to "/usr/share/emacs/site-lisp/eaf" if installed from AUR
  :custom
  (eaf-find-alternate-file-in-dired t)
  :config
  (eaf-bind-key scroll_up "C-n" eaf-pdf-viewer-keybinding)
  (eaf-bind-key scroll_down "C-p" eaf-pdf-viewer-keybinding)
  (eaf-bind-key take_photo "p" eaf-camera-keybinding))
```
But I failed to open some URL with it as shown below:
 
`M-x eaf-open-browser <CR>`

It will complain:

`M-x eaf-open-browser [No match]`

What's wrong with me? Any hints will be highly appreciated.

Regards,
HY

**Comment by MatthewZMD** [comment]
You have to set it to the correct load-path "~/manateelazycat/emacs-application-framework.git". Then you need to eval the eaf.el buffer, or restart emacs, and verify by `C-h f` that you have `eaf-open-browser` function.

**Comment by hongyi-zhao** [comment]
I'm a rather newbie of the great emcas editor. Based on the notes supplied by you [here](https://github.com/MatthewZMD/.emacs.d/blob/master/README.md#eaf), I retried with the following steps:

1. Clone the emacs-application-framework package into the following location:

```
git clone https://github.com/manateelazycat/emacs-application-framework.git ~/.emacs.d/site-elisp/emacs-application-framework.git
```

2. Use the following settings in my .emacs file adapted from yours:

```
(use-package eaf
  :load-path (lambda () (expand-file-name "site-elisp/emacs-application-framework.git" user-emacs-directory))
  :if eaf-env-p
  :custom
  (eaf-find-alternate-file-in-dired t)
  (browse-url-browser-function 'eaf-open-browser) ;; Make EAF Browser my default browser
  (eaf-browser-continue-where-left-off t)
  :config
  (require 'eaf-org)
  (defalias 'browse-web #'eaf-open-browser)
  (eaf-setq eaf-browser-default-zoom "1.25")
  (eaf-setq eaf-browser-dark-mode "false")
  (eaf-setq eaf-browser-enable-adblocker "true")
  (eaf-setq eaf-pdf-dark-mode "false")
  (eaf-setq eaf-browser-enable-autofill "true")
  ;; I already bind "RET", "<mouse-2>", "^" to `dired-find-alternate-file' in `init-dired.el'.
  ;; Comment this line out of you don't want to use EAF to open available files in dired.
  ;; (global-set-key [remap dired-find-alternate-file] #'eaf-file-open-in-dired)
  (eaf-bind-key nil "M-q" eaf-browser-keybinding)
  (eaf-bind-key open_link "C-M-s" eaf-browser-keybinding)
  (eaf-bind-key clear_cookies "C-M-q" eaf-browser-keybinding)
  (eaf-bind-key insert_or_recover_prev_close_page "X" eaf-browser-keybinding)
  (eaf-bind-key scroll_up "RET" eaf-pdf-viewer-keybinding)
  (eaf-bind-key scroll_down_page "DEL" eaf-pdf-viewer-keybinding)
  (eaf-bind-key scroll_down_page "u" eaf-pdf-viewer-keybinding)
  (eaf-bind-key scroll_up_page "d" eaf-pdf-viewer-keybinding)
  (eaf-bind-key scroll_to_end "M->" eaf-pdf-viewer-keybinding)
  (eaf-bind-key scroll_to_begin "M-<" eaf-pdf-viewer-keybinding)
  (eaf-bind-key quit-window "q" eaf-pdf-viewer-keybinding)
  (eaf-bind-key zoom_in "C-=" eaf-pdf-viewer-keybinding)
  (eaf-bind-key zoom_out "C--" eaf-pdf-viewer-keybinding)
  (eaf-bind-key take_photo "p" eaf-camera-keybinding)
  (eaf-bind-key eaf-send-key-sequence "M-]" eaf-terminal-keybinding)
  )
```
When I try to start emacs, I meet the following error:

```
Warning (initialization): An error occurred while loading ‘/home/werner/.emacs’:

Symbol's value as variable is void: eaf-env-p
```
What's wrong with me and how to fix it?

Regards,
HY

**Comment by MatthewZMD** [comment]
Remove the line `:if eaf-env-p`

Also, I suggest you put EAF in the `.emacs.d` directory instead of here:`"~/elisp/manateelazycat/emacs-application-framework.git"`

**Comment by hongyi-zhao** [comment]
> Remove the line `:if eaf-env-p`

I'll try with the latest self compiled git master version and feedback if necessary.
> 
> Also, I suggest you put EAF in the `.emacs.d` directory instead of here:`"~/elisp/manateelazycat/emacs-application-framework.git"`

The schema I used above is based on the suggestion [here](https://emacs.stackexchange.com/questions/31994/where-would-be-the-most-appropriate-directory-to-put-my-own-emacs-lisp-files-in) which told the following:

```
If you plan to have small config files under source control, then having them within your .emacs.d is not a great idea because .emacs.d is already the spacemacs repository, and you wouldn't want to mess up the spacemacs organization with random files.

As an example, I have a ~/Elisp directory where I keep my configuration files. This way I can have a repo with my personal config and have only a single directory that I have to add to the load path. When I grab some config files from other people, or repositories, I usually keep them in their own git repo (from where I cloned them), and add symlinks to my ~/Elisp dir.
```
To be frank, I still can't figure out why you prefer .emacs.d directory over other locations. Could you please give me some more hints? 

Regards,
HY

**Comment by MatthewZMD** [comment]
Are you using spacemacs? If not, you don't need to worry about it, it's just a convention. Look at how it's laid out in M-EMACS.

**Comment by hongyi-zhao** [comment]
Thanks a lot for your notes. I'll try with your M-EMACS.

**Comment by hongyi-zhao** [comment]
> Remove the line `:if eaf-env-p`

I've commented the above line my init.el file, but still failed with the following error:

`Error (use-package): eaf/:catch: Cannot open load file: No such file or directory, s Disable showing Disable logging`

**Comment by manateelazycat** [comment]
I have answered on https://github.com/manateelazycat/emacs-application-framework/issues/466

Please try solution in issue #466, close this issue.

And "emacs -Q" will be nice for test, exclude your personal configuration impact.
