### ISSUE TITLE
Lose emacs focus when using with EXWM

### ISSUE THREAD

**Issue by vuquangtam** [manateelazycat/emacs-application-framework#47]
I use emacs25 in another xserver (run in Xephyr) with [exwn](https://github.com/ch11ng/exwm). When i try opening eaf, everytime i focus on eaf window, i lose my emacs focus (can't type on emacs).

**Comment by manateelazycat** [comment]
EAF use complicated technology that depend on general desktop environment, such as, KDE/DDE/Unity/Gnome2

EAF won't work if you run it on any Tile WM or other light DE (LXDE, Xfce, OpenBox etc)

**Comment by markgdawson** [comment]
Is it possible to have an idea of technology you're referring to? I'd be interested in trying to make this work if it was feasible.

**Comment by markgdawson** [comment]
A quick test seems to fix the issue I was seeing. Would it be worth me sending a PR to add EXWM to the `eaf-wm-focus-fix-wms` list?
