### ISSUE TITLE
Socks5-hostname protocol support in emacs-application-framework.

### ISSUE THREAD

**Issue by hongyi-zhao** [manateelazycat/emacs-application-framework#470]
I tried with the following settings in ~/.emacs.d/init.el:
```
(setq eaf-proxy-type "socks5h")
(setq eaf-proxy-host "127.0.0.1")
(setq eaf-proxy-port "18888")
```
It seems EAF currently doesn't support socks5-hostname protocol, i.e., use the specified SOCKS5 proxy and let the proxy resolve the host name. Could you please add this feature into EAF?

Regards,
HY

**Comment by manateelazycat** [comment]
No, Qt just support http, https and socks5.

You can use privoxy for protocol forwarding
