### ISSUE TITLE
The input method candidate box can't follow the cursor.

### ISSUE THREAD

**Issue by hongyi-zhao** [manateelazycat/emacs-application-framework#471]
When I use the eaf-open-browser command shipped in [EAF](https://github.com/manateelazycat/emacs-application-framework) to surfing the website, I find that the input method candidate box activated by [emacs-rime](https://github.com/DogLooksGood/emacs-rime) can't follow the cursor. See the following screenshot for detailed info:

![image](https://user-images.githubusercontent.com/11155854/102007158-907a7a80-3d61-11eb-8de5-26cda5346ec0.png)

As you can see, the position of the input method candidate box is fixed in the upper left corner of the screen instead of following the cursor. Any hints for solving this problem?

Regards,
HY

**Comment by manateelazycat** [comment]
Because PyQT widget not accept input directly, all qt event is fake event by Emacs event string.

So fake qt event don't know input coordindate.

I don't think this issue can fix in short time.

We most use M-e with emacs-rime in Emacs and EAF.

**Comment by hongyi-zhao** [comment]
> We most use M-e with emacs-rime in Emacs and EAF.

Still not so clear on your meaning. What's the relationship between move to end of sentence, i.e.,  M-e, and using emacs-rime in Emacs and EAF?

**Comment by manateelazycat** [comment]
> > We most use M-e with emacs-rime in Emacs and EAF.
> 
> Still not so clear on your meaning. What's the relationship between movement to end of sentence, i.e., M-e, and using emacs-rime in Emacs and EAF?

try press alt + e in EAF browser ;)

**Comment by hongyi-zhao** [comment]
> try press alt + e in EAF browser ;)

But this will only let me input the Chinese characters into the bottom buffer instead of the browser's search box. See the following screenshot for more info of my case:

![image](https://user-images.githubusercontent.com/11155854/102014717-68573f80-3d92-11eb-97e4-1923ba6c2365.png)

**Comment by manateelazycat** [comment]
> > try press alt + e in EAF browser ;)
> 
> But this will only let me input the Chinese characters at the bottom buffer instead of the browser's search box. See the following screenshot for more info of my case:
> 
> ![image](https://user-images.githubusercontent.com/11155854/102014717-68573f80-3d92-11eb-97e4-1923ba6c2365.png)

yes，this is best solution now

this issue i know when i created this project, not easy to fix

**Comment by manateelazycat** [comment]
No idea how to fix now, I think this problem cannot be repaired in the short term.

Close issue.

**Comment by QiangF** [comment]
感觉输入法打开的时候不应该把按键截获，fcitx对popup位置有很好的支持。
能不能用lua作为沟通fcitx和emacs的桥梁，用rpc之类的，fcitx那边用lua plugin, 用来通知emacs选择是否截获按键
https://www.aloxaf.com/2020/09/fcitx5_plugin/
https://github.com/syohex/emacs-lua
https://github.com/stockrt/luarpc

**Comment by manateelazycat** [comment]
> 感觉输入法打开的时候不应该把按键截获，fcitx对popup位置有很好的支持。
> 能不能用lua作为沟通fcitx和emacs的桥梁，用rpc之类的，fcitx那边用lua plugin, 用来通知emacs选择是否截获按键
> https://www.aloxaf.com/2020/09/fcitx5_plugin/
> https://github.com/syohex/emacs-lua
> https://github.com/stockrt/luarpc

eaf不管理按键，emacs就会失去控制，引入输入法就把事情搞复杂了，还有好多输入法呢。

就用M-e就够了
