### ISSUE TITLE
save screenshot overwrite others in mindmap

### ISSUE THREAD

**Issue by mackong** [manateelazycat/emacs-application-framework#481]
**Describe the bug**
when there are more than one mindmap buffer opened, type 1 to save screenshot in one buffer, the result image png will overwrite others.

**To Reproduce**
Open two mindmap buffers, type 1 in one buffer, see the result image png.

**Expected behavior**
Don't overwrite with each other.

**Versions:**
OS: Manjaro Linux, Gnome 3.36.6
QT: 5.15.0-5
PyQT: 5.15.1
Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-09-03

**Screenshots**

**Additional context**
With some investigation, I found the following
```
        self.profile.defaultProfile().downloadRequested.connect(self.handle_download_request)
```
in core/browser.py:703 may be the issue.

**Comment by manateelazycat** [comment]
I will fix this issue in this weekend, busy now.

Thanks for report.

**Comment by MatthewZMD** [comment]
Done

**Comment by mackong** [comment]
@MatthewZMD 我测试了下，问题还是存在的。
我用中文重新描述下问题，英语太渣。。。

同时打开两个mindmap文件， 称为a和b。
此时，在a窗口按下按键1,得到a.png文件，然后在b窗口按下按键1,得到b.png.
查看这两个png文件，会发现内容一样，都是b那个mindmap的内容。

排查发现，可能是 core/browser.py:703
```
self.profile.defaultProfile().downloadRequested.connect(self.handle_download_request)
```
这句代码导致的。两个窗口共用同一个profile, 保存图片的时候，触发的下载事件两个窗口都进行了处理。

**Comment by MatthewZMD** [comment]
懂了，我理解错了，有空修一修
