### ISSUE TITLE
EAF browser doesn't support google's reCAPTCHA checkbox widget

### ISSUE THREAD

**Issue by duzaichuan** [manateelazycat/emacs-application-framework#484]
I am using google by v2ray. When I try to open a youtube video, I often come across the problem described in the title. Can eaf add support to google's human-or-robot check?

**Comment by manateelazycat** [comment]
No idea now, I guess Google will consider other browser are rebot except Chrome, Firefox, IE

**Comment by duzaichuan** [comment]
I guss the check is associated with the proxy I use. In chrome I also need to take the robot check sometimes, but of course chrome supports it. So I can click on the box and go on youtubing.

**Comment by manateelazycat** [comment]
I know reason, cause by default user agent.

Current EAF user agent use Firefox's value, we can login Gmail, but reCAPTCHA not working.

Change user agent to Chrome's user agent, EAF can use reCAPTCHA, but google don't allow EAF login gmail if we switch to Chrome's user agent.

Google's strategy is very confused.

**Comment by manateelazycat** [comment]
I don't know how to fix this issue, please reopen this issue if someone figure out.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/emacs-application-framework/commit/07ab655c61c84d51756b111635909a3db65367c0 patch has fix this issue after upgrade firefox version in user agent.

Now EAF browser can pass test of https://patrickhlauke.github.io/recaptcha/
