### ISSUE TITLE
Caret mode does not work

### ISSUE THREAD

**Issue by loyalpartner** [manateelazycat/emacs-application-framework#488]
js console output
```
VM235:1 Uncaught ReferenceError: CaretBrowsing is not defined
```

https://github.com/manateelazycat/emacs-application-framework/blob/master/core/js/caret_browsing.js#L538

CaretBrowsing is not global variable, so it can't access.

![caret_not_work](https://user-images.githubusercontent.com/1442249/103215392-2e6b6900-494e-11eb-93aa-50f155cadfdb.gif)

**Comment by manateelazycat** [comment]
I found this issue recently, I guess some patch broken it.
