### ISSUE TITLE
The new commit "3a30d10" changed `default-directory' permantally.

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#494]
When I open an file link in Org buffer, then the `default-directory' is changed to the file's path.
It affacted a lot of things. Like `org-attach`, `org-store-link` etc.

**Comment by MatthewZMD** [comment]
Try the latest patch

**Comment by stardiviner** [comment]
还是不对。原有buffer的 `default-directory` 还是被修改了。原来buffer的 `default-directory` 不应该被修改。
错误是这样的

1. 我打开一个Org文件 `/tmp/kk.org` ，里面有一个链接 `[[file:anime/beauty/girl.png]]`.
2. 按下 `[C-c C-o]` 之后，链接被EAF打开。第一次能正确打开显示。
3. 然后我按 `[x]` 关闭EAF buffer
4. 再按 `[C-c C-o]` 打开链接，打不开了，报错 `user-error: [EAF] File /tmp/anime/beauty/anime/beauty/girl.png does not exist` 可以看到，由于EAF修改了 `default-directory` 导致org打开相对路径链接变成了一个错误的路径。应该是最近的 `find-file` advice 导致的。（因为原本我打开链接不是eaf,而是emacs image mode.）

**Comment by MatthewZMD** [comment]
现在再试试？我没测你这个情况

**Comment by stardiviner** [comment]
测试ok, 感谢 @MatthewZMD ! 哈哈哈
