### ISSUE TITLE
EAF too intrusive when opening files using find-file/dired

### ISSUE THREAD

**Issue by czikus** [manateelazycat/emacs-application-framework#495]
**Is your feature request related to a problem? Please describe.**
I find EAF too intrusive when it comes to opening files of certain types. I like using EAF to open a browser inside Emacs, but prefer PDF Tools for viewing PDFs. Yet, EAF advices find-file and prevents PDFs from being opened using PDF View. This is not configurable. One can remove .pdf from a list of supported files (`eaf-pdf-extension-list`), but that is not what I am looking for. I would still like the option to use eaf/open for PDFs explicitly, and I don't really want EAF to advice my find-file if that is not necessary.

**Describe the solution you'd like**
Add a configuration option that when set to nil will instruct EAF to not advise find-file/dired.

**Comment by MatthewZMD** [comment]
Do you still need this to be fixed? As its very simple, I can do it.

**Comment by czikus** [comment]
Sure, thanks, although I found an easy workaround, so it's not really high priority.

**Comment by MatthewZMD** [comment]
Could you share your workaround here? Other people might be interested as well.

**Comment by manateelazycat** [comment]
> Could you share your workaround here? Other people might be interested as well.

I think better way is build an option, default is t, we judge the option in advisor, if option is non-nil, open file with EAF, if option is nil, nothing to do.

**Comment by MatthewZMD** [comment]
> > Could you share your workaround here? Other people might be interested as well.
> 
> I think better way is build an option, default is t, we judge the option in advisor, if option is non-nil, open file with EAF, if option is nil, nothing to do.

I think a whitelist is better, the user might want to use some applications with EAF but not the other.

**Comment by MatthewZMD** [comment]
With the latest commit, you can now whitelist file extensions like this:

```
(setq eaf-find-file-ext-whitelist '("pdf"))
```

**Comment by czikus** [comment]
Looks great. Thanks! My only comment would be that it seems to me that blacklist might be a more appropriate term than whitelist here, since it is a list of extensions to exclude.

**Comment by MatthewZMD** [comment]
> Looks great. Thanks! My only comment would be that it seems to me that blacklist might be a more appropriate term than whitelist here, since it is a list of extensions to exclude.

Done!
