### ISSUE TITLE
Unable to unbind `,` from eaf-mode-map

### ISSUE THREAD

**Issue by dalanicolai** [manateelazycat/emacs-application-framework#498]
I am not sure if this is more a bug-report or a feature request, I will state the problem:

As I am trying to create an `eaf` layer for Spacemacs, I would like to use the [leader-key-for-major mode](https://develop.spacemacs.org/doc/DOCUMENTATION.html#major-mode-leader-key), which by default is set to the `,` key.

I am certainly no emacs keymap expert, but I find that Spacemacs creates a spacemacs-<major-mode>-map for this.
I can create keybindings withing this map using the function [spacemacs/set-leader-keys-for-major-mode](https://develop.spacemacs.org/doc/DOCUMENTATION.html#binding-keys) function, which works correctly. However, I am unable to use the key because I am unable to unbind the `,` key (which is bound to `eaf-send-key`).

As described [in the wiki](https://github.com/manateelazycat/emacs-application-framework/wiki/Keybindings), I have tried
`(eaf-bind-key nil "," eaf-browser-keybinding)`
and
`(define-key eaf-mode-map* (kbd ",") nil)`,
but the key does not unbind.

Could you advice me how to achieve what I want, or otherwise could you add the `leader-keys-for-major-mode` option to `eaf-evil.el`?

Of course let me know if you need more info...

**Comment by manateelazycat** [comment]
Please read the code of 'eaf--gen-keybinding-map' first.

If command's string include char "-", EAF will call it as elisp function.
If command is not built-in elisp function or not include char '-', EAF will call it as Python function through DBus.

So I think you can build your own elisp function "eaf-leader-key-or-send-key", then bind key "," with eaf-leader-key-or-send-key, then handle leader key logic in it.

**Comment by dalanicolai** [comment]
Ah great thanks! I guess with this info I can figure things out...

**Comment by manateelazycat** [comment]
Please re-open issue if still have problem here.
