### ISSUE TITLE
当窗口焦点位于eaf buffer时，emacs无法用f11切换到全屏

### ISSUE THREAD

**Issue by cireu** [manateelazycat/emacs-application-framework#51]
如题所示，如果手动切换焦点到minibuffer，则可以按f11切换到全屏。
此外，如果Emacs已经全屏，反而可以用f11切换回窗口状态。

## 复现步骤
1. `emacs -Q`
2. 添加`load-path`
3. 确保Emacs是窗口状态
4. `M-x eaf-open` 随便打开什么东西
5. 尝试用`f11`切换，此时应当切换失败 (Emacs窗口闪烁一下但是没有报错, 也没有切换成功)
6. 把焦点切换到非eaf buffer，进入全屏，焦点回到eaf buffer
7. `f11`切换，此时应当成功

## 相关信息
OS: Archlinux
Qt library version: `qt5-base` 5.12.0-2 `qt5-webengine` 5.12.0-2 `qt5-x11extras` 5.12.0-2
PyQt bindings version: `PyQt5` 5.11.3 `PyQt5-sip` 4.19.13 `python-xlib` 0.23
Emacs version: 26.1
EAF version: commint [d9681a9](https://github.com/manateelazycat/emacs-application-framework/commit/d9681a930f933d1777bbe341be6e6557bde9a204)
Xorg: `xorg-server` 1.20.3-1

**Comment by manateelazycat** [comment]
最近都在用Mac啊, Mac上跑不了我的EAF

我下周有时间看看哈, 现在手边没有Linux

**Comment by manateelazycat** [comment]
可能要到年后了, 我现在手边没有Linux, 没法测试和修复.
Mac跑不起 EAF

**Comment by cireu** [comment]
给老王拜个晚年，祝身体健康，心想事成！

不知可否有思路？

**Comment by MatthewZMD** [comment]
我无法重现，在我这里f11是正常的，这现在还有问题吗

**Comment by cireu** [comment]
现在没怎么用eaf，抽空看一下

**Comment by manateelazycat** [comment]
我可以重现这个问题，我这几天有空看一下

**Comment by cireu** [comment]
老王你终于有时间玩Linux了 Happy :)

**Comment by manateelazycat** [comment]
> 老王你终于有时间玩Linux了 Happy :)

原来用Mac主要是写坑爹的小程序，现在买了一个X1，没事的时候就修一下EAF的bug，客官你久等了，哈哈哈哈

**Comment by manateelazycat** [comment]
我大概看了一下，应该是 F11 由窗口管理器调用，导致Emacs EAF Buffer临时丢掉Focus状态，导致切换全屏失效。

具体代码层面的原因还需要时间看，先放一下，我去修一下其他的Bug

**Comment by cireu** [comment]
给f11加advice？

**Comment by manateelazycat** [comment]
@cireu 火车上灵感一来，搞定了，哈哈哈哈
