### ISSUE TITLE
Basic image transformations

### ISSUE THREAD

**Issue by czikus** [manateelazycat/emacs-application-framework#510]
**Is your feature request related to a problem? Please describe.**
It would be great if the EAF image viewer was capable of basic image transformations. Specifically: rotation (left/right) and cropping (region selected using the mouse). Then, it should be possible to either reset the transformations applied and return the image to the original state or save the image (overwrite, but saving as new file could be nice too).

**Describe the solution you'd like**
Several new commands to bind in `eaf-image-viewer-keybinding`:
- `rotate_clockwise`, `rotate_counterclockwise`
- `crop`
- `reset_transformations`
- `save`

**Comment by manateelazycat** [comment]
EAF Image Viewer is base on browser, maybe we can include some image javascript library for this.

**Comment by yqu212** [comment]
[fengyuanchen/viewerjs](https://github.com/fengyuanchen/viewerjs) ?

**Comment by manateelazycat** [comment]
I search some libraries.

https://pqina.nl/doka/ looks awesome, but need buy it.
https://fengyuanchen.github.io/cropperjs/ looks nice too, and it's free.

**Comment by manateelazycat** [comment]
> **Is your feature request related to a problem? Please describe.**
> It would be great if the EAF image viewer was capable of basic image transformations. Specifically: rotation (left/right) and cropping (region selected using the mouse). Then, it should be possible to either reset the transformations applied and return the image to the original state or save the image (overwrite, but saving as new file could be nice too).
> 
> **Describe the solution you'd like**
> Several new commands to bind in `eaf-image-viewer-keybinding`:
> 
> * `rotate_clockwise`, `rotate_counterclockwise`
> * `crop`
> * `reset_transformations`
> * `save`

zoom, rotate, reset has finish in newest version with viewer.js
save need hacker send new PR.

crop is feature image editor or image painter, not should add in image viewer.
