### ISSUE TITLE
How to enter new search pattern after previous search?

### ISSUE THREAD

**Issue by dalanicolai** [manateelazycat/emacs-application-framework#512]
I could not find how to enter a new search pattern after a previous search (in the browser). When first time pressing C-s, Emacs ask to enter a search term. However after that pressing C-s again jump to the next match. So how can I enter a new search term?

**Comment by manateelazycat** [comment]
ctrl + g then ctrl + s again

**Comment by dalanicolai** [comment]
Thanks! Did you document this somewhere already?

**Comment by manateelazycat** [comment]
> Thanks! Did you document this somewhere already?

you can add it to wiki ;)
