### ISSUE TITLE
Toggle dark mode for other apps than pdf-viewer

### ISSUE THREAD

**Issue by dalanicolai** [manateelazycat/emacs-application-framework#513]
I am not sure if it is easy to make other apps than the pdf-viewer invert colors easily (via a dbus call).
So because I do prefer to have a toggle option, I have added the following function to the Spacemacs layer, that toggles dark-mode for all apps (only tested for browser and pdf-viewer, although I am aware that the last mentioned app has a better dbus version):
```
(defun eaf-toggle-dark-mode ()
  (interactive)
  (if (not (eq major-mode 'eaf-mode))
      (message "Not in eaf-mode buffer")
    (let* ((app-dark-mode
            (intern
             (format "eaf-%s-dark-mode"
                     (if (string= eaf--buffer-app-name "pdf-viewer")
                         "pdf"
                       eaf--buffer-app-name))))
           (current-state (cdr (assoc app-dark-mode eaf-var-list))))
      (if (string= current-state "true")
          (eaf-set app-dark-mode "false")
        (eaf-set app-dark-mode "true")))
    (eaf-restart-process)))
```
Of course I am happy to create another PR if you are interested...

**Comment by MatthewZMD** [comment]
Sounds about right, however do keep in mind that `eaf-*-dark-mode` has options more than just `"true"` or `"false"` (see [Wiki](https://github.com/manateelazycat/emacs-application-framework/wiki/Customization#dark-mode))

**Comment by dalanicolai** [comment]
Ah yes, I was aware of that, but I forgot about it while writing this simple toggle function. Thanks for reminding me. So I will look if I can find out myself how to get the current "dark-state" of an app. Otherwise come back here to ask you...

**Comment by dalanicolai** [comment]
I see now that you have already enabled the github discussions feature. Maybe you could mention it when someone is trying to create an issue. Then I would have known about it before creating my last issues...

**Comment by MatthewZMD** [comment]
> I see now that you have already enabled the github discussions feature. Maybe you could mention it when someone is trying to create an issue. Then I would have known about it before creating my last issues...

There is already two templates for the issues, one is bug report, the other is feature request. I don't know how else to remind people to use the Discussions except adding a line directly into the template... I don't know if it would work very nice.

Anyways, the Discussions is a beta feature from Github, it's totally alright to forget to use it
