### ISSUE TITLE
Toggle dark-mode command for other apps than pdf-viewer

### ISSUE THREAD

**Issue by dalanicolai** [manateelazycat/emacs-application-framework#514]
I am not sure if it is easy to make other apps than the pdf-viewer invert colors easily (via a dbus call).
So because I do prefer to have a toggle option for the Spacemacs layer, I have added the following command that should toggle dark-mode for all apps but is only tested for browser and pdf-viewer (I am aware of the better dbus version for the pdf-viewer):
```
(defun eaf-toggle-dark-mode ()
  (interactive)
  (if (not (eq major-mode 'eaf-mode))
      (message "Not in eaf-mode buffer")
    (let* ((app-dark-mode
            (intern
             (format "eaf-%s-dark-mode"
                     (if (string= eaf--buffer-app-name "pdf-viewer")
                         "pdf"
                       eaf--buffer-app-name))))
           (current-state (cdr (assoc app-dark-mode eaf-var-list))))
      (if (string= current-state "true")
          (eaf-set app-dark-mode "false")
        (eaf-set app-dark-mode "true")))
    (eaf-restart-process)))
```
Of course I am happy to create another PR if you are interested...

**Comment by manateelazycat** [comment]
duplicate issue

**Comment by dalanicolai** [comment]
Ah that's interesting. When I submitted the first issue, I got directed to a `page not found` error. I did not notice that is anyway was submitted correctly
