### ISSUE TITLE
Variable to toggle UnknownUrlSchemePolicy in QtWebEngine

### ISSUE THREAD

**Issue by usaoc** [manateelazycat/emacs-application-framework#515]
**Is your feature request related to a problem? Please describe.**
[Joining a Zoom meeting](https://zoom.us/test) from EAF browser is impossible due to [a limitation in QtWebEngine](https://bugreports.qt.io/browse/QTBUG-84108).

**Describe the solution you'd like**
Provide a variable in EAF Python side to toggle [UnknownUrlSchemePolicy](https://doc.qt.io/qt-5/qwebenginesettings.html). Qutebrowser provides a similar workaround.

**Describe alternatives you've considered**
Wait for QtWebEngine bug fix.

**Comment by manateelazycat** [comment]
Can you show me qutebrowser's code?

Mabye we can add some patch similar qutebrowser.

Thanks

**Comment by usaoc** [comment]
No problem. Here are the [related issue](https://github.com/qutebrowser/qutebrowser/issues/5693) and [code snippet](https://github.com/qutebrowser/qutebrowser/blob/c628e1430c1d51888df6b825121444334d1b15ec/qutebrowser/browser/webengine/webenginesettings.py#L178-L185).

**Comment by manateelazycat** [comment]
Done by patch https://github.com/manateelazycat/emacs-application-framework/commit/fce341d7bf3ee94e38265ace2f2c21f875b9e29a
