### ISSUE TITLE
After install get libqt5 error

### ISSUE THREAD

**Issue by Aaronzinhoo** [manateelazycat/emacs-application-framework#517]
**Describe the bug**
```
ImportError: libQt5QmlModels.so.5: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/aaron-gonzales/.config/emacs/straight/build/eaf/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed # noqa
  File "/home/aaron-gonzales/.config/emacs/straight/repos/emacs-application-framework/app/browser/buffer.py", line 24, in <module>
    from core.browser import BrowserBuffer
  File "/home/aaron-gonzales/.config/emacs/straight/repos/emacs-application-framework/core/browser.py", line 26, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage, QWebEngineScript, QWebEngineContextMenuData, QWebEngineProfile, QWebEngineSettings
ImportError: libQt5QmlModels.so.5: cannot open shared object file: No such file or directory
```

**To Reproduce**
Installed using the eaf install script using Ubuntu 20.04.

**Versions (please complete the following info):**
 - Distro and DE/WM: Ubuntu-20.04
 - Versions of Dependencies: 5.15
 - M-x emacs-version: 26.1

**Additional context**
I tried finding the necessary package to install the dependency but it seems that QmlModels is not installable on ubuntu20.04. Is there some way around this package?

**Comment by manateelazycat** [comment]
You can try command ```sudo apt-file search libQt5QmlModels.so.5``` to figure out which package is miss.

Then install miss package and try again.

**Comment by Aaronzinhoo** [comment]
@manateelazycat  That is a really handy package but unfortunately it returns nothing in this case for me.
```
sudo apt-file find libQt5QmlModels.so.5
```

Have any other ideas? I did a lot research through ubuntu fossa packages before I decided to come here so I am hoping I am just missing something.

**Comment by manateelazycat** [comment]
> @manateelazycat That is a really handy package but unfortunately it returns nothing in this case for me.
> 
> ```
> sudo apt-file find libQt5QmlModels.so.5
> ```
> 
> Have any other ideas? I did a lot research through ubuntu fossa packages before I decided to come here so I am hoping I am just missing something.
> 
> This file is actually included in the qt-create installation from source but that does not really help the situation.

apt-file search not apt-file find

**Comment by Aaronzinhoo** [comment]
Sorry about that I did both actually I just forgot to post the other. They both resulted in empty responses.
```
❯ sudo apt-file search libQt5QmlModels.so.5
```

**Comment by manateelazycat** [comment]
> Sorry about that I did both actually I just forgot to post the other. They both resulted in empty responses.
> 
> ```
> ❯ sudo apt-file search libQt5QmlModels.so.5
> ```

did you do apt-file update before do apt-file search?

**Comment by Aaronzinhoo** [comment]
Yea I did. It requires you to do it before running the search command

**Comment by manateelazycat** [comment]
> Yea I did. It requires you to do it before running the search command

I am not use ubuntu, have not idea, sorry

**Comment by Aaronzinhoo** [comment]
That is fine, thanks for the help. I think this would work in Ubuntu 18.04 & 20.10 as both have the necessary packages available to install. I guess I should be really looking into Arch Linux soon.

**Comment by Aaronzinhoo** [comment]
@manateelazycat may I ask your qt5 Version that you have installed?

**Comment by manateelazycat** [comment]
> @manateelazycat may I ask your qt5 Version that you have installed?

I use arch and pyqt 5.15

**Comment by manateelazycat** [comment]
EAF just use pyqt's widget, not use QML, I don't know why Ubuntu will report this problem.

I guess something wrong with pyqt package in Ubuntu.

Welecome to send PR, I don't use Ubuntu, can not help this.
