### ISSUE TITLE
Support selecting text in epub

### ISSUE THREAD

**Issue by duzaichuan** [manateelazycat/emacs-application-framework#518]
I love reading epub books using eaf. Nov.el is nice, but does not render some math formula very well.

The only feature that I miss is selecting and copy text when reading ebooks. Any idea to enable this in eaf?

**Comment by manateelazycat** [comment]
@luhuaei Any idea?

**Comment by luhuaei** [comment]
> @luhuaei Any idea?

pymupdf don't support epub text selectting [this issues](https://github.com/pymupdf/PyMuPDF/issues/628) ;(

but can use browser wrap an epub viewer or use other reader base python.

**Comment by yqu212** [comment]
似乎可以用epub.js重新实现一个单独的epub阅读器。刚才看了一下，

**Comment by manateelazycat** [comment]
reopen this issue if someone has idea.
