### ISSUE TITLE
PDF Viewer: function to get the ID/Name of an annotation and jump to an annotation based on ID/Name

### ISSUE THREAD

**Issue by fuxialexander** [manateelazycat/emacs-application-framework#521]
**Is your feature request related to a problem? Please describe.**
I'm considering making `org-pdftools` and `org-noter-pdftools` compatible with the EAF PDF viewer, however, a few API is still missing. Namely: the functions to:
- retrieve the list of annotations on a page
- get the ID of a specific annotation
- jump to and highlight a specific annotation based on its ID
- ...

**Describe the solution you'd like**
PyMuPDF actually has support for all these. But they need to be used by EAF to be used from Emacs. Just like what has been done for the function to add an annotation.

**Comment by manateelazycat** [comment]
@luhuaei Above is right direction?

**Comment by luhuaei** [comment]
> @luhuaei Above is right direction?

Great! org-noter and org-pdftools provide many useful feature. :smiley_cat:

**Comment by manateelazycat** [comment]
@luhuaei Can you help add those APIs ? Thanks

**Comment by luhuaei** [comment]
OK, I will try to add those api on pdf-viewer

**Comment by luhuaei** [comment]
#532 
`(eaf-pdf-get-annots PAGE) ` will return a map about the annot on PAGE.
if the PAGE has annot will return
```json
{
  "annot-id": {
    "type_int": "annot type enum, see https://pymupdf.readthedocs.io/en/latest/vars.html#annotation-types",
    "type_name": "annot type name",
    "rect": "the annot internal position on pymupdf page",
    "page": "the page index on pdf"
  }
}
```
if the PAGE no annot will return `{}`

use the `(eaf-pdf-jump-to-annot ANNOT)` jump to annotation position on `pdf-viewer`

*example*:
if the page `66` has an annotation, and it id is `fitzannot-0`
```
(eaf-pdf-jump-to-annot (gethash "fitzannot-0" (json-parse-string (eaf-pdf-get-annots 66))))
```

@fuxialexander Those API can satisfy compatible `org-pdftools` and `org-noter-pdftools`

**Comment by manateelazycat** [comment]
great
