### ISSUE TITLE
Cannot type capital letters in eaf's browser

### ISSUE THREAD

**Issue by xsrvmy** [manateelazycat/emacs-application-framework#53]
When I try to type capital letters in an eaf browser buffer's input field, I get an error saying that the buffer is read-only. However, lower case letters work, and both trigger the `self-insert-command`.

System and emacs info:
Kubuntu 18.04
emacs 25.2.2
Possible conflicting plugin: evil

**Comment by manateelazycat** [comment]
this mission in todolist

**Comment by manateelazycat** [comment]
@xsrvmy Bug has fixed, thanks for report! ;)
