### ISSUE TITLE
Opening pdf throws error "Wrong type argument: epc:manager, nil"

### ISSUE THREAD

**Issue by Jdogzz** [manateelazycat/emacs-application-framework#531]
**Describe the bug**
After updating to the latest version of emacs and eaf I'm coming across this error when trying to open a PDF:
```
epc:start-server: Server may raise an error. Use "M-x epc:pop-to-last-server-process-buffer RET" to see full traceback:
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mymailuser'

epc:call-deferred: Wrong type argument: epc:manager, nil
```

Trying to use the suggested function to troubleshoot further yields:
```
epc:pop-to-last-server-process-buffer: No buffer for the last server process.  Probably the EPC connection exits correctly or you didn’t start it yet.
```

**To Reproduce**
Attempt to open a PDF with eaf-open.

**Expected behavior**
It should open the PDF as usual.

**Versions (please complete the following info):**
 - Distro and DE/WM: Turnkey Core 16.0 and Xpra
 - Versions of Dependencies:
 --python-pyqt5: 5.11.3+dfsg-1+b3
 --python-dbus: 1.2.8-3
 --python-pyqtwebengine: 5.11.3+dfsg-1+b3
 - M-x emacs-version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2021-01-22

**Comment by manateelazycat** [comment]
Can you restart your emacs  and try again?

**Comment by Jdogzz** [comment]
After restarting emacs I see the same error. (I have also checked for messages output during emacs startup but see nothing out of the ordinary)

I also tried reinstalling epc since initially I had installed it for my user through pip, and just now tried instead installing it through my package manager, but that did not change the error either.

**Comment by manateelazycat** [comment]
> After restarting emacs I see the same error. (I have also checked for messages output during emacs startup but see nothing out of the ordinary)
> 
> I also tried reinstalling epc since initially I had installed it for my user through pip, and just now tried instead installing it through my package manager, but that did not change the error either.

New version EAF log debug information at buffer that prefix with "*epc:server", can you paste buffer content to me?
Thanks.

**Comment by Jdogzz** [comment]
In the buffer *eaf-server:9999* it outputs:
```
Fri Jan 22 19:40:50 2021 eaf-server:9999 <127.0.0.1:44862>: client connected
Fri Jan 22 19:41:16 2021 eaf-server:9999 <127.0.0.1:44864>: client connected
Fri Jan 22 19:54:41 2021 eaf-server:9999 <127.0.0.1:45200>: client connected
```

**Comment by manateelazycat** [comment]
> In the buffer _eaf-server:9999_ it outputs:
> 
> ```
> Fri Jan 22 19:40:50 2021 eaf-server:9999 <127.0.0.1:44862>: client connected
> Fri Jan 22 19:41:16 2021 eaf-server:9999 <127.0.0.1:44864>: client connected
> Fri Jan 22 19:54:41 2021 eaf-server:9999 <127.0.0.1:45200>: client connected
> ```

Not eaf-server:9999 buffer, is "epc:server:xxx" buffer.

**Comment by Jdogzz** [comment]
I just made sure to pull in your last round of commits from the past few minutes and restarted emacs, but I see no buffer named like you're describing, just the usual Messages, Completions, etc.

**Comment by manateelazycat** [comment]
> I just made sure to pull in your last round of commits from the past few minutes and restarted emacs, but after trying eaf-open commands I see no buffer named like you're describing, just the usual Messages, Completions, etc. The error message continues to show up.

```*epc:server*` buffer is invisible buffer, you may need find it by command ```C-b SPC```

**Comment by Jdogzz** [comment]
I saw three buffers of that form with the names epc:server:2, epc:server:4, epc:server:6, and each contents of the form:
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mymailuser'
58853
EAF process starting...
```
with slightly different 5 digit numbers on the second line.

**Comment by manateelazycat** [comment]
> I saw three buffers of that form with the names epc:server:2, epc:server:4, epc:server:6, and each contents of the form:
> 
> ```
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-mymailuser'
> 58853
> EAF process starting...
> ```
> 
> with slightly different 5 digit numbers on the second line.

I see, because python-epc need first terminal output must be port, and your output first line is not port. 

That's is cause, give me some time.

**Comment by manateelazycat** [comment]
Hi, I commit new patch https://github.com/manateelazycat/emacs-application-framework/commit/840e0ff1a8fa842d96ff9bd475cfbcb8dad6de0b

I think will fixed this issue.

Thanks for report.
