### ISSUE TITLE
Videos won't play if there's single quote mark(') in its name

### ISSUE THREAD

**Issue by feng-qi** [manateelazycat/emacs-application-framework#550]
**Describe the bug**
Videos don't play if there's single quote mark(') in it.

**To Reproduce**
For example, if the video's name is `Alice's Adventures In Wonder Land.mp4`, then the video doesn't play as expected. But with the name `Alices Adventures In Wonder Land.mp4`, it can.

**Expected behavior**
Video can play normally even with single quote mark(') in its name.

**Versions (please complete the following info):**
 - Distro and DE/WM: Xfce on Manjaro
 - Versions of Dependencies: dependencies of what?
 - M-x emacs-version:
   "GNU Emacs 28.0.50 (build 4, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.17.4) of 2021-01-25"

**Screenshots**
![image](https://user-images.githubusercontent.com/3600573/106282236-4569e780-627b-11eb-956c-73a04b32c327.png)

**Comment by manateelazycat** [comment]
Done, please update newest version.
