### ISSUE TITLE
open emm file error js: Uncaught TypeError: Cannot read property 'view' of null

### ISSUE THREAD

**Issue by improve100** [manateelazycat/emacs-application-framework#565]
OS: ubuntu2004
emacs: 27.1

An error is reported when I open the EMM file.
[项目整体管理.emm.txt](https://github.com/manateelazycat/emacs-application-framework/files/5922428/emm.txt)

Qt: Session management error: Could not open network socket
EAF process starting...
Session is not restored, as no data present in session file.
js: Uncaught TypeError: Cannot read property 'view' of null

PS:
Dropping a node with the mouse can also trigger a crash.
github.com not support upload .emm file so rename .emm to .emm.txt.

**Comment by mackong** [comment]
可以发下emm文件吗

**Comment by improve100** [comment]
@mackong 我重新上传了崩溃文件.

**Comment by mackong** [comment]
这个文件我这边打开是正常的，你试下新建一个空白的看有没有异常，或者eaf更新到最新版本

**Comment by improve100** [comment]
我尝试升级到最新eaf，偶尔还是会出现Qt: Session management error: Could not open network socket类型问题。
怀疑 python-pyqt5不稳定,采用pip安装，好一点了。
  sudo apt autoremove python3-pyqt5
  sudo apt -y install git nodejs aria2 wmctrl xdotool
  sudo apt -y install libglib2.0-dev
  pip3 install PyQt5
  pip3 install sip
  pip3 install PyQt5.qtwebengine
  pip3 install PyQtWebEngine
  pip3 install qrcode
  pip install feedparser
  pip3 install feedparser
  pip3 install markdown
  pip3 install qtconsole
  pip3 install pygit2
