### ISSUE TITLE
eaf browser size does not follow fringe and window divider settings

### ISSUE THREAD

**Issue by Vivien-lelouette** [manateelazycat/emacs-application-framework#566]
If you set fringe or window divider in your settings, eaf doesn't follow the settings. This results in the modeline partly covered if bottom divider is set, and fringes and right dividers are covered too.
I think this should be fairly easy to fix and allow more customization to the user.
See the screenshot bellow with 10 pixels dividers:
![eaf-issue](https://user-images.githubusercontent.com/25980961/106934194-20152780-671a-11eb-83b2-028220045c07.png)

**Comment by MatthewZMD** [comment]
Can you share your configurations that modified fringe and window divider settings?

**Comment by Vivien-lelouette** [comment]
The setup used in the screenshot was the following:

  (setq window-divider-default-right-width 10)
  (setq window-divider-default-bottom-width 10)
  (menu-bar-bottom-and-right-window-divider)

But the bug appears on the right side with only the following:
  (setq window-divider-default-right-width 10)
  (window-divider-mode 1)

Worth mentioning that I'm under a 27 emacs, no doom or any other distros. I'm still using the doom modeline.

**Comment by manateelazycat** [comment]
Fix by newest version.

**Comment by Vivien-lelouette** [comment]
Sorry for the late answer, I stopped using eaf for now.
I just tested it, everything is working correctly now, thank you :)
