### ISSUE TITLE
Is this a replacement for Xwidgets?

### ISSUE THREAD

**Issue by linwaytin** [manateelazycat/emacs-application-framework#57]
According to the Emacs [wiki](https://www.emacswiki.org/emacs/EmacsXWidgets), Emacs can use Gtk widgets. Is this project related to the Xwidgets feature?

I don't see you mention this in the document, and I'm curious how this works.

**Comment by manateelazycat** [comment]
here is document https://github.com/manateelazycat/emacs-application-framework/blob/master/docs/HACKING.md

**Comment by linwaytin** [comment]
Awesome, thank you.
