### ISSUE TITLE
在wsl下调用windows下的eaf，browser在history跳转之后emacs会失焦

### ISSUE THREAD

**Issue by yqu212** [manateelazycat/emacs-application-framework#571]
我这里的eaf browser在history跳转之后emacs失焦了。我想在browser.py的
insert_or_history_back和insert_or_history_forward函数里面直接激活emacs，可是发现
它们是用类似装饰器的写法生成的，不知道自么改了。

>self.build_interactive_method(self.buffer_widget, “back”, “history_backward”, insert_or_do=True)
>self.build_interactive_method(self.buffer_widget, “forward”, “history_forward”, insert_or_do=True)

**Comment by manateelazycat** [comment]
最新版应该已经修复了这个issue，有问题继续反馈。
