### ISSUE TITLE
followup to previous issue #555 now closed

### ISSUE THREAD

**Issue by mikereape** [manateelazycat/emacs-application-framework#572]
All I was going to do was forward these bits in case it's of any use to you:

[Powershell log 2021-02-07.2.txt](https://github.com/manateelazycat/emacs-application-framework/files/5939687/Powershell.log.2021-02-07.2.txt)

[2021-02-07T17_51_11_001Z-debug.log](https://github.com/manateelazycat/emacs-application-framework/files/5939688/2021-02-07T17_51_11_001Z-debug.log)

I was able to do the pull in cmd but after that I had to use Powershell because cmd couldn't see the new directory.

I wish you all the best
Mike

**Comment by MatthewZMD** [comment]
I'll take a look in a moment. You could/should re-open the issue by the way, instead of creating a new one.

**Comment by hjtoh** [comment]
> I'll take a look in a moment. You could/should re-open the issue by the way, instead of creating a new one.

其实他这个问题我在emacs上china上给你我的问题截图了，我感觉是不是"postinstall": "(cd app/js-video-player && npm install); (cd app/markdown-previewer && npm install); (cd app/terminal && npm install); (cd app/image-viewer && npm install)"
  },这的逻辑有问题，我单独进这个四个文件夹然后手动npm install就没有问题，但是node ./win32.js这种安装方式就报错，上上次那个去掉mermaid的那次js好像是对的，我看了一下js文件的内容，你好像重构了一下，问题应该出在了这里。

**Comment by hjtoh** [comment]
> All I was going to do was forward these bits in case it's of any use to you:
> 
> [Powershell log 2021-02-07.2.txt](https://github.com/manateelazycat/emacs-application-framework/files/5939687/Powershell.log.2021-02-07.2.txt)
> 
> [2021-02-07T17_51_11_001Z-debug.log](https://github.com/manateelazycat/emacs-application-framework/files/5939688/2021-02-07T17_51_11_001Z-debug.log)
> 
> I was able to do the pull in cmd but after that I had to use Powershell because cmd couldn't see the new directory.
> 
> I wish you all the best
> Mike

hey, I think you should enter the four folders separately then execute npm install, 'cause I fix the problem this way. gook luck

**Comment by mikereape** [comment]
Hi please don't do anything on my behalf. I just wanted to leave you with that in case it was any use to you. I still think this is an awesome project and I look forward to seeing it running on my Windows setup eventually. I'm afraid I can't devote anymore time to this for a while ... not sure how long. Like I said I just submitted that in case it helps you.

I just saw your reply _in real time_ haha. Maybe if I need a displacement activity.

Anyway I need to sign off for some unknown amount of time.

Thanks to you and keep up the good work.

Mike

**Comment by MatthewZMD** [comment]
> > I'll take a look in a moment. You could/should re-open the issue by the way, instead of creating a new one.
> 
> 其实他这个问题我在emacs-china上给你我的问题截图了，我感觉是不是"postinstall": "(cd app/js-video-player && npm install); (cd app/markdown-previewer && npm install); (cd app/terminal && npm install); (cd app/image-viewer && npm install)"
>   },这的逻辑有问题，我单独进这个四个文件夹然后手动npm install就没有问题，但是node ./win32.js这种安装方式就报错，上上次那个去掉mermaid的那次js好像是对的，我看了一下js文件的内容，你好像重构了一下，问题应该出在了这里。

You don't need to go to each individual app directory and run `npm install`, simply run it in the base directory would suffice. See my comment to him in the previous issue and in the `install-eaf.sh` script designed for Linux.

**Comment by MatthewZMD** [comment]
I'm closing this issue and re-opening the previous issue.

**Comment by MatthewZMD** [comment]
> Hi please don't do anything on my behalf.

He clearly wasn't *doing* anything on your behalf, and I don't think there is a communication error here. He was giving you a suggestion on the possible way to fix the problem that you're having.

**Comment by MatthewZMD** [comment]
> 上上次那个去掉mermaid的那次js好像是对的，我看了一下js文件的内容，你好像重构了一下，问题应该出在了这里。

你可以提个PR修一修，我只是单纯地改成`npm install`，还没在Windows测试过。但是请不要把npm的dependency在install script列出来，那样维护起来太麻烦，mermaid就是一个很好的例子。可以改一下package.json，参考[这个](https://stackoverflow.com/questions/50585091/how-to-run-package-json-postinstall-script-only-on-macos)
