### ISSUE TITLE
Marker and Dark-Mode is broken in browser cause by CSP violatation

### ISSUE THREAD

**Issue by mackong** [manateelazycat/emacs-application-framework#573]
Open

https://pypi.org/search/?q=pyqt5

Marker and Dark-Mode is broken with following error:
```
VM36:248 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-+pF5g66D9gtillalitx9vdLf98+r0Ycqt5KTuh4i5C4='), or a nonce ('nonce-...') is required to enable inline execution.
```

**Additional context:**
A related issues to Dark-Reader:  https://github.com/darkreader/darkreader/issues/1452

**Comment by manateelazycat** [comment]
darkreader.js now include by npm, if darkreader.js is fix, EAF not problem.

I think EAF nothing need to do with this issue.
