### ISSUE TITLE
QWidget   activate 时激活 emacs 窗口

### ISSUE THREAD

**Issue by xhcoding** [manateelazycat/emacs-application-framework#576]
现在有很多失去焦点的问题，关键在于内部的 qt 窗口 activate 导致 emacs 窗口 deactivate 了。
考虑在 eventFilter 里收到 QEvent.WindowActivate 事件时激活   emacs 窗口，但是我不知道这样会不会
带来其它副作用, @manateelazycat  大神帮忙参考下

```python

if event.type() in [QEvent.ShortcutOverride, QEvent.WindowActivate]:
    eval_in_emacs('eaf-activate-emacs-window', [])
```

**Comment by manateelazycat** [comment]
QEvent.ShortcutOverride 事件是窗口切换会发生，偶尔一次。

主要是要观察 eventFilter 的事件，看看 QEvent.WindowActivate 的频率和触发场景：
1. 频率不能太频繁，因为 active emacs 操作有点耗时
2. 触发场景看看有没有以外的情况

如果频率不频繁，同时触发QEvent.WindowActivate的情况很精准，就可以加。

**Comment by manateelazycat** [comment]
> 现在有很多失去焦点的问题，关键在于内部的 qt 窗口 activate 导致 emacs 窗口 deactivate 了。
> 考虑在 eventFilter 里收到 QEvent.WindowActivate 事件时激活 emacs 窗口，但是我不知道这样会不会
> 带来其它副作用, @manateelazycat 大神帮忙参考下
> 
> ```python
> if event.type() in [QEvent.ShortcutOverride, QEvent.WindowActivate]:
>     eval_in_emacs('eaf-activate-emacs-window', [])
> ```

@yqu212 Can you test this patch and remove all ```if platform == windows``` code?

If this patch work, you don't need add ```if platform == windows``` everywhere. ;)

**Comment by yqu212** [comment]
I have tested this patch as you asked. Sadly, it doesn't work. Emacs lose foucs
after refreshing, moving forward and backward in history.

**Comment by manateelazycat** [comment]
鼠标点击会激活窗口，但是激活的原因有很多，暂时还不能这么做。
