### ISSUE TITLE
Eaf浏览器在网页进度条没走完的时候使用快捷键会卡死Emacs

### ISSUE THREAD

**Issue by yqu212** [manateelazycat/emacs-application-framework#577]
**Describe the bug**
加载一个大型网站，Eaf浏览器在网页进度条没走完的时候使用快捷键会卡死Emacs

**To Reproduce**
加载emacs-china或更大型的网站，Emacs顶部eaf的进度条没走完的时候按任意快捷键

**Expected behavior**
Emacs卡死，界面无反应，CPU保持在25%

**Versions (please complete the following info):**
 - Distro and DE/WM: wsl1+eaf on Windows
 - Versions of Dependencies: 最新
 - M-x emacs-version: Emacs 28

**Screenshots**

**Additional context**
我这里这个问题已经反复出现了，挺烦人的，最近才发现规律。会不会是EPC的问题？

**Comment by manateelazycat** [comment]
估计是Windows的原因，我这边没遇到过。

**Comment by yqu212** [comment]
那我再看看。

先关了，有新情况我再来反馈

**Comment by doneself** [comment]
我也经常会卡住。

**Comment by yqu212** [comment]
据我观察似乎都是EPC服务出问题，然后Emacs一直尝试连接，然后就被卡死了。我也没找到确切原因，所以现在尽量小心点，少踩雷。不过很多时候莫名其妙就卡死了，也挺烦人的。
