### ISSUE TITLE
load-file-name not defined in Emacs 27

### ISSUE THREAD

**Issue by QiangF** [manateelazycat/emacs-application-framework#579]
**Describe the bug**

    (defvar eaf-python-file (expand-file-name "eaf.py" (file-name-directory load-file-name)))

**Comment by MatthewZMD** [comment]
It is defined in emacs37, please check your emacs configuration.

Check by running `emacs -q`, `M-x emacs-version`: `GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28` 

`C-h v load-file-name` gives 
```
load-file-name is a variable defined in ‘C source code’.
Its value is nil

Documentation:
Full name of file being loaded by ‘load’.
```

**Comment by QiangF** [comment]
Sorry the error is caused by manually evaluating the code. Maybe just use (locate-library "eaf") .
