### ISSUE TITLE
Link hints hidden by hovering adds

### ISSUE THREAD

**Issue by QiangF** [manateelazycat/emacs-application-framework#580]
**Describe the bug**
www.ifeng.com news page has many small ads, when I try to close those ads using link hint,  I only see the hint borders, hint char are blocked by ad window, and some hint are hidden completely.

**Versions (please complete the following info):**
 i3wm Arch linux Emacs 27

**Comment by manateelazycat** [comment]
@MatthewZMD Any idea?

**Comment by MatthewZMD** [comment]
Can you give a specific URL or screenshot, the ifent homepage seems working fine.

**Comment by QiangF** [comment]
Try https://news.ifeng.com/c/83pwteC5IhR
The ifeng home page doesn't have annoying ads.

**Comment by manateelazycat** [comment]
> Try https://news.ifeng.com/c/83pwteC5IhR
> The ifeng home page doesn't have annoying ads.

@MatthewZMD Can you help fix this?

**Comment by MatthewZMD** [comment]
I'll have a look later, quite busy lately

**Comment by MatthewZMD** [comment]
> Try https://news.ifeng.com/c/83pwteC5IhR
> The ifeng home page doesn't have annoying ads.

A few has been fixed in a recent commit. However I think the better fix is to add them to the adblocker. Someone can have a closer look into it.
