### ISSUE TITLE
Using eaf with LaTeX file "Compile and view" command

### ISSUE THREAD

**Issue by Jdogzz** [manateelazycat/emacs-application-framework#581]
**Describe the bug**
I have been attempting to use eaf with the LaTeX file "Compile and view" command (C-c C-a) instead of other system viewers. I managed to cobble together a few lines in my config file:

```
;; from TeX-pdf-tools-sync-view
;;;###autoload
(defun TeX-eaf-sync-view()
  (unless (fboundp 'eaf-open)
    (error "EAF is not available!"))
  (let* ((pdf (TeX-active-master (TeX-output-extension)))
         (url (expand-file-name pdf))
         (app-name "pdfviewer")
         (exists-eaf-buffer)
         (eaf-buffer-window))
    (catch 'found-match-buffer
      (dolist (buffer (buffer-list))
        (set-buffer buffer)
        (when (equal major-mode 'eaf-mode)
          (when (and (string= buffer-url url)
                     (string= buffer-app-name app-name))
            (setq exists-eaf-buffer buffer)
            (setq eaf-buffer-window (get-buffer-window exists-eaf-buffer))
            (throw 'found-match-buffer t)))))
    (if (and exists-eaf-buffer eaf-buffer-window)
        (pop-to-buffer exists-eaf-buffer)
      (eaf-open url app-name "--synctex_on=True"))))

(eval-after-load "tex"
  '(progn
	(add-to-list 'TeX-view-program-list '("eaf" TeX-eaf-sync-view))
(add-to-list 'TeX-view-program-selection '(output-pdf "eaf"))
))
```

As far as I can tell, the compile part works perfectly, but the view part causes eaf to hang and not display the file, just an empty buffer. I can even navigate in dired to some other PDF file and open it with eaf after enough time (if opening a file immediately after it will still hang). Restarting emacs, I am able to open the compiled PDF just fine in eaf, it's just the procedure of opening it with the above Compile and view command that doesn't work.

**To Reproduce**
After adding the standard lines from the eaf readme and my above lines to the emacs config file:

1. Open a tex file, for example my test.tex file with this as its contents:
```
\documentclass{article}

\begin{document}
First document. This is a simple example, with no 
extra parameters or packages included.
\end{document}
```
2. Select the Command>Compile and view entry from the GUI (listed as C-c C-a).

**Expected behavior**
The PDF file generated from compiling the tex file should open.

**Versions (please complete the following info):**
    Distro and DE/WM: Turnkey Core 16.0 and Xpra
    Versions of Dependencies:
        python-pyqt5: 5.11.3+dfsg-1+b3
        python-dbus: 1.2.8-3
        python-pyqtwebengine: 5.11.3+dfsg-1+b3
    M-x emacs-version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2021-02-12

Notes: please add a corresponding GitHub Label so future people can find this issue easier.

**Screenshots**

**Additional context**
The lines I added to my config were put together from these sources:

[https://github.com/xhcoding/doom-private/blob/master/autoload.el](url)
[https://github.com/xhcoding/doom-private/blob/master/config.el](url)
[https://tex.stackexchange.com/questions/150485/configuring-auctex-for-pdf-viewer](url)
[http://git.savannah.gnu.org/cgit/auctex.git/tree/tex.el](url)

**Comment by xhcoding** [comment]
change `(app-name "pdfviewer")` to `(app-name "pdf-viewer")`

**Comment by Jdogzz** [comment]
That worked, thank you very much!

**Comment by manateelazycat** [comment]
@Jdogzz Can you share your config in EAF Wiki ? 

Maybe this function will help other emacs LaTex user, thanks! ;)

**Comment by Jdogzz** [comment]
@manateelazycat Sure thing, added it to the wiki now at this page: [https://github.com/manateelazycat/emacs-application-framework/wiki/LaTeX](https://github.com/manateelazycat/emacs-application-framework/wiki/LaTeX)

Since the majority of the code came from @xhcoding 's repo (or at least that's where I first came across it) it can be updated to reflect proper attribution if needed.
