### ISSUE TITLE
flash when loading image in image-viewer

### ISSUE THREAD

**Issue by yqu212** [manateelazycat/emacs-application-framework#588]
There are two cases:
1. load first image
2. load second image

The second case is caused by the height change of minibuffer after message sent
by eaf disappears. The solution is to prevent eaf from sending message in
image-viewer, such as:

> [EAF/image-viewer] Opening ~/sample.jpg
> [EAF/image-viewer] Kill selected text.
> [EAF/image-viewer] Yank selected text.
> [EAF/image-viewer] Kill selected text.
> [EAF/image-viewer] Yank selected text.

The first case is caused by the white background of browser. The solution is to
set the background color to the color of image-viewer. I have confirmed that
setting dark-mode for image-viewer can fix this case.

@manateelazycat Can you fix this issue today? I'm not familiar with the related codes
so if I do the job, I need some time to read the code and the fix have to be
delayed to tomorrow.

**Comment by manateelazycat** [comment]
done

**Comment by yqu212** [comment]
The second case has not been fixed. There is still message "EAF image viewer Opening sample.jpg".

**Comment by yqu212** [comment]
@manateelazycat I have confirmed that just setting resize-mini-window to nil can fix this issue.

**Comment by manateelazycat** [comment]
> @manateelazycat I have confirmed that just setting resize-mini-window to nil can fix this issue.

I think your problem is font setting, when you change difference font, minibuffer won't resize.

I have try set resize-mini-window before, it's wrong choose, because some awesome plugin can't work, such as, kill-ring-search

**Comment by yqu212** [comment]
No. My point is to set this variable as a buffer local one. It will not influence any plugin other than the image viewer itself.

In my emacs, the variable is set to its default (grow-only), the minibuffer will expand automatically to accommodate the text. When the message disappear,the minibuffer shrinks automatically. This causes the flash when the second image loads,not the font setting.

**Comment by manateelazycat** [comment]
> No. My point is to set this variable as a buffer local one. It will not influence any plugin other than the image viewer itself.
> 
> In my emacs, the variable is set to its default (grow-only), the minibuffer will expand automatically to accommodate the text. When the message disappear,the minibuffer shrinks automatically. This causes the flash when the second image loads,not the font setting.

如果只是针对 image-viewer 可以发一个PR吧。
