### ISSUE TITLE
网页字体不能显示。

### ISSUE THREAD

**Issue by doneself** [manateelazycat/emacs-application-framework#599]
windows 10，一直用都好好的，然后突然网页字体不显示了，重启还是那样，没看到其他错误信息。

![pic](https://emacs-china.org/uploads/default/optimized/2X/1/1d63fd1fbc70fc1f11b7d72393ce435399ae18cc_2_1035x570.jpeg)

**Comment by manateelazycat** [comment]
去掉这个补丁的变动再看看？ https://github.com/manateelazycat/emacs-application-framework/commit/41bd38620120428edf5695cefde33065faf206e8

**Comment by doneself** [comment]
> 去掉这个补丁的变动再看看？ [41bd386](https://github.com/manateelazycat/emacs-application-framework/commit/41bd38620120428edf5695cefde33065faf206e8)

去掉后就显示正常了。

**Comment by manateelazycat** [comment]
> > 去掉这个补丁的变动再看看？ [41bd386](https://github.com/manateelazycat/emacs-application-framework/commit/41bd38620120428edf5695cefde33065faf206e8)
> 
> 去掉后就显示正常了。

看来windows不能引入硬件加速，我稍后修复。
