### ISSUE TITLE
vesions of QT & PyQt5

### ISSUE THREAD

**Issue by yssource** [manateelazycat/emacs-application-framework#6]
```
    from app.browser.buffer import BrowserBuffer
<module>
    from PyQt5.QtWebKitWidgets import QWebView, QWebPage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```
Hi, 
QtWebKit got deprecated upstream in Qt 5.5 and removed in 5.6.
You may want to switch to PyQt5.QtWebEngineWidgets

**Comment by manateelazycat** [comment]
我这边 Qt 5.11 都可以用 QtWebView。

QtWebEngineWidgets后端是OpenGL, 新卡兼容性各种问题，内存泄漏和各种不能开发的问题。

不会用 QtWebEngine的

**Comment by Compro-Prasad** [comment]
@manateelazycat It will be helpful if you could reply in English.

**Comment by mut0u** [comment]
I have the same problem.

I use fedora 28 and install qt env

```
sudo dnf install python3-pyqt5  python3-qt5-devel
pip3 install  pyqt5

```
I can import `QWebEngineView` from `PyQt5.QtWebEngineWidgets` , but I can not impot `QWebView`
