### ISSUE TITLE
Not working with HiDPI

### ISSUE THREAD

**Issue by yangsheng6810** [manateelazycat/emacs-application-framework#60]
I am using emacs 26.2 on i3 on Arch Linux. On one machine with normal display (1366x768 on a 14 inch screen), eaf works. However, on the other machine with HiDPI (2560x1440 on a 14 inch screen), eaf is kind of cropped, as shown in the following picture.
![1](https://user-images.githubusercontent.com/2863729/59547368-d73ca980-8f0b-11e9-9c8e-24cba9eaec7a.png)
To make things worse, the display from eaf totally covers the components from emacs, i.e. scroll bar, modeline, minibuffer, etc. It also blocks all inputs to emacs. I tried wrapping
```python
app = QApplication(sys.argv)
```
with 
```python
        os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
        app = QApplication(sys.argv)
        app.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
```
as suggested by [pyat5 and 4k screen](https://stackoverflow.com/questions/41331201/pyqt-5-and-4k-screen), but it didn't work.

I managed to make it work with the following quick hack since I have a scale of 2. Ideally, this number should come from some variable or environmental variable. This can be tricky though: this might involve scaling both from the python side and the emacs side. Since currently PDF is showing a little bit of blur, I guess the proper way of handling would be emacs pass the exact available width/height, while PyQt handles the HiDPI case.
```diff
modified   eaf.el
@@ -221,6 +221,8 @@ We need calcuate render allocation to make sure no black border around render co
          (width (frame-pixel-width))
          ;; Render height should minus mode-line height, minibuffer height, header height.
          (height (- (frame-pixel-height) (window-mode-line-height) (window-pixel-height (minibuffer-window)) window-header-height)))
+    (setq width (/ width 2)
+          height (/ height 2))
     (mapcar (lambda (x) (format "%s" x)) (list width height))))
 
 (defun eaf-get-window-allocation (&optional window)
@@ -230,6 +232,10 @@ We need calcuate render allocation to make sure no black border around render co
          (w (- (nth 2 window-edges) x))
          (h (- (nth 3 window-edges) y))
          )
+    (setq x (/ x 2)
+          y (/ y 2)
+          w (/ w 2)
+          h (/ h 2))
     (list x y w h)))
 
 (defun eaf-generate-id ()
```
One minor thing that I need to mention is that when an eaf buffer is focused, it does not seem to pass emacs commands to emacs. Since it also happens to my other machine, I guess I should report a separate bug for this?

**Comment by manateelazycat** [comment]
I haven't HiDPI monitor, sorry i can't test it. ;(

**Comment by yangsheng6810** [comment]
Shall we keep this issue open while I spend some time fixing the issue? It is also OK to close it and I will make a PR when I have a reasonably mature patch ready.

**Comment by manateelazycat** [comment]
PR are welcome!

**Comment by stardiviner** [comment]
Is there a solution for this? I installed Arch Linux on MacBook Pro with a Retina screen. The position of EAF displayed is bigger than Emacs window.

I can help for testing.

**Comment by manateelazycat** [comment]
I haven't HiDPI screen.

I think code should get device scale factor, then adjust render x, y, width, height.

Sorry, I know how to fix this issue, but i haven't HiDPI device now.

**Comment by stardiviner** [comment]
Maybe I can provide remote access for you. WDYT?

**Comment by manateelazycat** [comment]
Thank you, it need much time.

**Comment by stardiviner** [comment]
Ok, I see. Thanks for considering that.

**Comment by xhcoding** [comment]
I have the same issue on manjaro kde 4k screen, my system scale is 2. `QT_SCREEN_SCALE_FACTORS=VGA-1=2;` is set as environment variable, so EAF program has double scaling.

I remove the relevant environment variables from the `process-environment` to disable QT scaling, let EAF qt program follow the system scale.

```elisp
(require 'seq)

(setq process-environment (seq-filter
 (lambda(var)
   (and (not (string-match-p "QT_SCALE_FACTOR" var))
        (not (string-match-p "QT_SCREEN_SCALE_FACTOR" var)))) process-environment))

(eaf-setq eaf-browser-default-zoom  "2") 

```

**Comment by stardiviner** [comment]
This is very great, It works for me too. Thanks @xhcoding !!

@manateelazycat Can this workaround be in EAF source code?
