### ISSUE TITLE
EAF error on opening web browser

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#603]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please add a corresponding GitHub Label so future people can find this issue easier.

Yes, latest version. commit `511d2ac`.

**Describe the bug**

When I open web browser with command `eaf-open-browser` with URL or open local html file with `eaf-open-browser`. Bot open a new buffer but white blank page.

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

**Expected behavior**

Should open URL or local html file correctly display.

**Versions (please complete the following info):**
 - Distro and DE/WM: `Arch Linux, KDE/Plasma`
 - Versions of Dependencies:
 - M-x emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.17.4) of 2021-01-26`

**Screenshots**

https://imgur.com/a/G5YIYZg

**Additional context**

**Comment by manateelazycat** [comment]
Just reboot Emacs and try.

**Comment by stardiviner** [comment]
Rebooted system, and Emacs, and try again. Problem still remain.

**Comment by stardiviner** [comment]
When I press `x` key on eaf web browser, it shows message `epc:net-send: Process epc con 4 not running`.
The `*eaf*` buffer error output:
```
EAF process starting...
Traceback (most recent call last):
  File "/home/stardiviner/Code/Emacs/emacs-application-framework/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/stardiviner/Code/Emacs/emacs-application-framework/eaf.py", line 256, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '222b-ad7d-4626-0641-f1c4-a70d-367b'

Process *eaf* aborted (core dumped)
```

**Comment by manateelazycat** [comment]
> When I press `x` key on eaf web browser, it shows message `epc:net-send: Process epc con 4 not running`.
> The `*eaf*` buffer error output:
> 
> ```
> EAF process starting...
> Traceback (most recent call last):
>   File "/home/stardiviner/Code/Emacs/emacs-application-framework/core/utils.py", line 58, in on_signal_received
>     self._func(obj, *args, **kwargs)
>   File "/home/stardiviner/Code/Emacs/emacs-application-framework/eaf.py", line 256, in update_views
>     view = View(self.buffer_dict[buffer_id], view_info)
> KeyError: '222b-ad7d-4626-0641-f1c4-a70d-367b'
> 
> Process *eaf* aborted (core dumped)
> ```

目前我还重现你的问题，你有稳定重现步骤吗？

**Comment by stardiviner** [comment]
由于我是早期版本的EAF也用，新版的 install-eaf.sh  也执行了。所以环境依赖可能比较复杂了。这个没法复现。

EAF版本，我是在 commit `511d2ac` 上。

操作步骤：
1. `M-x eaf-open-browser RET baidu.com`
2. 接着打开就是空白的了。

**Comment by manateelazycat** [comment]
新版没有问题，那就没有问题啊。

不可能在这个改了架构以后还兼顾老版本。

**Comment by stardiviner** [comment]
sorry,可能是我表述错误，我的意思是我是老版本一直用下来的，没有卸载老的那些安装的东西。直接执行了新版本的安装脚本。我是怕新旧的两个安装的东西会混淆和冲突之类的。
