### ISSUE TITLE
Add Sway support

### ISSUE THREAD

**Issue by Armoken** [manateelazycat/emacs-application-framework#604]
I am using sway, and due to missing of support of it in EAF all  EAF windows cannot be placed in a valid place. They even are not floating by default.

I have tried to fix it using `for_window [app_id="python3"] floating enable` line in Sway config. But it doesn't fix window positioning and can affect on non-EAF applications. Therefore all EAF windows should have app_id different from python3. For example emacs_application_framework.

Current positioning with using of described above fix:
![EAF-Positionint](https://user-images.githubusercontent.com/11635947/110686483-8a752800-81f0-11eb-8e1a-35e16b639e48.jpg)

**Comment by manateelazycat** [comment]
EAF current depend on XReparent tech, that's mean depend on XWayland.
EAF can't work on Wayland composite now, and not easy to do that.

**Comment by MatthewZMD** [comment]
> Therefore all EAF windows should have app_id different from python3. For example emacs_application_framework.

Is that some sway configuration? Is there anything we need to do on our side?

**Comment by Armoken** [comment]
> > Therefore all EAF windows should have app_id different from python3. For example emacs_application_framework.
> 
> Is that some sway configuration? Is there anything we need to do on our side?

Yes. **X11** has a property called **WM_CLASS** that lets you set the class and application names for an application. This is used, for instance, by **kwin** and **compiz** for setting window-specific rules. **app_id** is almost the same, but for Wayland.

I tried to fix it by setting organization domain (QApplication.setOrganizationDomain) or (QApplication.setApplicationDisplayName) in eaf.py. It works but I think authors of this framework can choose more suitable names.

**Comment by Armoken** [comment]
> EAF current depend on XReparent tech, that's mean depend on XWayland.
> EAF can't work on Wayland composite now, and not easy to do that.

But maybe you can run eaf windows using XWayland? Because at present they running as Wayland windows (But i could be wrong )

**Comment by manateelazycat** [comment]
> > EAF current depend on XReparent tech, that's mean depend on XWayland.
> > EAF can't work on Wayland composite now, and not easy to do that.
> 
> @manateelazycat But maybe you can run eaf windows using XWayland? Because at present they running as Wayland windows (But i could be wrong )

I use gnome3 wayland, works well

**Comment by Armoken** [comment]
@manateelazycat I fixed it by using `QT_QPA_PLATFORM=xcb` environment variable. I think that eaf should set it, to allow run other Qt applications using wayland.

**Comment by manateelazycat** [comment]
@Armoken Can you test newest version ?

**Comment by Armoken** [comment]
@manateelazycat Awesome, it works!
