### ISSUE TITLE
EAF Browser new tab won't reset zoom 

### ISSUE THREAD

**Issue by manateelazycat** [manateelazycat/emacs-application-framework#605]
If user open page by url, browser reset zoom as expect.

But browser won't reset zoom correctly if page open by vimium link.

**Comment by MatthewZMD** [comment]
我觉得现在这样没问题：通过vimium点开的新页面跟当前页面有关联，所以保持当前页面的zoom是可以理解的；通过eaf-open-browser打开的新页面是不一定跟当前页面有关系的，所以reset成了default zoom

**Comment by manateelazycat** [comment]
> 我觉得现在这样没问题：通过vimium点开的新页面跟当前页面有关联，所以保持当前页面的zoom是可以理解的；通过eaf-open-browser打开的新页面是不一定跟当前页面有关系的，所以reset成了default zoom

关键是vimium点开的页面没有关联，打开以后非常小。4k屏幕必现。

**Comment by MatthewZMD** [comment]
我这边测了一下，如果`(eaf-setq eaf-browser-default-zoom "2")`，然后手动`-`到`1`左右，这个时候不论是用vimium还是eaf-open-browser打开新页面都会重置回2。

**Comment by manateelazycat** [comment]
重现步骤：
1. Google搜索任意关键字
2. 调用 insert_or_open_link_new_buffer 在新标签打开网页，缩放正常
3. 调用 insert_or_open_link 命令在当前页打开链接，缩放不正常

经过研究发现，当前页面是直接调用 setUrl 切换内容，但 setUrl 以后，zoom factor会变成1。
把逻辑改成 “所有页面加载完毕后重新设置页面缩放”，这样可以保证页面新建或者setUrl后都会调整 zoom factor 为用户设置的值。
