### ISSUE TITLE
Eaf crashing on load.

### ISSUE THREAD

**Issue by jeetelongname** [manateelazycat/emacs-application-framework#614]
As I have not mentioned it. I would like too say that I love this project and I thank you for not only advancing the ability of emacs but also my slow decent into insanity 

- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
I have done this.
- Please add a corresponding GitHub Label so future people can find this issue easier.
I am not sure how to do this (sorry).
**Describe the bug**
EAF crashes no matter the application 
I have not used EAF in a while due to neglect and moving to emacs 28 pgtk native comp. I updated all the dependencys as specified in the discussion linked in this issue. and remade the package! declaration (I use doom emacs) to include all the new files

```lisp
(package! eaf :recipe
  (:host github
   :repo "manateelazycat/emacs-application-framework"
   :files ("*")
   :build (:not compile))) ;; specify not to compile files
```
then I ran `M-x eaf-install-dependencies` 
and the install.sh in the build root due to sudo not being able to install the node dependencies 

```lisp
(use-package! eaf
  :defer t
  :init
  (use-package! epc :defer t)
  (use-package! ctable :defer t)
  (use-package! deferred :defer t)
  (use-package! s :defer t)
  :config
  (setq eaf-enable-debug t) ; should only be used when eaf is wigging out
  (eaf-setq eaf-browser-dark-mode "false") ; dark mode is overrated
  (setq eaf-browser-default-search-engine "duckduckgo")
  (eaf-setq eaf-browse-blank-page-url "https://duckduckgo.com"))

(use-package! eaf-evil ;; evil bindings in my browser
  :after eaf
  :config
  (setq eaf-evil-leader-keymap doom-leader-map)
  (setq eaf-evil-leader-key "spc"))
```

**To Reproduce**
1) rebuild eaf and subsequent packages.
2) install dependencies as specified
3) `M-x eaf-open-demo` (which works? it opens up a child widow that can be manipulated outside of emacs (I use GNOME) 
4) `M-x eaf-open-browser` (which does not work and produces the error you will see bellow)
   this is the case for all commands
5) Cry

**Expected behavior**
Eaf would work as expected after reinstalling all the dependencies and I would be happy 
(I am not sure if this is enough detail (its not but I am not sure what else to put))

**Versions (please complete the following info):**
 - Pop OS (ubuntu) 20:10 using GNOME: 3.38 
 - Versions of Dependencies:
    - All emacs packages are from there current build of melpa 
    - git 2.30.1
    - node v12.18.2
    - npm 6.14.8
    - aria2 1.35.0
    - wmctrl 1.07
    - xdotool 3.20160805.1
    - libglib2.0-dev 2.66.1
    
    - python3-pyqt5 5.15.0+dfsg-1
    - python3-sip 4.19.24+dfsg-1
    - python3-pyqt5.qtwebengine 5.15.0-1
    - python3-qrcode 6.1-2
    - python3-feedparser 5.2.1-2
    - python3-markdown 3.2.2-2
    - python3-qtconsole 4.7.6-1
    - python33-pygit2 1.0.3-1
    
    - "@mozilla/readability": "0.4.1",
    - "darkreader": "4.9.27"

 - M-x emacs-version:
 GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)

**Screenshots**

**Additional context**
<details> 
this backtrace comes from opening up `eaf-camera` but similar ones come from other commands 

```

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 15808]
[New Thread 0x7fffe0e28640 (LWP 15809)]
[New Thread 0x7fffdb833640 (LWP 15810)]
[New Thread 0x7fffdaea2640 (LWP 15811)]
[New Thread 0x7fffda511640 (LWP 15812)]
[New Thread 0x7fffd98e2640 (LWP 15814)]
[New Thread 0x7fffd8f30640 (LWP 15815)]
[New Thread 0x7fffbcd60640 (LWP 15819)]
[New Thread 0x7fffb7fff640 (LWP 15820)]
[New Thread 0x7fffb766e640 (LWP 15821)]
[New Thread 0x7fffb6cdd640 (LWP 15822)]
[New Thread 0x7fffb634c640 (LWP 15823)]
[New Thread 0x7fffb59bb640 (LWP 15824)]
[New Thread 0x7fffb502a640 (LWP 15825)]
[New Thread 0x7fff9ffff640 (LWP 15826)]
[New Thread 0x7fff9f66e640 (LWP 15827)]
[New Thread 0x7fff9ecdd640 (LWP 15828)]
[New Thread 0x7fff9e34c640 (LWP 15829)]
[New Thread 0x7fff9d9bb640 (LWP 15830)]
[New Thread 0x7fff9d02a640 (LWP 15831)]
[New Thread 0x7fff83fff640 (LWP 15832)]
[New Thread 0x7fff8366e640 (LWP 15833)]
[New Thread 0x7fff82cdd640 (LWP 15834)]
Qt: Session management error: Could not open network socket
[New Thread 0x7fff8234c640 (LWP 15836)]
[New Thread 0x7fff819bb640 (LWP 15837)]
[New Thread 0x7fff8102a640 (LWP 15838)]
[Detaching after fork from child process 15839]
EAF process starting...
[New Thread 0x7fff67fff640 (LWP 15851)]
[New Thread 0x7fff6766e640 (LWP 15852)]
[New Thread 0x7fff66cdd640 (LWP 15853)]
[New Thread 0x7fff6634c640 (LWP 15854)]
[Thread 0x7fff66cdd640 (LWP 15853) exited]
[New Thread 0x7fff66cdd640 (LWP 15855)]
[Thread 0x7fff6766e640 (LWP 15852) exited]
[Thread 0x7fff6634c640 (LWP 15854) exited]
[Thread 0x7fff66cdd640 (LWP 15855) exited]
Traceback (most recent call last):
  File "/home/jeet/.config/emacs.doom/.local/straight/repos/emacs-application-framework/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/jeet/.config/emacs.doom/.local/straight/build-28.0.50/eaf/eaf.py", line 133, in new_buffer
    self.create_app(buffer_id, str(url), "app.{0}.buffer".format(str(app_name)), str(arguments))
  File "/home/jeet/.config/emacs.doom/.local/straight/build-28.0.50/eaf/eaf.py", line 180, in create_app
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/jeet/.config/emacs.doom/.local/straight/build-28.0.50/eaf/eaf.py", line 194, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, eaf_config_dir, arguments, self.emacs_var_dict, module_path)
  File "/home/jeet/.config/emacs.doom/.local/straight/repos/emacs-application-framework/app/camera/buffer.py", line 41, in __init__
    self.add_widget(CameraWidget(QColor(0, 0, 0, 255)))
  File "/home/jeet/.config/emacs.doom/.local/straight/repos/emacs-application-framework/app/camera/buffer.py", line 88, in __init__
    self.select_camera(0)
  File "/home/jeet/.config/emacs.doom/.local/straight/repos/emacs-application-framework/app/camera/buffer.py", line 95, in select_camera
    self.camera = QCamera(self.available_cameras[i])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/jeet/.config/emacs.doom/.local/straight/repos/emacs-application-framework/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/jeet/.config/emacs.doom/.local/straight/build-28.0.50/eaf/eaf.py", line 256, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '2f5c-356f-71ef-401c-7da7-147c-43c9'
[New Thread 0x7fff66cdd640 (LWP 15856)]
[Thread 0x7fff66cdd640 (LWP 15856) exited]
Traceback (most recent call last):
  File "/home/jeet/.config/emacs.doom/.local/straight/repos/emacs-application-framework/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/jeet/.config/emacs.doom/.local/straight/build-28.0.50/eaf/eaf.py", line 256, in update_views
    view = View(self.buffer_dict[buffer_id], view_info)
KeyError: '2f5c-356f-71ef-401c-7da7-147c-43c9'
[New Thread 0x7fff66cdd640 (LWP 15857)]
[Thread 0x7fff66cdd640 (LWP 15857) exited]
[Thread 0x7fffd98e2640 (LWP 15814) exited]

```

</details>

If you need more then just let me know. Now I need to go too bed. I may try to automate this horrid process of dependencies finding but thats a topic for a less sleep deprived person

**Comment by MatthewZMD** [comment]
> I have not used EAF in a while due to neglect and moving to emacs 28 pgtk native comp

Probably due to this issue #449 , EAF currently doesn't work with the pgtk port of Emacs, unfortunately.

**Comment by jeetelongname** [comment]
Ah thats a shame. Ill watch your project with great interest tho and I will wait for the day I can. (also my google fu sucks I could have saved my self so much time.) anyway thanks!
