### ISSUE TITLE
Use random port to start epc-server when starting Emacs

### ISSUE THREAD

**Issue by zbelial** [manateelazycat/emacs-application-framework#617]
**Is your feature request related to a problem? Please describe.**
When starting more than one Emacs instance, all instances except the first one will signal an error because EAF wants to start an epc server at startup.

**Describe the solution you'd like**
Use a random port number.

**Additional context**
按现在的实现方式，随Emacs进程起多个epc server应该没有问题吧？port不同，消息应该不会乱，不像原来用dbus的时候。

**Comment by manateelazycat** [comment]
> **Is your feature request related to a problem? Please describe.**
> When starting more than one Emacs instance, all instances except the first one will signal an error because EAF wants to start an epc server at startup.
> 
> **Describe the solution you'd like**
> Use a random port number.
> 
> **Additional context**
> 按现在的实现方式，随Emacs进程起多个epc server应该没有问题吧？port不同，消息应该不会乱，不像原来用dbus的时候。

随机端口做了，但是没测试过多个emacs实例

**Comment by zbelial** [comment]
现在的代码确实是支持随机端口的，但是在`(defvar eaf-server ...)`的时候还是用的9999这个端口号。这就导致第二个Emacs实例启动时报错，EAF也没法用。

可以测试同时起多个实例看看。

**Comment by manateelazycat** [comment]
主要是没有想到Elisp端用生成可用随机端口的好方法，如果有的话，理论上刻意解决你说的问题。

**Comment by manateelazycat** [comment]
最新版已经支持随机端口了，@zbelial 你可以测试一下多frame，有问题，我们再提交新的issue修复。
