### ISSUE TITLE
Allow opening youtube videos inside buffer with EAF video player

### ISSUE THREAD

**Issue by melodrom** [manateelazycat/emacs-application-framework#619]
With players like mpv and vlc I can usually just type `mpv <youtube-link>` into the command line and have them open the video, id love to do that but with the EAF video player. for example be able to hover over a youtube link in an elfeed entry and open it automatically. im pretty sure mpv does that using youtube-dl.

**Comment by manateelazycat** [comment]
PR are welcome

**Comment by OrionRandD** [comment]
> With players like mpv and vlc I can usually just type `mpv <youtube-link>` into the command line and have them open the video, id love to do that but with the EAF video player. for example be able to hover over a youtube link in an elfeed entry and open it automatically. im pretty sure mpv does that using youtube-dl.

I havent tested in with elfeed, but it eaf opens YT videos inside Emacs here...

**Comment by manateelazycat** [comment]
I don't have time on this, you can write code that call youtube-dl and pass to eaf video player.

**Comment by OrionRandD** [comment]
Ok. Thx.
I have ditched eaf as well.
That was giving me some headache as well....
