### ISSUE TITLE
Suggestion: save eaf buffers in bookmarks

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/emacs-application-framework#62]
I really enjoy the speed and capabilities of eaf. However, it would be nicer and more user-friendly if we can save eaf buffers in bookmarks (or something similar to bookmarks)
Examples:
* Browser: Save Google homepage in a bookmark so we don't need to manually type `eaf-open-url RET https://www.google.com` every time when we need to open google.
* PDF Viewer: Save pdf files in a bookmark. When opening a pdf file directly from a bookmark, it goes to the position we saved last time, without manually finding the file. (similar behavior exists in pdf-tools already)
* Same idea goes with video player, image viewer ...

**Comment by manateelazycat** [comment]
Good idea, PR we welcome!

**Comment by manateelazycat** [comment]
@MatthewZMD 按照你对 EAF 的熟悉程度，我觉得这个功能你可以直接发PR哈，我最近超急忙，估计最多只有时间合并你的补丁了，哈哈哈哈

**Comment by MatthewZMD** [comment]
哈哈哈，我有空时研究研究

**Comment by stardiviner** [comment]
This also can be added to Org Mode link support. Will be very useful for Org Mode.

**Comment by luhuaei** [comment]
我觉得利用[interleave](https://github.com/rudolfochrist/interleave)这种形式代替进行交互可能更加方便。具有书签的功能同时也具有做笔记的功能。

对interleave进行尝试，采用eaf-pdf-viewer接口，可以得到以下的效果，勉强可以用...
![GIFrecord_2019-10-26_141048](https://user-images.githubusercontent.com/46041665/67622794-82615600-f850-11e9-938a-5442986f41ae.gif)可以实现上面所讨论的根据笔记对pdf页面进行跳转。

同样也可以用于浏览器、当浏览某一个书签时，还可以提示你在当前页面是否具有笔记等等。

**Comment by stardiviner** [comment]
This is an good idea!! @luhuaei , how do you implemented that? Can you share your patch code? or add PR to `eaf`? Style like interleave is really awesome, and portable.

**Comment by luhuaei** [comment]
跳转是使用`pdf-viewer`自带的跳转功能，插入笔记是从`pdf-viewer`返回信息，再插入到`org`中。你可以参考 https://github.com/luhuaei/interleave/blob/add-eaf/interleave.el  @stardiviner

**Comment by MatthewZMD** [comment]
@luhuaei 这是一个很好的方案，你可以提个PR。我觉得依旧也可以支持内置bookmark，这样总体保持一致，并且支持[emacs-dashboard](https://github.com/emacs-dashboard/emacs-dashboard)

**Comment by clemera** [comment]
For browser app one can now save bookmarks.

**Comment by manateelazycat** [comment]
Newest version has support browser and pdf-viewer with bookmarks.
