### ISSUE TITLE
Recaptcha support for EAF-browser

### ISSUE THREAD

**Issue by PiFlUn** [manateelazycat/emacs-application-framework#622]
I just wanted to login today to a website and I can't because EAF-browser does not support it. Is there a plan to support it? Is it hard to do that? I have absolutely no idea.

**Comment by manateelazycat** [comment]
try change user agent

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/emacs-application-framework/issues/484

**Comment by PiFlUn** [comment]
How do I do that?

**Comment by MatthewZMD** [comment]
07ab655
