### ISSUE TITLE
eaf-send-key-sequence doesn't work for <angled> keys

### ISSUE THREAD

**Issue by piknik** [manateelazycat/emacs-application-framework#628]
Hello,

I have tried to use `eaf-send-key-sequence` for some keys like `C-<backspace>` but then I get an error like so:

```
Traceback (most recent call last):
  File "<<location of EAF>>emacs-application-framework/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "<<location of EAF>>emacs-application-framework/eaf.py", line 373, in send_key_sequence
    self.buffer_dict[buffer_id].fake_key_sequence(event_string)
  File "<<location of EAF>>emacs-application-framework/core/buffer.py", line 332, in fake_key_sequence
    QApplication.sendEvent(widget, QKeyEvent(QEvent.KeyPress, qt_key_dict[last_key], modifiers, last_key))
KeyError: 'backspace>'
```
It appears that some python code is expecting the format `C-<backspace>` rather than `<C-backspace>` which is returned by `key-description`.

I have included a fix/workaround for keys described with angles:
```
(defun eaf-send-key-sequence-angled ()
      (interactive)
      (eaf-call-async "send_key_sequence" eaf--buffer-id (let* ((key-seq (key-description (this-command-keys-vector)))
								(split (split-string (substring key-seq 1 (- (length key-seq) 1)) "-")))
							   (setf (nth (- (length split) 1) split)
								 (format "<%s>" (car (last split))))
							   (mapconcat #'identity split "-"))))
```
Binding those keys to this function then makes the python code happy. It also allows keys like `C-S-<backspace>`.

**Comment by manateelazycat** [comment]
I just test

```
(defun eaf-send-ctrl-backspace-sequence ()
  "Directly send Ctrl-Backspace key sequence to EAF Python side."
  (interactive)
  (eaf-call-async "send_key_sequence" eaf--buffer-id "C-<backspace>"))
```

Works fine.

I don't understand why your code can't work, can you give me your code for example?

**Comment by piknik** [comment]
Correct, that function works fine. Now change it to this:
```
(defun eaf-send-ctrl-backspace-sequence ()
      "Directly send Ctrl-Backspace key sequence to EAF Python side."
      (interactive)
      (eaf-call-async "send_key_sequence" eaf--buffer-id "<C-backspace>"))
```
Notice the sent key sequence is now `<C-backspace>`. It will crash with the error I've provided.

You may be thinking, why make the keybindings in that format? Because emacs outputs this format:
```
(key-description (kbd "C-<backspace>"))
=> "<C-backspace>"
```
This is the behavior in `eaf-send-key-sequence`:
```
(defun eaf-send-key-sequence ()
  "Directly send key sequence to EAF Python side."
  (interactive)
  (eaf-call-async "send_key_sequence" eaf--buffer-id (key-description (this-command-keys-vector))))
```
So I cannot make a keybinding like:
```
(eaf-bind-key send-key-sequence "C-<backspace>" eaf-browser-keybinding)
```

**Comment by manateelazycat** [comment]
> Correct, that function works fine. Now change it to this:
> 
> ```
> (defun eaf-send-ctrl-backspace-sequence ()
>       "Directly send Ctrl-Backspace key sequence to EAF Python side."
>       (interactive)
>       (eaf-call-async "send_key_sequence" eaf--buffer-id "<C-backspace>"))
> ```
> 
> Notice the sent key sequence is now `<C-backspace>`. It will crash with the error I've provided.
> 
> You may be thinking, why make the keybindings in that format? Because emacs outputs this format:
> 
> ```
> (key-description (kbd "C-<backspace>"))
> => "<C-backspace>"
> ```
> 
> This is the behavior in `eaf-send-key-sequence`:
> 
> ```
> (defun eaf-send-key-sequence ()
>   "Directly send key sequence to EAF Python side."
>   (interactive)
>   (eaf-call-async "send_key_sequence" eaf--buffer-id (key-description (this-command-keys-vector))))
> ```
> 
> So I cannot make a keybinding like:
> 
> ```
> (eaf-bind-key eaf-send-key-sequence "C-<backspace>" eaf-browser-keybinding)
> ```

I have test, my Emacs-28.0.50 output ```(key-description (kbd "C-<backspace>"))``` with ```C-<backspace>```

**Comment by manateelazycat** [comment]
@piknik close issue, please reopen it if still have problem
