### ISSUE TITLE
EAF unable to start browser under Anaconda

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#629]
**Describe the bug**
When I'm under Anaconda3 `(base)` virtualenv environment, start Emacs. the EAF is unabled to start browser, and got error in `*eaf*` buffer.
```
Traceback (most recent call last):
  File "/home/stardiviner/Code/Emacs/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed # noqa
  File "/home/stardiviner/Code/Emacs/emacs-application-framework/app/browser/buffer.py", line 25, in <module>
    from core.browser import BrowserBuffer
  File "/home/stardiviner/Code/Emacs/emacs-application-framework/core/browser.py", line 25, in <module>
    from PyQt5.QtNetwork import QNetworkCookie
ImportError: /usr/lib/libgssapi_krb5.so.2: undefined symbol: k5_cc_store_primary_cred, version krb5_3_MIT

Process *eaf* exited abnormally with code 1
```

When I `conda deactivate`, using system Python instead, then EAF can open browser correctly.

(P.S. I remember I upgraded Anaconda a few days ago, maybe related)

**To Reproduce**
I'm on main branch, and using latest commit `503fed8`. Open image with eaf or open `eaf-open-browser` both failed.

**Versions (please complete the following info):**
 - Distro and DE/WM: KDE/Plasma
 - Versions of Dependencies:
 - M-x emacs-version: `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-04-12`

**Comment by stardiviner** [comment]
Related issue with https://github.com/MatthewZMD/.emacs.d/issues/40

**Comment by manateelazycat** [comment]
The error is clear, "The error is clear "/usr/lib/libgssapi_krb5.so.2: undefined symbol: k5_cc_store_primary_cred, version krb5_3_MIT"

libgssapi_krb5.so.2 have not include symbol k5_cc_store_primary_cred, version krb5_3_MIT, I think you need upgrade package version that include file libgssapi_krb5.so.2, it's a bug of your system, not bug of EAF.
