### ISSUE TITLE
Multiple major issues with `install-eaf.sh`

### ISSUE THREAD

**Issue by lebensterben** [manateelazycat/emacs-application-framework#631]
https://github.com/manateelazycat/emacs-application-framework/blob/b21efedaf78a2c41c36932c92884d930448b0516/install-eaf.sh#L1

- `/bin` is not standard PATH according to Linux Filesystem Specification.
- `bash` is not installed on some systems.
- One should always use `#!/usr/bin/env sh`

---

https://github.com/manateelazycat/emacs-application-framework/blob/b21efedaf78a2c41c36932c92884d930448b0516/install-eaf.sh#L5-L7

Array syntax is not available in POSIX shell. On system that `bash` or `zsh` is aliased to `sh`, this works. But on system with `dash`, this will not.

The solution is to store them in a string. And shell word split would separate them.

---

https://github.com/manateelazycat/emacs-application-framework/blob/b21efedaf78a2c41c36932c92884d930448b0516/install-eaf.sh#L10
https://github.com/manateelazycat/emacs-application-framework/blob/b21efedaf78a2c41c36932c92884d930448b0516/install-eaf.sh#L19
https://github.com/manateelazycat/emacs-application-framework/blob/b21efedaf78a2c41c36932c92884d930448b0516/install-eaf.sh#L28
https://github.com/manateelazycat/emacs-application-framework/blob/b21efedaf78a2c41c36932c92884d930448b0516/install-eaf.sh#L47
https://github.com/manateelazycat/emacs-application-framework/blob/b21efedaf78a2c41c36932c92884d930448b0516/install-eaf.sh#L49

- This redirection is only valid in bash. In posix shell you should use `COMMAND > /dev/null 2>&1`
- These tests are not canonical. You should use `[ $(command -v PROGRAM) ]`.

---

A more serious issue is, this script uses the existence of package manager to determine the host OS.
This is not robust.

On my system there is `dnf` but it can't install anything. It's a developer tool.

**Comment by MatthewZMD** [comment]
Thanks for the report, the install script indeed needs some cleanup and improvement. It wasn't too long ago for it to be created, and the main goal was to "make it work" first.

Perhaps you could contribute by sending us a patch to improve this script!

**Comment by manateelazycat** [comment]
@lebensterben Can you give me some PR to fix this issue directly ? Thanks.
