### ISSUE TITLE
On Ubuntu, reparenting does not work well

### ISSUE THREAD

**Issue by dalanicolai** [manateelazycat/emacs-application-framework#632]
I experience two different problems with EAF on Ubuntu 20.10, one problem occurs in vanilla Emacs and the other problem occurs in Spacemacs. I am using EAF on Fedora 34 also, without any problem.

In this bug report I will describe the issue in Spacemacs. In a subsequent issue I will describe the issue in vanilla Emacs.

**Describe the bug**
In Spacemacs when I open the eaf browser with `M-x eaf-open-browser` then the browser opens in a separate window, i.e. the window is not embedded within Emacs. So when I select that window then the keybindings are not working, on the other hand when I select Emacs, then the keybindings do control the browser in the separate window correctly. Also the browser window is listed as a separate window in the Gnome window switcher (Alt-tab). Here follows a screenshot.

![image](https://user-images.githubusercontent.com/18429791/115359632-2b2b1000-a1bf-11eb-9607-4f3db0974382.png)

It might be related that the \*eaf\* buffer shows the message:
Qt: Session management error: Could not open network socket
![image](https://user-images.githubusercontent.com/18429791/115360210-b73d3780-a1bf-11eb-9826-e42c80f6e965.png)

**To Reproduce**
Well it requires Spacemacs, but just install eaf with the [eaf-layer](https://develop.spacemacs.org/layers/+tools/eaf/README.html) and then open the browser with `M-x eaf-open-browser`

**Expected behavior**
The window is embedded in Emacs

**Versions (please complete the following info):**
Ubuntu 20.10 with Gnome 3.38.3 (same behavior on X11 and Wayland)
 - Versions of Dependencies: newest versions available in Ubuntu default repo (let me know if you would like more specific info)
 - Emacs version 28.0.50

**Screenshots**
Attached above

**Comment by MatthewZMD** [comment]
@manateelazycat are you using ubuntu right now? can you take a look?

**Comment by manateelazycat** [comment]
EAF need xwayland install to embed window

**Comment by dalanicolai** [comment]
@manateelazycat I have xwayland installed. And b.t.w., the problem also occurs on X11 (I guess xwayland is not required there).

**Comment by manateelazycat** [comment]
Can you test with emacs -Q ?

**Comment by dalanicolai** [comment]
Testing with emacs -Q is quite some work, however I have a vanilla installation where I have only enabled the melpa repo, so then when installing all eaf .el dependencies from melpa using `list-packages`, en doing a fresh git clone of emacs-application-framework (and running install-eaf.sh), the reparenting issue persists. The message in the *eaf* buffer reads:

```EAF process starting...
Session is not restored, as no data present in session file.
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 643, resource id: -1935154528, major code: 7 (ReparentWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 875, resource id: -1935154528, major code: 7 (ReparentWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1335, resource id: -1935154528, major code: 7 (ReparentWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1604, resource id: -1935154528, major code: 7 (ReparentWindow), minor code: 0
```

All other eaf buffers are empty (no messages)

**Comment by dalanicolai** [comment]
Ah yes, I have tested again now. On Ubuntu it works correct with Emacs 26.3, but with `pgtk` branch, in x11 as well as in wayland, eaf-browser opens in a separate frame(/gtk window).

In fedora 34 eaf-browser works correctly also with `pgtk` branch. I don't know which packages cause this difference between Fedora and Ubuntu...

**Comment by MatthewZMD** [comment]
At least pgtk branch on native Wayland isn't supported as per #449.

**Comment by manateelazycat** [comment]
@dalanicolai Maybe you need install xwayland in Ubuntu? Since Fedora can works well

**Comment by manateelazycat** [comment]
EAF need XWayland support.

I don't think pgtk Emacs is possible way.
