### ISSUE TITLE
Installation via M-x eaf-install-dependencies does not work well

### ISSUE THREAD

**Issue by dalanicolai** [manateelazycat/emacs-application-framework#633]
I experience two different problems with EAF on Ubuntu 20.10, one problem occurs in vanilla Emacs and the other problem occurs in Spacemacs. I am using EAF on Fedora 34 also, without any problem.

In this bug report I will describe the issue in Emacs. In a previous issue I have described the issue in Spacemacs.

**Describe the bug**
Okay I have found there is not a separate problem (from Spacemacs). I have just found out that installing the required packages using `eaf-install-dependencies` does not work correctly.

Manually running `install-eaf.sh` from the eaf directory installs things correctly.
Note that now I experience the same reparenting issue as I have just reported for Spacemacs in #632

Here follows the report as I was planning to write.

Subject: browser window stays blank
In Emacs when I open the browser with `M-x eaf-open-browser` then the browser does not find any webpage, but it stays blank.

It might be related to the following message that is shown in the \*epc\* buffer:
![image](https://user-images.githubusercontent.com/18429791/115363560-dc7f7500-a1c2-11eb-876f-2a81e9b7211e.png)

**To Reproduce**
Install eaf according to eaf installation instructions, and open the browser.

**Expected behavior**
Everything works fine

**Versions (please complete the following info):**
Ubuntu 20.10 with Gnome 3.38.3
 - Versions of Dependencies: newest versions available in Ubuntu default repo (let me know if you would like more specific info)
 - Emacs version 28.0.50

**Screenshots**
Irrelevant

**Additional context**
While creating this issue I realized that I am on Wayland, I will check the behavior on X11

**Additional context**

**Comment by MatthewZMD** [comment]
Are you reporting two different issues here? I think I'm a bit confused.

> Okay I have found there is not a separate problem (from Spacemacs). I have just found out that installing the required packages using eaf-install-dependencies does not work correctly.
> Manually running install-eaf.sh from the eaf directory installs things correctly.

Is the spacemacs layer using the `eaf-install-dependencies` function from the EAF repo or the one you previously created? There are some updates in the EAF repo.

If it does not work correctly, what is the output?

> In Emacs when I open the browser with M-x eaf-open-browser then the browser does not find any webpage, but it stays blank.
> It might be related to the following message that is shown in the *epc* buffer:

Does this occur regardless of whether you install EAF using the `eaf-install-dependencies` function or manually running the script?

**Comment by dalanicolai** [comment]
Ah okay, when using `eaf-install-dependencies` then npm is run as root:
```
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
```

I guess that causes the problem.

**Comment by dalanicolai** [comment]
Sorry, I just wanted to emphasize that I had two different problems, one when using vanilla Emacs, the other when using Spacemacs. But then, while I was creating the bug report, I found out that when I ran the `install-eaf.sh` manually, things installed correctly.

But subsequently I experienced the same reparenting problem of #632 also in vanilla Emacs.

**Comment by manateelazycat** [comment]
Close issue since install-eaf.sh works.

**Comment by dalanicolai** [comment]
Yes install-eaf.sh works, but `eaf-install-dependencies` generally does not because of the sudo. It would be nice if that could be documented (or explain how to get a '/root/package.json').

Thanks for the reply.

**Comment by manateelazycat** [comment]
> Yes install-eaf.sh works, but `eaf-install-dependencies` generally does not because of the sudo. It would be nice if that could be documented (or explain how to get a '/root/package.json').
> 
> Thanks for the reply.

@MatthewZMD Maybe we should remove eaf-install-dependencies command ? install-eaf.sh is enough.

**Comment by MatthewZMD** [comment]
We could find a way to run npm install in the command without sudo

**Comment by dalanicolai** [comment]
I guess you can just remove the `(let ((default-directory "/sudo::"))`. The `apt` and `dnf` commands in `install-eaf.sh` already have a sudo and Emacs will still prompt for the password.
While for the commands `npm` and `pip` with the --user flag the sudo is not required.

**Comment by manateelazycat** [comment]
> I guess you can just remove the `(let ((default-directory "/sudo::"))` from the `eaf-install-dependencies` command. The `apt` and `dnf` commands in `install-eaf.sh` already have a sudo and Emacs will still prompt for the password.
> While for the commands `npm` and `pip` with the --user flag the sudo is not required.

can you send pr？ thanks

**Comment by MatthewZMD** [comment]
Hi @dalanicolai , are you still using EAF and maintain the install script in the spacemacs layer? 

There are some significant changes to the install-eaf script, changing from shell to python is the first one, please have a look when you have time. Thanks!

**Comment by dalanicolai** [comment]
@manateelazycat Thanks, for the notification. I have been busy with some other stuff, but I will have a look at it tomorrow then...
