### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by afidegnum** [manateelazycat/emacs-application-framework#64]
i am having hard time installing this package into emacs 26, any guidance?

**Comment by MatthewZMD** [comment]
Are you using Linux?

**Comment by afidegnum** [comment]
yes, i m using Ubuntu 18,  i managed to installed via pip3 but when i tried to launch the browser, it automatically exits, i think there is a Qt compatibility issue

**Comment by MatthewZMD** [comment]
What does it say in the `*eaf*` buffer?

FYI you might want to check out how I [configure](https://github.com/MatthewZMD/.emacs.d#emacs-application-framework) EAF to work with my Lubuntu system. According to Lazycat this project technically is still being maintained but he wasn't able to access a Linux computer for a while to make more changes.

**Comment by afidegnum** [comment]
Thanks, it works

**Comment by MatthewZMD** [comment]
Great, this issue can be closed now.

**Comment by afidegnum** [comment]
Please one last question, what's the installation procedure to run this application on arch-linux?

**Comment by MatthewZMD** [comment]
I haven't tried it on arch, but what's the difference?

**Comment by wvxvw** [comment]
GStreamer used in latest Arch Linux is 1.16, but it seems like you programed against some other version. GStreamer I have installed has `video/x-h264` plugin, but when I try to play an `h.264` encoded mp4, I'm getting an error telling me that GStreamer is missing a plugin (and nothing plays).

Web-browser crashes w/o any more messages. I don't even know what binary it runs, so core-dump is useless to me.

The only application that manages to display something is the PDF viewer, but the key bindings don't work in the buffer displaying it.

**Comment by MatthewZMD** [comment]
@manateelazycat any ideas on how this should be approached?

**Comment by manateelazycat** [comment]
I have not time on eaf recently

I will fix all issue on 2019-10

sorry for that

**Comment by manateelazycat** [comment]
I have not time on eaf recently

I will fix all issue on 2019-10

sorry for that
