### ISSUE TITLE
get_selection_text not available in Emacs

### ISSUE THREAD

**Issue by dalanicolai** [manateelazycat/emacs-application-framework#642]
**Describe the bug**
In the `buffer.py` file I find a function `get_selection_text` with the `@interactive` decorator, However this function is not available in Emacs (I am using eaf verision of 15th of april, but was unable to update, see #641).
However, I expect that this issue will probably still exist after the update

**To Reproduce**
Try to find this `get_selection_text` function from Emacs elisp

**Expected behavior**
Maybe I understand it wrong, but I expect this function to be available in Emacs lisp

**Versions (please complete the following info):**
 - Fedora wiht KDE on Wayland
 - M-x emacs-version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.25, cairo version 1.16.0) of 2021-02-18 [2 times]

**Comment by MatthewZMD** [comment]
`get_selection_text` is an obsolete function, it is not used by the EAF anymore, and it is merely a typo to have `@interactive` decorator on top if it.

However, if you do want to use it, or use some other function, please note that it is not a function available by default from Emacs Lisp, it is a Python function that has an `@interacitive` decorator, which means you *can* bind it to a keybinding, which we may or may not have done it for you already. You simply need to do:
```
(eaf-bind-key get_selection_text "C-a" eaf-browser-keybinding)
```

Which, if you try it, will not do anything by default. However, you can change the function from 
```python
@interactive
    def get_selection_text(self):
        ''' Get the selected text.'''
        return self.execute_js(self.get_selection_text_js)
```
to
```python
@interactive
def get_selection_text(self):
    ''' Get the selected text.'''
    message_to_emacs(self.execute_js(self.get_selection_text_js))
```
with the same keybinding. Once you select a range of text in the EAF Browser, it will display the selected text in the minibuffer.
