### ISSUE TITLE
EAF org preview和markdown preview报错

### ISSUE THREAD

**Issue by quarkquartet** [manateelazycat/emacs-application-framework#647]
我用的是emacs-mac 27.2，macOS 10.15.7， 配置是doom。
成功安装eaf，能够正常使用eaf-pdf。
使用`eaf-open`打开org和md，会正常生成html，但是无法打开，弹出"python quit unexpectedly."
![image](https://user-images.githubusercontent.com/26316540/116615847-e2cfc880-a909-11eb-95e0-df9f2adcc758.png)
图里是org。如果开markdown结果是一样的。
安装过程是手动调用的`install-eaf-mac.sh`，没有报错。

**Comment by MatthewZMD** [comment]
`*eaf*`有什么信息？

**Comment by manateelazycat** [comment]
EAF requires the accessibility to Camera and Bluetooth in some scenes, otherwise it will crash. Open the System Preferences application in macOS, in Security & Privacy panel, allow Emacs.app to use bluetooth. If you want to use the camera, open the Emacs.app package, and then add “Privacy - Camera Usage Description” key to Info.plist file. Google requires bluetooth access when logging, so make sure your Emacs have access to the bluetooth before logging into Google Account.

**Comment by quarkquartet** [comment]
> `*eaf*`有什么信息？

/bin/sh: ldd: command not found
EAF process starting...
Traceback (most recent call last):
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/isaac/.emacs.d/.local/straight/build-27.2/eaf/eaf.py", line 133, in new_buffer
    self.create_app(buffer_id, str(url), "app.{0}.buffer".format(str(app_name)), str(arguments))
  File "/Users/isaac/.emacs.d/.local/straight/build-27.2/eaf/eaf.py", line 180, in create_app
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/Users/isaac/.emacs.d/.local/straight/build-27.2/eaf/eaf.py", line 194, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, eaf_config_dir, arguments, self.emacs_var_dict, module_path)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/app/org-previewer/buffer.py", line 29, in __init__
    BrowserBuffer.__init__(self, buffer_id, url, config_dir, arguments, emacs_var_dict, module_path, False)
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/browser.py", line 612, in __init__
    self.add_widget(BrowserView(buffer_id, config_dir))
  File "/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/core/browser.py", line 71, in __init__
    self.dark_mode_js = open(os.path.join(os.path.dirname(os.path.dirname(__file__)),
FileNotFoundError: [Errno 2] No such file or directory: '/Users/isaac/.emacs.d/.local/straight/repos/emacs-application-framework/node_modules/darkreader/darkreader.js'

Process *eaf* abort trap: 6

**Comment by lhpfvs** [comment]
Please try to use eaf-open-browser and see if it works or not. And also try to run `npm install` manually.

**Comment by quarkquartet** [comment]
> Please try to use eaf-open-browser and see if it works or not. And also try to run `npm install` manually.

I tried both. Unfortunately, non of these methods works.

**Comment by quarkquartet** [comment]
> EAF requires the accessibility to Camera and Bluetooth in some scenes, otherwise it will crash. Open the System Preferences application in macOS, in Security & Privacy panel, allow Emacs.app to use bluetooth. If you want to use the camera, open the Emacs.app package, and then add “Privacy - Camera Usage Description” key to Info.plist file. Google requires bluetooth access when logging, so make sure your Emacs have access to the bluetooth before logging into Google Account.

I tried this. But unfortunately it does not work.

**Comment by lhpfvs** [comment]
Please send details of crash report to my email. I will try to find some clues.

**Comment by quarkquartet** [comment]
> Please send details of crash report to my email. I will try to find some clues.

I reinstalled everything again. Now the org-preview is successfully opened. But math formulas are not rendered and displayed.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/26316540/116841827-5a228800-aba8-11eb-953c-909fbd53b22b.png">

Like this. 

`*eaf*` file says:

/bin/sh: ldd: command not found
EAF process starting...
Session is not restored, as no data present in session file.
js: Uncaught SyntaxError: Unexpected token '<'
js: Uncaught SyntaxError: Unexpected token '<'
js: Uncaught SyntaxError: Unexpected token '<'

I really appreciate it for your help. What other information do you need?

**Comment by lhpfvs** [comment]
So the crash is caused by an incomplete installation and the problem has been solved. Rendering math formulas is not a work of EAF, please check your org-html-export function.

**Comment by quarkquartet** [comment]
> So the crash is caused by an incomplete installation and the problem has been solved. Rendering math formulas is not a work of EAF, please check your org-html-export function.

Thanks for the guidance. I will close this issue.
