### ISSUE TITLE
Support synctex?

### ISSUE THREAD

**Issue by quarkquartet** [manateelazycat/emacs-application-framework#648]
I'm using eaf for my latex, with the configurations in the eaf wiki.

Now `C-c C-a` opens the pdf in eaf perfectly. But it seems that there is no designed synctex function. 

Is it possible to include this?

**Comment by manateelazycat** [comment]
I'm not use LaTeX, so I can't help this issue.

**Comment by manateelazycat** [comment]
I haven't time on feature that I don't use.

Sorry to close issue, but PR always are welcome.
