### ISSUE TITLE
What is fitz?

### ISSUE THREAD

**Issue by wvxvw** [manateelazycat/emacs-application-framework#65]
I'm missing this dependency, but looking it up on PyPI gives seemingly unrelated results. What packaged do I need to install for this?

As an aside, it would've been great if your `setup.py` was an actual setup script. At least mention your dependencies there...

BTW. I also had to

```
pacman -S python-pyqtwebengine qutebrowser
```

to get some of the missing stuff.

**Comment by MatthewZMD** [comment]
I have not encountered this, can you provide more information on where did you see fitz?

**Comment by wvxvw** [comment]
I figured it out later: it's coming from PyMuPDF, essentially, it's what their package is called. Beats me what the connection between two names is...

Though I still cannot get any of this to work :) Qt is a very unstable and unpredictable thing... every minor version inconsistency breaks something up.

Another problem: GStreamer dependency. My OS must be using a different version of it than the one used by the project, so, no sounds, no video for me...

**Comment by manateelazycat** [comment]
Fitz provide by python-pymupdf.

Please commit new issue if you any new problem, thanks for report.
