### ISSUE TITLE
Title: EAF  Browser And Chrome Extensions

### ISSUE THREAD

**Issue by tvraman** [manateelazycat/emacs-application-framework#652]
Description: Using Chrome Extensions With EAF  Browser
Is this possible? Was looking to find where the EAF  browser kept its
extensions directory so I could add Chrome Extensions to it.
More Specifically, I'm using emacspeak  to provide spoken output
(https://github.com/tvraman/emacspeak)and would like to have the
ChromeVox   extension to provide speech in the browser window. Is this
above possible?

**Comment by MatthewZMD** [comment]
The EAF Browser is based on the QtWebEngine, which unfortunately does not support Chrome Extensions at the moment. https://stackoverflow.com/questions/46037625/how-to-load-chrome-extensions-in-qtwebengine
