### ISSUE TITLE
EAF Spreadsheet Integration

### ISSUE THREAD

**Issue by larebsyed** [manateelazycat/emacs-application-framework#653]
**Is your feature request related to a problem? Please describe.**
Emacs lacks a good spreadsheet program, I think in order to make spreadsheet editing a part of Emacs workflow we will need to use an external program and EAF can do that I think

**Describe the solution you'd like**
Probably we can use OnlyOffice integration or some other tool to get the functionality

**Describe alternatives you've considered**
Alternatives is CSV mode and SES Mode but both are below par in spreadsheet capabilities

**Additional context**

**Comment by MatthewZMD** [comment]
Great suggestion! Noted.

**Comment by wineee** [comment]
Maybe [Luckysheet](https://github.com/mengshukeji/Luckysheet) is a good choice

**Comment by larebsyed** [comment]
There is also onlyoffice.com which also has a standalone app.

**Comment by manateelazycat** [comment]
Spreadsheet is complicated application.

Just use Excel if you need powerful spreadsheet tools, otherwise Org-mode's table is good enough.
