### ISSUE TITLE
No key bindings are working. Everything else is perfect.

### ISSUE THREAD

**Issue by AdamAtGradient** [manateelazycat/emacs-application-framework#657]
**Description**
EAF seems to work fine except that none of the key bindings appear to be active and I'm not sure how to proceed in diagnosing further.
Let me also say, this is incredible project that I will use and hopefully contribute to. I'm always annoyed by having to leave Emacs to test a browser or chose different music to listen to.

**My setup**
I'm using the straight package manager with use-package. It is all well configured and works with all other packages. My config is:
``` emacs-lisp
(use-package eaf
  :straight (eaf :type git
                 :host github
                 :repo "manateelazycat/emacs-application-framework"
                 :files ("*.el" "*.py" "core" "app"))
  :init
  (use-package epc :defer t :ensure t)
  (use-package ctable :defer t :ensure t)
  (use-package deferred :defer t :ensure t)
  (use-package s :defer t :ensure t)
  :custom
  (eaf-browser-continue-where-left-off t)
  :config
  (eaf-setq eaf-browser-enable-adblocker "true")
  (eaf-bind-key scroll_up "C-n" eaf-pdf-viewer-keybinding)
  (eaf-bind-key scroll_down "C-p" eaf-pdf-viewer-keybinding)
  (eaf-bind-key take_photo "p" eaf-camera-keybinding)
  ;; unbind M-q, see more in the Wiki
  (eaf-bind-key nil "M-q" eaf-browser-keybinding))
```
Everything builds fine. I've run `install-eaf.sh` both in my conda (anaconda) python environment and on the system's python. Same results.

I do run a locally built version of a fairly-up-to-date version off of master. I do this because I keep getting broken by the PPA. I am willing to repeat my tests (and get my configuration working) on an earlier/more specific version of Emacs.

I'm on a fully up-to-date Ubuntu 20.04 system.

**Expected behavior**
I expected at least `C-h m` to work. AFAICT no keys make it through the EAF buffer so the bindings don't work. I have to use the mouse to go another buffer to get keys working. Any time I switch back to the EAF buffer, my keys are completely captive by the EAF process (nothing seems to get to Emacs).

**Versions:**
 - Ubuntu 20.04 running Xfce4 - fully upgraded
 - Emacs version: * master 28bed069a7 [origin/master: behind 25] * lib/Makefile.in (maintainer-clean): Fully ignore rmdir errors.

**More**
Again, this has never worked - I'm just getting it running now. Even popping up a png locks me out. My configuration is pretty dead simple (the basic config can be found at my [emacs-config repository](https://github.com/Atman50/emacs-config).

**Comment by manateelazycat** [comment]
EAF confirms that the desktop environment or window manager you can work includes: KDE, Gnome2, Gnome3, Mate, Xfce, LXDE, Sway, i3, QTile, Xpra, EXWM.

We suspect there are some issues with how all the Window Managers implement their x11 protocols.

One workaround is to name of command wmctrl -m to the elisp list eaf-wm-focus-fix-wms.

**Comment by manateelazycat** [comment]
Run command ```wmctrl -m``` in your system, what output is ?

**Comment by AdamAtGradient** [comment]
``` sh
$)wmctrl -m
Name: Xfwm4
Class: xfwm4
PID: 2353
Window manager's "showing the desktop" mode: N/A
$
```

**Comment by manateelazycat** [comment]
git pull newest version and try again

**Comment by AdamAtGradient** [comment]
That did the trick!!!! Awesome.

Notes: I had to delete two files before I could pull:
```
rm package.json app/music-player/package-lock.json 
```
and the first time I ran the ./install-eaf.sh script, I encountered an error - I followed the output instructions and did:
```
npm install --save @fortawesome/fontawesome-svg-core
```
And re-ran the install. Second time's the charm.

All the bindings now seem to work. Great job. Thanks!

**Comment by AdamAtGradient** [comment]
Things are still working wonderfully. This ticket can be closed. I'm not sure if I should close it or not.
Thanks so much for your help and this great package.
