### ISSUE TITLE
Support for Wayland

### ISSUE THREAD

**Issue by benquike** [manateelazycat/emacs-application-framework#66]
Hi,

I have tried it on Wayland. It does not work.
Is there any plan to support wayland?

**Comment by manateelazycat** [comment]
no plan

i dont know wayland support tech like x11 reparent

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/commit/af392dc299c9ab3a1e000598b471ab540c9603f5

I haven't used the pgtk version of Emacs. The above patch is a patch that I wrote blindly based on the EAF principle.

This patch means that when EAF finds that Emacs is in the Wayland native (also known as the pgtk version) environment, it will use the same strategy as macOS: "Show the EAF window when Emacs is focused, and hide the EAF window when Emacs loses focus. "Although it is not as perfect as multi-process reparent in X11 and XWayland environments, it should be no problem for daily use.

Welcome to try it, and welcome feedback.
