### ISSUE TITLE
EAF support emacspeak

### ISSUE THREAD

**Issue by tvraman** [manateelazycat/emacs-application-framework#660]
---
name: EAF Feature request
about: Suggest an idea for the Emacs Application Framework
title:Howto: Send current line back to Emacs in Caret Browsing  Mode 
labels: ''
assignees: ''
Hi,

I'm trying to hook up EAF to emacspeak (https://github.com/tvraman/emacspeak)
and as a baby step, I wanted to extend caret-browsing mode to speak the current line. What part of the code do I extend to achieve this --- I'm looking for pointers as to how to do this.

What I'd like:

1. As I navigate using caret-browsing mode, have the python side send over HTML (minus JS)  (not plain text) to the emacs side where I can render it via speech. This is just a baby step toward eventually making EAF talk intelligently via Emacspeak.

3. Also, how is M-D select_text supposed to work? When invoked, it produces a minibuffer prompt, but it's  unclear as to what type of input it expects. I looked on the python side (core/webengine.py) and the corresponding python function  doesn't   tell me much about what it was expecting from the emacs side.

---

**Comment by MatthewZMD** [comment]
> 1\. As I navigate using caret-browsing mode, have the python side send over HTML (minus JS) (not plain text) to the emacs side where I can render it via speech. This is just a baby step toward eventually making EAF talk intelligently via Emacspeak.

To get things working quickly, you could rewrite this currently-useless-piece-of-code:
```
    @interactive
    def get_selection_text(self):
        ''' Get the selected text.'''
        return self.execute_js(self.get_selection_text_js)
```
Have a look at the `core/js/get_selection_text.js` file, it should be self explanatory. Change it to return the HTML DOM of your selection, return it back to ELisp as per the Wiki, and continue from here.

> 2\. Also, how is M-D select_text supposed to work? When invoked, it produces a minibuffer prompt, but it's  unclear as to what type of input it expects. I looked on the python side (core/webengine.py) and the corresponding python function  doesn't   tell me much about what it was expecting from the emacs side.

You can try on the current page, it prompts you to enter the vimium key combination marker shown on the webpage, and will highlight the appropriate paragraphs. You can proceed with `M-w` to copy or do anything you'd like to the highlighted text.

Hope this helps.

**Comment by tvraman** [comment]
Matthew Zeng ***@***.***> writes:

This is awesome and exactly what I was looking for, so thanks. One
question: could you explain what you mean by "vimium markers shown on
the page"? Note that I cannot see the screen at all

>     1. As I navigate using caret-browsing mode, have the python side
>     send over HTML (minus JS) (not plain text) to the emacs side where
>     I can render it via speech. This is just a baby step toward
>     eventually making EAF talk intelligently via Emacspeak.
>
> To get things working quickly, you could rewrite this
> currently-useless-piece-of-code:
>
>     @interactive
>     def get_selection_text(self):
>         ''' Get the selected text.'''
>         return self.execute_js(self.get_selection_text_js)
>
> Have a look at the core/js/get_selection_text.js file, it should be
> self explanatory. Change it to return the HTML DOM of your selection,
> return it back to ELisp as per the Wiki, and continue from here.
>
>     2. Also, how is M-D select_text supposed to work? When invoked, it
>     produces a minibuffer prompt, but it's unclear as to what type of
>     input it expects. I looked on the python side (core/webengine.py)
>     and the corresponding python function doesn't tell me much about
>     what it was expecting from the emacs side.
>
> You can try on the current page, it prompts you to enter the vimium
> key combination marker shown on the webpage, and will highlight the
> appropriate paragraphs. You can proceed with M-w to copy or do
> anything you'd like to the highlighted text.
>
> Hope this helps.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 

Thanks,

--Raman
♈ Id: kg:/m/0285kf1  🦮

**Comment by MatthewZMD** [comment]
Does EAF Browser work for you? If it works, then if you press `f` on any page, it will pop up a bunch of markers on the webpage on top of any link. Enter the key will open the corresponding link for you in the browser, this is similar to a Chrome extension called vimium. `M-D` behaves the same way, but instead of opening links, it highlights the corresponding text on the webpage.

**Comment by tvraman** [comment]
Thanks. Yes, eaf browser is working in Emacs  -- but until I write some
code,  I wont hear anything useful:-)


-- 

Thanks,

--Raman
♈ Id: kg:/m/0285kf1  🦮

**Comment by manateelazycat** [comment]
I haven't time on feature that I don't use.

Sorry to close issue, but PR always are welcome.

**Comment by tvraman** [comment]
Not a problem, your original reply gave me some information to work on;
if I make progress I'll send along a PR.

Thank you again for the work on EAF, it's really good work.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by kowsen** [comment]
Based on its release notes, it looks like Emacspeak now supports Emacs Application Framework [as of version 55!](http://emacspeak.sourceforge.net/releases/release-55.html) (released November 2021)
