### ISSUE TITLE
Support trim margins for PDF files

### ISSUE THREAD

**Issue by fountainer** [manateelazycat/emacs-application-framework#662]
**Is your feature request related to a problem? Please describe.**
I often use [pdf-tools](https://github.com/politza/pdf-tools) to trim margins (set slice to bounding box) when reading PDF files because of the small screen of the laptop. pdf-tools is nice but a little bit slow. I tried EAF. However, EAF seems not to provide such functionality. 

**Describe the solution you'd like**
Trim margins (set slice to bounding box) as [pdf-tools](https://github.com/politza/pdf-tools) does.

**Comment by manateelazycat** [comment]
some screenshot？

I'm not understand what you mean

**Comment by manateelazycat** [comment]
EAF PDF will use all width of screen.

I don't understand what you mean.

**Comment by fountainer** [comment]
![Screen Shot 2021-05-20 at 6 47 08 PM copy copy](https://user-images.githubusercontent.com/5546074/118968608-b0f8d180-b99e-11eb-9e0f-ec834e907389.jpg)
The area in the red rectangle is a PDF page, which will be showed in an Emacs buffer. Notice that the area (margins) that is inside of the red rectangle and outside of the green rectangle is quite large and blank.  It's better to only show the area that is inside the green rectangle and "trim"  the margins.

**Comment by manateelazycat** [comment]
can you give me your PDF file for test?

**Comment by fountainer** [comment]
> can you give me your PDF file for test?

The PDF file can be downloaded from [here](https://web.stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf).

**Comment by manateelazycat** [comment]
I found pdf-tools use https://github.com/politza/pdf-tools/blob/c510442ab89c8a9e9881230eeb364f4663f59e76/server/epdfinfo.c#L3269 detect margin of PDF file.

@luhuaei Can you help me support this feature?

Once we can detect white margin of PDF file, then we can trim margin in EAF PDF file.

But we need carefully add this feature, because we have many feature (zoom, rotate, search, annotate etc) depend the coordinate of clip rectangle.

**Comment by luhuaei** [comment]
> I found pdf-tools use https://github.com/politza/pdf-tools/blob/c510442ab89c8a9e9881230eeb364f4663f59e76/server/epdfinfo.c#L3269 detect margin of PDF file.
> 
> @luhuaei Can you help me support this feature?
> 
> Once we can detect white margin of PDF file, then we can trim margin in EAF PDF file.
> 
> But we need carefully add this feature, because we have many feature (zoom, rotate, search, annotate etc) depend the coordinate of clip rectangle.

I think how to add this feature. Unsure whether cause other feature error.

**Comment by manateelazycat** [comment]
> > I found pdf-tools use https://github.com/politza/pdf-tools/blob/c510442ab89c8a9e9881230eeb364f4663f59e76/server/epdfinfo.c#L3269 detect margin of PDF file.
> > @luhuaei Can you help me support this feature?
> > Once we can detect white margin of PDF file, then we can trim margin in EAF PDF file.
> > But we need carefully add this feature, because we have many feature (zoom, rotate, search, annotate etc) depend the coordinate of clip rectangle.
> 
> I think how to add this feature. Unsure whether cause other feature error.

 Maybe we should refactory code before add this future.

**Comment by luhuaei** [comment]
> Once we can detect white margin of PDF file, then we can trim margin in EAF PDF file.
I find the method to detect text area. fitz [page.getTextPage().extractBLOCKS()](https://pymupdf.readthedocs.io/en/latest/textpage.html#TextPage.extractBLOCKS) get the every line coordinate,  can compute the text area.

**Comment by luhuaei** [comment]
#691 Already add trim pdf white margin feature. Enable this feature will cause load page slow when init. I recommend to use other tool trim pdf margin before using EAF open it. Example:

```python

import fitz

def get_tight_margin_rect(page):
    r = None
    page_rawdict = page.getText("rawdict")
    for block in page_rawdict["blocks"]:
        if block["type"] != 0:
            continue

        x0, y0, x1, y1 = block["bbox"]
        if r is None:
            r = fitz.Rect(x0, y0, x1, y1)
            continue
        x0 = min(x0, r.x0)
        y0 = min(y0, r.y0)
        x1 = max(x1, r.x1)
        y1 = max(y1, r.y1)
        r = fitz.Rect(x0, y0, x1, y1)
    return r


def get_doc_tight_margin_rect(document):
    dr = None
    for index, page in enumerate(document):
        r = get_tight_margin_rect(page)
        if r is None:
            continue
        if dr is None:
            dr = r
            continue
        x0 = min(r.x0, dr.x0)
        y0 = min(r.y0, dr.y0)
        x1 = max(r.x1, dr.x1)
        y1 = max(r.y1, dr.y1)
        dr = fitz.Rect(x0, y0, x1, y1)
    return dr

def create_clip_doc(origin, empty, clip, name):
    for index, page in enumerate(origin):
        page.setCropBox(clip)
        page = origin.reload_page(page)
        new_page = empty.newPage(index, page.rect.width, page.rect.height)
        new_page.showPDFpage(fitz.Rect(0, 0, page.rect.width, page.rect.height), origin, index)
    empty.save(name, garbage=3, deflate=True)

if __name__ == "__main__":
    origin = fitz.open("bv_cvxbook.pdf")
    doc = fitz.open()

    clip = get_doc_tight_margin_rect(origin)
    create_clip_doc(origin, doc, clip, "trim_bv_cvxbook.pdf")

```
save above code to one file, eg: `trim_margin.py`, replace `trim_margin.py` to you want to trim margin pdf file name. replace `trim_bv_cvxbook.pdf` to the new file name.

**Comment by fountainer** [comment]
Thanks for your work. Since the option "eaf-pdf-enable-trim-white-margin" is disabled by default because of low speed, is it better to add a function like `eaf-pdf-trim-white-margin`?  I think functions are more flexible than options.

**Comment by luhuaei** [comment]
> Thanks for your work. Since the option "eaf-pdf-enable-trim-white-margin" is disabled by default because of low speed, is it better to add a function like `eaf-pdf-trim-white-margin`? I think functions are more flexible than options.

OK, I change this to interactive.

**Comment by manateelazycat** [comment]
done
