### ISSUE TITLE
M-x  not working in an eaf buffer

### ISSUE THREAD

**Issue by OrionRandD** [manateelazycat/emacs-application-framework#676]
Why "M-x"  does not work in an eaf buffer for me to issue 
commands on that?
I am using Doom-Emacs.
But, even if  I  change to Emacs estate with  C-z
it does not work.
The eaf buffer, just sits there looking at me and nothing happens...

**Comment by manateelazycat** [comment]
emacs -Q test first

**Comment by OrionRandD** [comment]
> emacs -Q test first

"M-x"  works in    emacs -Q
