### ISSUE TITLE
which-key not working in eaf buffers

### ISSUE THREAD

**Issue by OrionRandD** [manateelazycat/emacs-application-framework#677]
I have found that which-key is not working in eaf buffers...
Is that because I am using Doom-Emacs?
But, even if I   C-z  to change to Emacs normal state 
pressing  Space or M-x  gives me nothing  :(

**Comment by manateelazycat** [comment]
emacs -Q test first

**Comment by MatthewZMD** [comment]
Does all other keys work except for these keys?

**Comment by OrionRandD** [comment]
> I have found that which-key is not working in eaf buffers...
> Is that because I am using Doom-Emacs?
> But, even if I C-z to change to Emacs normal state
> pressing Space or M-x gives me nothing :(

Seems to be working now. After I  reinstalled it  :)
