### ISSUE TITLE
Performance loading package

### ISSUE THREAD

**Issue by iris-garcia** [manateelazycat/emacs-application-framework#678]
Probably not a bug and just me doing something wrong but I would love to know why loading this package takes 3.5 seconds of my emacs startup.
```
(use-package eaf
    :straight (eaf :host github
                   :repo "manateelazycat/emacs-application-framework"
                   :branch "master"
                   :files ("eaf-all-the-icons.el" "eaf-org.el" "eaf.el"))
    :defer 10
    :config
    (use-package epc :straight t :defer 10)
    (use-package ctable :straight t :defer 10)
    (use-package deferred :straight t :defer 10)
    (use-package s :straight t :defer 10)
    )
```

Tried to defer without any luck, no matter what I do if I load eaf it takes 3.5 seconds more to start emacs.

Is this normal?

**Comment by MatthewZMD** [comment]
What system are you on? What Emacs version?

**Comment by iris-garcia** [comment]
OS: Arch linux

Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.29, cairo version 1.17.4) of 2021-05-24

CPU: Ryzen 9 3950x
RAM: 64GB

**Comment by MatthewZMD** [comment]
I don't have a lot of ideas at the moment, but you could try
1. use Emacs 27 to ensure it's not something introduced by the latest Emacs master
2. use use-package to ensure it's not something introduced by straight
3. Add to load-path and require manually to check the time

For reference, on a Thinkpad X1C7 with Manjaro KDE, EAF takes 0.8s to load as per `use-package report` with [this config](https://github.com/MatthewZMD/.emacs.d#eaf)
```
eaf                       Configured    2021-05-24 Mon 16:10    0.80
```

**Comment by iris-garcia** [comment]
Thank you @MatthewZMD, I tried the option 3 with load-path and the loading happens in no time.
So I think the problem is in straight, I'll report there.
Thank you for the support and hope it helps others facing the same issue.
