### ISSUE TITLE
how to remove the shadow of  window border 

### ISSUE THREAD

**Issue by bigteech** [manateelazycat/emacs-application-framework#679]
![image](https://user-images.githubusercontent.com/16490211/119467935-95177600-bd78-11eb-932f-13f81719bb5a.png)
this looks  incompatible，how to remove it

**Comment by manateelazycat** [comment]
@lhpfvs Can you help to remove shadow? 

I haven't Mac device for test.

**Comment by bigteech** [comment]
> @lhpfvs Can you help to remove shadow?
> 
> I haven't Mac device for test.

OK
