### ISSUE TITLE
Add support for invidio project

### ISSUE THREAD

**Issue by OrionRandD** [manateelazycat/emacs-application-framework#684]
Hi.
Could you add support for  invidio project?
I use an script in my firefox I have installed inside tampermonkey
called invidio redirect and it beautifully redirects me from any youtube video to
play it through a invidio instance.

https://github.com/iv-org/invidious
https://docs.invidious.io/Extensions.md
https://docs.invidious.io/Extensions.md
https://www.tampermonkey.net/
https://greasyfork.org/en/scripts/370461-invidious-redirect

**Comment by manateelazycat** [comment]
PR are welcome！

I havent time to write feature that I not use

**Comment by OrionRandD** [comment]
> PR are welcome！
> 
> I havent time to write feature that I not use

You can try this one in your firefox browser and have a feeling of this add. It is really good. Especially because it blocks java scripts, blocks all kind of YT adds, etc. Have a look for yourself. I assure you that it pays off...

**Comment by manateelazycat** [comment]
I haven't time on feature that I don't use.

Sorry.
