### ISSUE TITLE
Killing EAF buffers sometimes crashes the eaf process

### ISSUE THREAD

**Issue by KjartanOli** [manateelazycat/emacs-application-framework#685]
```
Traceback (most recent call last):
  File "/home/kjartan/.emacs.d/elpa/28.0/develop/eaf-20210526.1421/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/kjartan/.emacs.d/elpa/28.0/develop/eaf-20210526.1421/eaf.py", line 342, in execute_function
    if buffer_id in self.buffer_dict:
TypeError: unhashable type: 'list'

Process *eaf* aborted
```
**Describe the bug**
Occasionaly, when I kill a eaf buffer the eaf process crashes with the above error.

**To Reproduce**
I haven't found a clear way to reproduce this issue. It seems to happen at random.

**Expected behavior**
Killing a eaf buffer does not crash the eaf proccess

**Versions (please complete the following info):**
 - Distro and DE/WM: Debian bullseye with EXWM as my window manager
 - Versions of Dependencies:
     Python 3.9.2
     NodeJs 15.14.0
     Other dependencies should have been installed by the `install-dependencies.sh` script provided by eaf.
 - M-x emacs-version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw scroll bars) of 2021-05-26
 This was also an issue in Emacs 27, I just updated.

**Comment by manateelazycat** [comment]
Close issue, please reopen this if have stable reproduction step.

**Comment by Elilif** [comment]
@manateelazycat  after run `install-dependencies.sh`, I reproduce this error in emacs -q with the use-package config wrote in README. 
```
EAF process starting...
Session is not restored, as no data present in session file.
js: Deprecation notice: Use specific `@ember/*` imports instead of `ember` (deprecated since Discourse 2.4.0) (removal in Discourse 2.5.0)
Traceback (most recent call last):
  File "/home/eli/.emacs.d/private/emacs-application-framework/core/utils.py", line 60, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/eli/.emacs.d/private/emacs-application-framework/eaf.py", line 351, in execute_function
    if buffer_id in self.buffer_dict:
TypeError: unhashable type: 'list'

Process *eaf* aborted (core dumped)
EAF process starting...
Session is not restored, as no data present in session file.
js: Deprecation notice: Use specific `@ember/*` imports instead of `ember` (deprecated since Discourse 2.4.0) (removal in Discourse 2.5.0)
js: Deprecation notice: Use specific `@ember/*` imports instead of `ember` (deprecated since Discourse 2.4.0) (removal in Discourse 2.5.0)
js: Deprecation notice: Use specific `@ember/*` imports instead of `ember` (deprecated since Discourse 2.4.0) (removal in Discourse 2.5.0)
Traceback (most recent call last):
  File "/home/eli/.emacs.d/private/emacs-application-framework/core/utils.py", line 60, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/eli/.emacs.d/private/emacs-application-framework/eaf.py", line 351, in execute_function
    if buffer_id in self.buffer_dict:
TypeError: unhashable type: 'list'

Process *eaf* aborted (core dumped)
```
**Versions (please complete the following info):**
 - Distro and DE/WM: Arch with i3wm
 - Versions of Dependencies: 
   Python:3.9.5
   Nodejs:16.5.0
 - M-x emacs-version: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-27
 - Commit: 48fad6ce894a31491a69334e0dd89f06a0bec208

**Comment by MatthewZMD** [comment]
For anyone who could reproduce this error, could you please add `print(buffer_id)` before line 351 `if buffer_id in self.buffer_dict:` to see what it gives?
