### ISSUE TITLE
Dependency Installation: process.stdout.ClearLine is not a function

### ISSUE THREAD

**Issue by swapneils** [manateelazycat/emacs-application-framework#693]
I installed the repository via the git command in the README.md, with "~" modified to my .emacs.d path, and then ran M-x eaf-install-dependences. At first it seemed to work fine, but at the end of the *Async Shell Command* buffer there was an error saying (Copy-pasted, with directory information removed):

[something]\.emacs.d\elpa\eaf-20210604.112\install-eaf-win32.js:43
    process.stdout.clearLine();
                   ^

TypeError: process.stdout.clearLine is not a function
    at printProgress ([something]\.emacs.d\elpa\eaf-20210604.112\install-eaf-win32.js:43:20)
    at IncomingMessage.<anonymous> ([something]\.emacs.d\elpa\eaf-20210604.112\install-eaf-win32.js:84:25)
    at IncomingMessage.emit (events.js:314:20)
    at IncomingMessage.Readable.read (_stream_readable.js:513:10)
    at flow (_stream_readable.js:986:34)
    at resume_ (_stream_readable.js:967:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Running eaf-install-dependencies again produced the same result.

The only anomaly I noticed during installation is that for some reason eaf is in .emacs.d/elpa instead of .emacs.d/site-lisp (which doesn't exist yet, to be clear), but [I'm assuming this was an intended consequence of the package installation, so] I'm not sure how that would cause the problem.

I am on a Windows machine with the latest version of emacs.

UPDATE: Forgot to mention, when I tried the eaf-open-browser command it gave no response for about 5-10 min, then opened a buffer titled *eaf* saying it could not find python on my machine. Running a normal python shell works fine, however.

**Comment by manateelazycat** [comment]
@yqu212 can you help to fix this? thanks

**Comment by yqu212** [comment]
This is probably not a bug. From the above message, I think there is a problem with the environment(i.e.，Emacs home environment，js，python).  @swapneils

**Comment by swapneils** [comment]
> This is probably not a bug. From the above message, I think there is a problem with the environment(i.e.，Emacs home environment，js，python). @swapneils

I looked into it again, and while it does have to do with the environment I think it actually _is_ a bug: according to the error message I got from open-eaf-demo, at least part of the problem seems to be that instead of python.exe, EAF was trying to open **python3.exe, a file that doesn't exist on Windows** versions of Python, [according](https://stackoverflow.com/questions/34212036/python-3-installation-on-windows-running-from-command-line) [to](https://stackoverflow.com/questions/48355319/cmd-windows-python-command-works-but-python3-doesnt-although-my-python-ver) [StackOverFlow](https://stackoverflow.com/questions/40914108/bash-python3-command-not-found-windows-discord-py). 

After using mklink /H to create a fake python3.exe in the Python folder, open-eaf-demo works fine, though I haven't tested more advanced functions yet.

I also haven't tested or found a quick-fix for the issue with process.stdout.clearLine(); it's node.js, which I'm not familiar with, and I only found [one](https://stackoverflow.com/questions/34570452/node-js-stdout-clearline-and-cursorto-functions) SO question mentioning this error, though it's _possible_ this one has to do with Windows being different as well.

**Comment by yqu212** [comment]
In my experience, the problem is indeed that the dependencies are not installed correctly. Please make sure that python3 is on the top of the Path environment variable. Install each dependency manually and correctly. Please read readme.md. If you can install all dependencies correctly, most applications will work fine. At that point, we'll discuss the bug you mentioned above.

Also, qtwebengine cannot play mp4 due to legal issues. This limitation is present under both Windows and mac. You can watch YouTube videos, but don't expect every site to be able to do so.

Translated with www.DeepL.com/Translator (free version)

**Comment by MatthewZMD** [comment]
I think it's about time to omit the `3` in `python3` whenever it's creating a problem like this, since Python2 had been deprecated for more than a year and Python3 is the standard.
