### ISSUE TITLE
Doesn't work when open a remote file

### ISSUE THREAD

**Issue by ssskkkky** [manateelazycat/emacs-application-framework#695]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.
- 
RuntimeError: cannot open /scp:user@hostname:/public/home/user/file.pdf: No such file or directory

**Describe the bug**
It doesn't work when open a remote file through ssh and tramp

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.
Just try to open a remote file through ssh and tramp

**Expected behavior**
I would like it works like that I'm reading a local file just as the tramp usually does

**Versions (please complete the following info):**
 - Distro and DE/WM:ubuntu gnome
 - Versions of Dependencies:
 - M-x emacs-version: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian

**Comment by manateelazycat** [comment]
no，EAF not support tramp
