### ISSUE TITLE
pdf annotation cannot be deleted

### ISSUE THREAD

**Issue by Jousimies** [manateelazycat/emacs-application-framework#696]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.
EAF process starting...
Session restored:  b332-ddea-45c1-3fba-43ec-e7c0-6f2c app.pdf-viewer.buffer /home/dn/.emacs.d/eaf/session.json
Traceback (most recent call last):
  File "/home/dn/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 346, in execute_function
    buffer.execute_function(function_name)
  File "/home/dn/.emacs.d/site-lisp/emacs-application-framework/core/buffer.py", line 272, in execute_function
    getattr(self, function_name)()
  File "/home/dn/.emacs.d/site-lisp/emacs-application-framework/app/pdf-viewer/buffer.py", line 178, in add_annot_strikeout_or_delete_annot
    self.buffer_widget.annot_handler("delete")
  File "/home/dn/.emacs.d/site-lisp/emacs-application-framework/app/pdf-viewer/buffer.py", line 1294, in annot_handler
    if annot.parent:
AttributeError: 'NoneType' object has no attribute 'parent'
**Describe the bug**
I cannot delete annotations which were added with eaf. When I execute eaf-proxy-add_annot_strikeout_or_delete_annot , the message buffer echo: [EAF/pdf-viewer] Cannot execute function: add_annot_strikeout_or_delete_annot (b332-ddea-45c1-3fba-43ec-e7c0-6f2c)
**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.
The eaf git log commit id is "81db16546c946f10a9dc24ea2ef5e72f54128ee7", I am sure it is on the latest master branch.
Step to reproduce:
1. eaf-open a pdf file.
2. choose some text and annote with eaf-proxy-add_annot_highlight.
3. hover the cursor on one annote and execute eaf-proxy-add_annot_strikeout_or_delete_annot
4. The minibuffer echo [EAF/pdf-viewer] Cannot execute function: add_annot_strikeout_or_delete_annot (b332-ddea-45c1-3fba-43ec-e7c0-6f2c)
**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM: Arch 5.12.9
 - Versions of Dependencies: PyQt5-5.15.4 PyQt5-sip-12.9.0 PyQtWebEngine-5.15.4
 - M-x emacs-version: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)

**Screenshots**

**Additional context**

**Comment by manateelazycat** [comment]
@luhuaei any idea?

**Comment by luhuaei** [comment]
> choose some text and annote with eaf-proxy-add_annot_highlight.
> hover the cursor on one annote and execute eaf-proxy-add_annot_strikeout_or_delete_annot

@Jousimies When you hover the annot, minibuffer is has `[EAF/pdf-viewer] [d]Delete Annot [e]Edit Annot` message? I test myself pdf, delete annot and add annot is normal. Could provide a pdf document to reproduce this problem? Thanks.

**Comment by Jousimies** [comment]
@luhuaei Yes, when I hover the annot, minibuffer display `[EAF/pdf-viewer] [d]Delete Annot [e]Edit Annot` message. 

If I press d, the cursor will move to the right corner of screen and nothing happened, the annot cannot be deleted.

If I M-x eaf-proxy-add_annot_strikeout_or_delete_annot, minibuffer echo `[EAF/pdf-viewer] Cannot execute function: add_annot_strikeout_or_delete_annot (97f6-8a7e-db2d-3590-a385-ac4e-fea3)`. 
Then C-x b to *eaf* buffer, there is a Traceback, AttributeError: 'NoneType' object has no attribute 'parent'.

I attached the pdf below, and in the pdf, the title higlight annot was highlited with eaf.
[2019_Ghali_Gayed.pdf](https://github.com/manateelazycat/emacs-application-framework/files/6624601/2019_Ghali_Gayed.pdf)

**Comment by luhuaei** [comment]
> @luhuaei Yes, when I hover the annot, minibuffer display `[EAF/pdf-viewer] [d]Delete Annot [e]Edit Annot` message.
> 
> If I press d, the cursor will move to the right corner of screen and nothing happened, the annot cannot be deleted.
> 
> If I M-x eaf-proxy-add_annot_strikeout_or_delete_annot, minibuffer echo `[EAF/pdf-viewer] Cannot execute function: add_annot_strikeout_or_delete_annot (97f6-8a7e-db2d-3590-a385-ac4e-fea3)`.
> Then C-x b to _eaf_ buffer, there is a Traceback, AttributeError: 'NoneType' object has no attribute 'parent'.
> 
> I attached the pdf below, and in the pdf, the title higlight annot was highlited with eaf.
> [2019_Ghali_Gayed.pdf](https://github.com/manateelazycat/emacs-application-framework/files/6624601/2019_Ghali_Gayed.pdf)

Sorry, I use the pdf don't reproduce this problem. 
![Peek 2021-06-11 19-32](https://user-images.githubusercontent.com/46041665/121680403-19455980-caec-11eb-985a-8f4b624f3a39.gif)

**Comment by Jousimies** [comment]
I have re-checkd my configuration and re-installed eaf and dependency. so far the problem is still there.

May need to dig into it.  Anyway, Thanks.

**Comment by luhuaei** [comment]
> I have re-checkd my configuration and re-installed eaf and dependency. so far the problem is still there.
> 
> May need to dig into it. Anyway, Thanks.

:joy: If you re-create other annot or use other pdf document, problem still? Thanks.

**Comment by Jousimies** [comment]
Yes, The problem is still there, no matter I re-create another annot or use other pdf file.

In buffer.py line 486, I see you comment "# Must assign annot parent, else deleteAnnot cause parent is None problem."

Did it related to the problem I face ? AttributeError: 'NoneType' object has no attribute 'parent'. 

Or, do I need to install some other dependencies?

**Comment by luhuaei** [comment]
Yes, annot must has parent, else cause error when delete this annot.

But, each new adding annot will setting it parent. (line  1148  `new_annot.parent = page`). 
Maybe here page is None, you can print it to debug this problem.

Thanks.


-  [Annot.parent](https://pymupdf.readthedocs.io/en/latest/annot.html#Annot.parent)

**Comment by zbelial** [comment]
IMO it must be that `hover_annot` returns a None as annot, but it's hard for me to tell why this happens. Maybe an exception is triggered, so this function returns None, None at the last. 

You can add some  print statements to help figure out what happens.

PS. You should press `M-d` but not just a `d` to delete an annot when hovering on it. The message in minibuffer is misleading.

**Comment by Jousimies** [comment]
@luhuaei @manateelazycat @zbelial I think I have found what happened, It related to the desktop manager, i3wm. 

I print the annot type whthin `hover_annot` and `annot_handler` . During the `hover_annot` , the type is `fitz.fitz.Annot`,  another always retrun `Nonetype`. 

First, I hover the curson on the highlight annot, then try to press M-d. But when I press M, the cursor will move to the right-bottom corner of my screen. So,  there do not have any annot where the cursor hover.  

Don't know how to fix this bug, wait for your hard work.

**Comment by luhuaei** [comment]
> Maybe an exception is triggered, so this function returns None, None at the last.

If exception is triggered, the `*eaf*` buffer will print the error. But above debug message don't exception error information.

> But when I press M, the cursor will move to the right-bottom corner of my screen. 

:joy: If you cursor move to right-bottom, `hover_annot` will return `None` (some possible return `fitz.fitz.Annot` if right-bottom has normal annot)

**Comment by manateelazycat** [comment]
> @luhuaei @manateelazycat @zbelial I think I have found what happened, It related to the desktop manager, i3wm.
> 
> I print the annot type whthin `hover_annot` and `annot_handler` . During the `hover_annot` , the type is `fitz.fitz.Annot`, another always retrun `Nonetype`.
> 
> First, I hover the curson on the highlight annot, then try to press M-d. But when I press M, the cursor will move to the right-bottom corner of my screen. So, there do not have any annot where the cursor hover.
> 
> Don't know how to fix this bug, wait for your hard work.

@luhuaei 

i3wm窗口器必须将鼠标移动到户外管理里，要不键盘无法工作。

同时，我觉得每次鼠标Hover的时候可以把Hover对应的Annotation保存到一个临时变量中，当遇到i3wm这种会返回None的情况，用最后一次保存的临时变量来处理。

The i3wm window manager must move the mouse to the corner of screen, otherwiwse the keystroke cannot work.

At the same time, I think that every time the mouse is hovered, the Annotation corresponding to the Hover can be saved to a temporary variable. When encountering the situation that i3wm will return None, use the last saved temporary variable to handle it.

**Comment by zbelial** [comment]
Here is a patch that does exactly what @manateelazycat said in his previous comment, I've tested it last night and it works for me. Could you install it and give it a try? @Jousimies 

``` diff
diff --git a/app/pdf-viewer/buffer.py b/app/pdf-viewer/buffer.py                                                                                                     
index eb3cb9e..946f157 100755                                                                                                                                        
--- a/app/pdf-viewer/buffer.py                                                                                                                                       
+++ b/app/pdf-viewer/buffer.py                                                                                                                                       
@@ -641,6 +641,8 @@ class PdfViewerWidget(QWidget):                                                                                                                  
         self.remember_offset = None                                                                                                                                 
                                                                                                                                                                     
         self.last_hover_annot_id = None                                                                                                                             
+        self.hovered_annot = None                                                                                                                                   
+        self.hovered_annot_page = None                                                                                                                              
                                                                                                                                                                     
         self.start_page_index = 0                                                                                                                                   
         self.last_page_index = 0                                                                                                                                    
@@ -1245,18 +1247,20 @@ class PdfViewerWidget(QWidget):                                                                                                              
             if not annot:                                                                                                                                           
                 return None, None                                                                                                                                   
                                                                                                                                                                     
+            self.hovered_annot_page = page                                                                                                                          
+                                                                                                                                                                    
             annots = []                                                                                                                                             
             while annot:                                                                                                                                            
                 annots.append(annot)                                                                                                                                
                 annot = annot.next                                                                                                                                  
                                                                                                                                                                     
             is_hover_annot = False                                                                                                                                  
-            current_annot = None                                                                                                                                    
+            self.hovered_annot = None                                                                                                                               
             for annot in annots:                                                                                                                                    
                 if fitz.Point(ex, ey) in annot.rect:                                                                                                                
                     # message_to_emacs(annot.info["content"])                                                                                                       
                     is_hover_annot = True                                                                                                                           
-                    current_annot = annot                                                                                                                           
+                    self.hovered_annot = annot                                                                                                                      
                     opacity = 0.5
                     message_to_emacs("[d]Delete Annot [e]Edit Annot")
                 else:
@@ -1279,7 +1283,7 @@ class PdfViewerWidget(QWidget):
                 if QToolTip.isVisible():
                     QToolTip.hideText()
 
-            return page, current_annot
+            return self.hovered_annot_page, self.hovered_annot
         except Exception as e:
             print("Hove Annot: ", e)
             return None, None
@@ -1290,14 +1294,13 @@ class PdfViewerWidget(QWidget):
         self.update()
 
     def annot_handler(self, action=None):
-        page, annot = self.hover_annot()
-        if annot.parent:
+        if self.hovered_annot and self.hovered_annot.parent:
             if action == "delete":
-                page.deleteAnnot(annot)
+                self.hovered_annot_page.deleteAnnot(self.hovered_annot)
                 self.save_annot()
             if action == "edit":
-                self.edited_page_annot = (page, annot)
-                atomic_edit(self.buffer_id, annot.info["content"].replace("\r", "\n"))
+                self.edited_page_annot = (self.hovered_annot_page, self.hovered_annot)
+                atomic_edit(self.buffer_id, self.hovered_annot.info["content"].replace("\r", "\n"))
 
     def update_annot_text(self, annot_text):
         page, annot = self.edited_page_annot
```

**Comment by Jousimies** [comment]
@zbelial  The patch really work, I can open pdf and press M-d to delete highlight annot. But, at the same time, the *eaf*  buffer displayed `mupdf: object out of range (364 0 R); xref size 0`.

Another problem is after I press M-d to delete highlight annot,  the minibuffer echo `Detected pdf has been changed, refreshing buffer`, then do some actions like switching buffer or scrool the page, the *eaf* buffer printed `Process *eaf* segmentation fault (core dumped)`.  Do not know what caused the problem.

**Comment by luhuaei** [comment]
>  after I press M-d to delete highlight annot, the minibuffer echo Detected pdf has been changed, refreshing buffer

This normal. when you delete annot, will trigger document save.

**Comment by zbelial** [comment]
> The patch really work, I can open pdf and press M-d to delete highlight annot. But, at the same time, the _eaf_ buffer displayed `mupdf: object out of range (364 0 R); xref size 0`.

@Jousimies Be closer to enjoying EAF :). But I didn't see this error message here. What's your python-mupdf version? Does it always happen when you delete an annotation? 

As of the core dump, you can follow the readme or the wiki to try to figure out the problem or provide steps that can reproduce the problem.

**Comment by manateelazycat** [comment]
@Jousimies Any luck?

**Comment by Jousimies** [comment]
> > The patch really work, I can open pdf and press M-d to delete highlight annot. But, at the same time, the _eaf_ buffer displayed `mupdf: object out of range (364 0 R); xref size 0`.
> 
> @Jousimies Be closer to enjoying EAF :). But I didn't see this error message here. What's your python-mupdf version? Does it always happen when you delete an annotation?
> 
> As of the core dump, you can follow the readme or the wiki to try to figure out the problem or provide steps that can reproduce the problem.

The version of python-mupdf is 1.18.14.

**Comment by Jousimies** [comment]
> @Jousimies Any luck?

Sorry for long time no response. 

Today, I upgrade to dee219fb67b1fc6b0a5f540b6cc89d2a71d823d8. After I open a pdf with eaf-open, the *eaf* aborted with I press any key.

`EAF process starting...
Session is not restored, as no data about /home/dn/Seafile/Storage.PDF/2019/2019_Ghali_Gayed.pdf.
Traceback (most recent call last):
  File "/home/jousimies/emacs/site-lisp/extensions/emacs-application-framework/core/utils.py", line 58, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/usr/share/emacs/jousimies/extensions/emacs-application-framework/eaf.py", line 346, in execute_function
    buffer.execute_function(function_name)
  File "/home/jousimies/emacs/site-lisp/extensions/emacs-application-framework/core/buffer.py", line 272, in execute_function
    getattr(self, function_name)()
  File "/home/jousimies/emacs/site-lisp/extensions/emacs-application-framework/core/buffer.py", line 182, in move_cursor_to_corner
    QCursor().setPos(screen, screen.size().width(), screen.size().height())
TypeError: arguments did not match any overloaded call:
  setPos(int, int): argument 1 has unexpected type 'QScreen'
  setPos(QPoint): argument 1 has unexpected type 'QScreen'

Process *eaf* aborted (core dumped)`

**Comment by manateelazycat** [comment]
> > @Jousimies Any luck?
> 
> Sorry for long time no response.
> 
> Today, I upgrade to [dee219f](https://github.com/manateelazycat/emacs-application-framework/commit/dee219fb67b1fc6b0a5f540b6cc89d2a71d823d8). After I open a pdf with eaf-open, the _eaf_ aborted with I press any key.
> 
> `EAF process starting...
> Session is not restored, as no data about /home/dn/Seafile/Storage.PDF/2019/2019_Ghali_Gayed.pdf.
> Traceback (most recent call last):
> File "/home/jousimies/emacs/site-lisp/extensions/emacs-application-framework/core/utils.py", line 58, in on_signal_received
> self._func(obj, *args, **kwargs)
> File "/usr/share/emacs/jousimies/extensions/emacs-application-framework/eaf.py", line 346, in execute_function
> buffer.execute_function(function_name)
> File "/home/jousimies/emacs/site-lisp/extensions/emacs-application-framework/core/buffer.py", line 272, in execute_function
> getattr(self, function_name)()
> File "/home/jousimies/emacs/site-lisp/extensions/emacs-application-framework/core/buffer.py", line 182, in move_cursor_to_corner
> QCursor().setPos(screen, screen.size().width(), screen.size().height())
> TypeError: arguments did not match any overloaded call:
> setPos(int, int): argument 1 has unexpected type 'QScreen'
> setPos(QPoint): argument 1 has unexpected type 'QScreen'
> 
> Process _eaf_ aborted (core dumped)`

Which Qt version do you use?

**Comment by Jousimies** [comment]
@manateelazycat  
PyQt5                         5.12.3
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.9.0
PyQtWebEngine                 5.12.1
PyQtWebEngine-Qt5             5.15.2
QtAwesome                     1.0.3
QtPy                          1.9.0

**Comment by Jousimies** [comment]
I install xfce4, pdf annotation can be deleted.

So, I will close this issue.
