### ISSUE TITLE
Consider using qutebrowser instead of making a browser from scratch

### ISSUE THREAD

**Issue by winmillwill** [manateelazycat/emacs-application-framework#7]
It's a PyQt webkit browser that I'm using to submit this issue. It has everything mentioned in the TODO doc.

**Comment by manateelazycat** [comment]
@winmillwill I research it yesterday, qutebrowser is cool, but it's too compllicate, hard to integrate into eaf framework.

**Comment by manateelazycat** [comment]
@winmillwill I give up after i try.
Anyway, if someone can modify qutebrowser , i will merge pull request.

Thanks for your suggestion.
