### ISSUE TITLE
Jump to link breaks on epub file

### ISSUE THREAD

**Issue by c1-g** [manateelazycat/emacs-application-framework#706]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.
```
Traceback (most recent call last):
  File "/usr/home/i/.emacs.d/site-lisp/emacs-application-framework/app/pdf-viewer/buffer.py", line 782, in paintEvent
    qpixmap = self.get_page_pixmap(index, self.scale * hidpi_scale_factor, self.rotation)
  File "/usr/home/i/.emacs.d/site-lisp/emacs-application-framework/app/pdf-viewer/buffer.py", line 720, in get_page_pixmap
    self.jump_link_key_cache_dict.update(page.mark_jump_link_tips(self.emacs_var_dict["eaf-marker-letters"]))
  File "/usr/home/i/.emacs.d/site-lisp/emacs-application-framework/app/pdf-viewer/buffer.py", line 525, in mark_jump_link_tips
    links = self.page.getLinks()
  File "/usr/local/lib/python3.8/site-packages/fitz/__init__.py", line 161, in deprecated_function
    return fname(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/fitz/utils.py", line 786, in get_links
    linkxrefs = [x for x in page.annot_xrefs() if x[1] == PDF_ANNOT_LINK]
TypeError: 'NoneType' object is not iterable

Process *eaf* abort trap
```
**Describe the bug**
EAF immediately abort the pdf-viewer process when call jump to link function.

**To Reproduce**
```eaf-open``` an epub file.
Use as usual until there's a link in the current page.
Call jump to link.

**Expected behavior**
Jump to link works as expected

**Versions (please complete the following info):**
 - Distro and DE/WM:
 FreeBSD 13.0-RELEASE
 EXWM 0.24
 - Versions of Dependencies:
 epc                 0.0.5
 PyMuPDF             1.18.14
 PyGetWindow         0.0.9
 nodejs              16.2.0
 npm                 6.14.8
 wmctrl              1.07_7
 
 - M-x emacs-version:
```GNU Emacs 28.0.50 (build 1, amd64-portbld-freebsd13.0, GTK+ Version 3.24.29, cairo version 1.17.4)```
**Screenshots**

**Additional context**
It works fine when called on a page without any links

**Comment by manateelazycat** [comment]
@luhuaei Can you help fix this issue?

**Comment by luhuaei** [comment]
PyMupdf many function only support PDF file type. So Not PDF file type calling will cause error.
