### ISSUE TITLE
Pdf viewer: background color

### ISSUE THREAD

**Issue by antoine-levitt** [manateelazycat/emacs-application-framework#725]
The background color picked by the pdf viewer is not always good (here it's dark black). It would be good to set it to `(face-background 'default nil)` by default. I didn't find how to do this; I saw something in https://github.com/manateelazycat/emacs-application-framework/blob/master/app/pdf-viewer/buffer.py#L726 referring to eaf-emacs-theme-background-color, but setting this didn't work.

**Comment by MatthewZMD** [comment]
> (face-background 'default nil)

It is currently set using `(frame-parameter nil 'background-color)`. At least on my system, these two commands give me the same output, what's the difference?

**Comment by antoine-levitt** [comment]
The two commands do give the same results, but for me that isn't the color that gets picked as the pdf background. I have "#263238" (light grey) as background, but pdf backgrounds are complete black

**Comment by MatthewZMD** [comment]
Check your `eaf-pdf-dark-mode` in the `eaf-var-list`, make sure to set it to `"follow"` using `(eaf-setq eaf-pdf-dark-mode "follow")`

**Comment by antoine-levitt** [comment]
I tried setting to follow, didn't change. Maybe I should be clearer: I'm not talking about the background of the pdf itself, but rather the "padding" on the margins. See attached screenshot.
![Screenshot at 2021-07-24 13-23-16](https://user-images.githubusercontent.com/88065/126866915-5367f29e-5864-44a5-956b-15f4d066438b.png)
It would be nice if that color followed the pdf background color.

**Comment by antoine-levitt** [comment]
Actually following the pdf background color could be confusing because it would not be clear where the pdf ends. I can think of two useful options here: always taking the emacs background color, or taking the color of the pdf background. Taking the emacs background color looks like a reasonable default (although it would be even nicer to have it as an option)

**Comment by manateelazycat** [comment]
@MatthewZMD render background it's now hard code at https://github.com/manateelazycat/emacs-application-framework/blob/d102acecf5b037052780c19b025144ff4639b4b4/app/pdf-viewer/buffer.py#L44

**Comment by manateelazycat** [comment]
> Actually following the pdf background color could be confusing because it would not be clear where the pdf ends. I can think of two useful options here: always taking the emacs background color, or taking the color of the pdf background. Taking the emacs background color looks like a reasonable default (although it would be even nicer to have the choice of taking the color of the pdf background as an option)

If margin color same as pdf background color, user will confuse.

I haven't thought how to customize the color of margin.

@MatthewZMD How do you think?

**Comment by MatthewZMD** [comment]
> > Actually following the pdf background color could be confusing because it would not be clear where the pdf ends. I can think of two useful options here: always taking the emacs background color, or taking the color of the pdf background. Taking the emacs background color looks like a reasonable default (although it would be even nicer to have the choice of taking the color of the pdf background as an option)
> 
> If margin color same as pdf background color, user will confuse.
> 
> I haven't thought how to customize the color of margin.
> 
> @MatthewZMD How do you think?
> 
> 

I agree, the margin has its own black color that differentiate Emacs background from the PDF background.

**Comment by manateelazycat** [comment]
@antoine-levitt git pull and try new option ```(eaf-setq eaf-buffer-background-color "#FF0000")```

**Comment by antoine-levitt** [comment]
This is great, thank you!
