### ISSUE TITLE
Please seperate eaf core and eaf apps into seperate packages

### ISSUE THREAD

**Issue by QiangF** [manateelazycat/emacs-application-framework#726]
Eaf is a versatile framework, as time goes by, eaf apps will keep increasing. However, not every people needs all those apps. Currently all apps are bundled into one package, which makes eaf looks big. Because I am putting eaf in my dotfile repo, the files to keep an eye on is too many, and I can't just pick those files I need, because eaf.el requires eaf-mindmap, eaf-mail etc.

I would suggest making eaf-core and those eaf-apps two seperate repos/packages, and all those keybinding being put in the user's customization file. That will make it easier for users like me to get updated on the most relevant development.

Thank you very much for your consideration!

**Comment by manateelazycat** [comment]
API is not stable enough now, I will do this job when API stable (maybe next year).

Thanks for suggestion.

**Comment by MatthewZMD** [comment]
Yes, I've thought about this quite a while ago, but the EAF core API is still constantly evolving, the package maintenance will be much more troublesome if the EAF core and app are separated, so we haven't done it yet.

For anyone in the future discovering this issue and wants this to happen, please comment or give a 👍🏼 to this issue, so we'll know how many people really is annoyed by it.

**Comment by MatthewZMD** [comment]
This has been implemented in the latest EAF master.
