### ISSUE TITLE
Allow user to set the maximum size of browser cached site data, and add a function to clear that cache

### ISSUE THREAD

**Issue by QiangF** [manateelazycat/emacs-application-framework#729]
I have found the cache is stored in ~/.local/share/eaf.py/QtWebEngine/Default, but I can't find cache size setting and clear cache commands. 
From my own experience with other browsers, if cached size of webpages increases over a threshold, browsers become slow and freeze sometimes,  a function to clear cache and keep site login data is a must have feature for a browser.
Maybe some cache-related settings can be borrowed from qutebrowser:
https://github.com/qutebrowser/qutebrowser/issues/666

**Comment by manateelazycat** [comment]
Browser slow? 

Can you use data to prove your point?

**Comment by QiangF** [comment]
OK. I am not so sure. It's probably not so important anyway.
