### ISSUE TITLE
Keep emacs editing behavior in browser text input box

### ISSUE THREAD

**Issue by QiangF** [manateelazycat/emacs-application-framework#730]
To do that in Firefox, I use xkeysnail. xkeysnail doesn't know the focus point in a browser, with that knowledge, eaf-browser should do it better. However, currently the line editing key bindings are binded to functions that should not be active during text editing.

I would suggest an implementation like this: make a buffer local variable that changes state when focus is in a text box, if the variable is true, simulate key binding according to the following table:

    original: transformed
    C-b: left
    C-f: right
    C-p: up
    C-n: down
    M-b: C-left
    M-f: C-right
    C-a: home
    C-e: end
    C-d: delete
    M-d: C-delete

**Comment by MatthewZMD** [comment]
Try M-e in an EAF browser input box.

**Comment by QiangF** [comment]
C-n and C-p is useful when selecting item in a pull down list.
