### ISSUE TITLE
Auto accept link hint on unique match

### ISSUE THREAD

**Issue by QiangF** [manateelazycat/emacs-application-framework#731]
The link opening with hint in eaf web browser is not efficient enough, user has to type a return key to finish the jump, which is not necessary in other browser plugins like surfingkey. If eaf alreay has the input and it is the only match, is it possible to omit the last return key?

**Comment by MatthewZMD** [comment]
Because EAF uses the minibuffer prompt for the link hint keys, it needs to enter. This is by design of the minibuffer prompt.

**Comment by QiangF** [comment]
What about using a real buffer? I am not good enough at elisp, but in Ivy the current user input is saved in a variable.

**Comment by MatthewZMD** [comment]
> What about using a real buffer? I am not good enough at elisp, but in Ivy the current user input is saved in a variable.

I don't understand this sentence. PR always welcome.

**Comment by QiangF** [comment]
> Because EAF uses the minibuffer prompt for the link hint keys, it needs to enter. This is by design of the minibuffer prompt.

You said it's using the minibuffer that makes the enter necessary, so I was suggesting using a normal buffer that may save you some typing of enters. I will PR when I am good enough at elisp. Thank you for your great work though.

**Comment by manateelazycat** [comment]
I know you want press key to active link and don't need press ENTER, just like vimum in Chrome.

It's need write many javascript code.

Anyway, PR are welecome.

**Comment by MatthewZMD** [comment]
This is correct, this requires a lot of JavaScript work to achieve something that is questionably better (without pressing enter to confirm a link is prone to typo and error) than the current minibuffer approach is just not convincing enough for us to implement it. If you really want this approach, please submit a pull request.

**Comment by manateelazycat** [comment]
I think this feature has implementation in newest version.
