### ISSUE TITLE
keep hints and open multiple link hints in one shot

### ISSUE THREAD

**Issue by QiangF** [manateelazycat/emacs-application-framework#733]
This is just another two ideas for a better keyboard driving experience: 

1. extended hint mode: ie. after user input and the corresponding link opened in a new buffer, keep the hints displayed on the original page, so the user can go back and start opening other links immediately without summon the hints one more time. This is useful in a search result page, often there are multiple links that are interesting, pressing "M-B" again and again is craziness.

2. open multiple links with hint list seperated by commas, and hint globbing: Because web page take time to load under slow connection, some people like to open multiple links on a page in the background and read them later. You know we use the minibuffer for hint input, the input is only processed after a return key, this can be utilized to select multiple hints, e.g. an input like "h,j,a{b,c}" will open link hint "h","j","ab" and "ac".

Feel free to close this if none of you are interested.

**Comment by c1-g** [comment]
This sounds exactly like the "rapid hints" feature of qutebrowser. And since it also uses python and qtwebengine like us. I think it shouldn't be too difficult?? 
https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/browser/hints.py

**Comment by MatthewZMD** [comment]
I'd suggest move feature request discussions to the discussion page, to save resource for the actual issue discussion.

Personally I think this is a very niche feature, it will not be prioritized. If you really like this idea, please submit a PR.
