### ISSUE TITLE
Fuse eaf variables with emacs variables

### ISSUE THREAD

**Issue by antoine-levitt** [manateelazycat/emacs-application-framework#734]
It is pretty annoying to not be able to set eaf variables directly with `(setq)`, define keybindings, etc. This also doesn't benefit from emacs's great self-documentation features. Would it be possible to set up a bidirectional bridge between emacs and eaf variables? Or simply merge the two and have the python code look into emacs variables? On the lisp side there ishttps://www.gnu.org/software/emacs/manual/html_node/elisp/Watching-Variables.html to keep the variables in sync, if that helps.

**Comment by MatthewZMD** [comment]
Yes it is possible, however it would be very troublesome to tell EAF which Emacs variables to pass to the Python side, at least not in an elegant way. 

For any documentation, please refer to the Wiki.

**Comment by antoine-levitt** [comment]
By documentation I meant eg describe-variable & co, which are very convenient. I was thinking of the variables in eaf-var-list, which basic users are more likely to interact with.

**Comment by MatthewZMD** [comment]
> By documentation I meant eg describe-variable & co, which are very convenient. I was thinking of the variables in eaf-var-list, which basic users are more likely to interact with.

Yes, I do understand that. The reason it is currently in the `eaf-var-list` alist is the simplicity to pass every variable EAF cares about to the Python side - you just pass the entire list. It definitely has this drawback of lacking documentation.

**Comment by c1-g** [comment]
@MatthewZMD Have you considered using `defcustom` with a special `:set` function that will append them to `eaf-var-list` every time their value is set to define those variables in Elisp? And since these variables aren't technically in use for elisp we could rename them with eaf-py-.... prefix.

Also, since this really isn't an "issue" why not move this to Discussion?

**Comment by MatthewZMD** [comment]
I have not considered before, I will look into it when I have time.

**Comment by c1-g** [comment]
Hi, apparently I tried this,
```
(defcustom eaf-browser-enable-adblocker t
  "Whether to enable adblocker in EAF's browser app or not."
  :type 'boolean
  :set 'eaf-set)
```
and it just works.
So we can pretty much convert everything in the default `eaf-var-list` to this form, ideally in their respectively .el file.

**Comment by antoine-levitt** [comment]
Wouldn't that be even more confusing? Then if you do `(setq eaf-browser-enable-adblocker nil)` in your .emacs it wouldn't get passed to eaf.

**Comment by c1-g** [comment]
Since it's `defcustom` you are supposed to set its value via  `(customize-set-variable 'eaf-browser-enable-adblocker nil)`  or through the customize interface but yeah, this might cause an issue if users choose to use `setq` instead.

**Comment by manateelazycat** [comment]
git pull newest version, eaf-setq has remove now.

We can use ```get_emacs_var("var-name")``` to fetch elisp var value at Python process.

**Comment by antoine-levitt** [comment]
Awesome, well done!
