### ISSUE TITLE
Can you please guide on adding custom widgets?

### ISSUE THREAD

**Issue by afidegnum** [manateelazycat/emacs-application-framework#74]
I m trying to build an svg browser and editor... which will allow me render svg from plantuml or graphvz. after roaming from various sources i remember you had something similar which is able to render Qt into emacs buffer, 

can you please advise on how can i perform the same thing to display the graph engine into emacs buffer ?

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/emacs-application-framework/blob/master/docs/HACKING.md

**Comment by afidegnum** [comment]
can something like that be done on c++ aside python?

**Comment by manateelazycat** [comment]
no current just support python,python is enough IMO
