### ISSUE TITLE
创建 app 时不要将模块路径写死

### ISSUE THREAD

**Issue by xhcoding** [manateelazycat/emacs-application-framework#748]
eaf 里下面这行代码创建 app：
```python
self.create_app(buffer_id, str(url), "app.{0}.buffer".format(str(app_name)), str(arguments))
```
module_path `app.{0}.buffer` 是写死的，导致 app 的入口文件只能放在 emacs-application-framework 的app/{app_name} 目录下。

希望提供一个机制能够根据 app-name 指定 module_path ，这样 app 就可以不用放在这个仓库里

**Comment by manateelazycat** [comment]
现在完全独立目录还有很多接口要改，这个issue先放着吧。

现在底层接口还没有完全稳定，不适合分app出去，时机不对

**Comment by manateelazycat** [comment]
1. 要把 Python 这边的所有 module_path 都重构以后才可以安全的做 app 路径分离处理。
2. 除开 module_path 外，dark-mode 部分的代码也依赖 app_name 的处理。

最少要把这两点都处理干净以后，才不会出现问题, app.{0}.buffer 只是表象的问题。

**Comment by manateelazycat** [comment]
moudle_path 现在都重构的差不多了，module_path 只存在 eaf.py 中，app 里面还有 app.browser.buffer 和 app.org-previewer.buffer 这两个值。

最近比较忙，估计要这个月才能完成 “任意路径加载EAF app“ 的工作。

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/emacs-application-framework/commit/57ca9eb91583ef52f6f5daf19ade56705ad81bd3
