### ISSUE TITLE
Could not load the Qt platform plugin "xcb" in "" even though it was found

### ISSUE THREAD

**Issue by zxcwindy** [manateelazycat/emacs-application-framework#75]
*eaf* error message
-----------------------------------------------------
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
-----------------------------------------------------
slackware14.2
emacs26.1

**Comment by sscarecrow** [comment]
How did you solve this problem?
