### ISSUE TITLE
vue-demo 无法插入图片

### ISSUE THREAD

**Issue by ShaoChenHeng** [manateelazycat/emacs-application-framework#752]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.

**Describe the bug**
我尝试在vue-demo中插入图片，但是图片无法在emacs上显示。

**To Reproduce**
我将App.vue修改成了这个样子。
```vue
<template>
  <div id="app">
    <img :src= "pic">
    <HelloWorld msg="EAF can now use Vue.js to write applications!"/>
  </div>
</template>

<script>
 import HelloWorld from './components/HelloWorld.vue'

 export default {
   name: 'App',
   components: {
     HelloWorld
   },
   mounted() {
   },
   data() {
     return {
       pic: require('@/assets/logo.png')
     }
   }
 }
</script>
```
然后在我的终端上执行`npm run serve`，在我的浏览器打开http://localhost:8080

这时是能够在浏览器上正常显示图片的。

我在终端上执行`npm run build`，再到emacs里`M-x eaf-open-vue-demo`，图片却无法正常显示。

我还尝试过直接在eaf的broser里打开，也就是在我的终端上执行`npm run serve`后，打开emacs执行`M-x eaf-open-broser http://localhost:8080/`，这时图片是能在eaf的broser上正常显示的。

**Expected behavior**
在终端上执行`npm run build`，再到emacs里`M-x eaf-open-vue-demo`，图片应该是要正常显示的。

**Versions (please complete the following info):**
 - Distro and DE/WM:Ubuntu 20.04.2 LTS
 - Versions of Dependencies:
    npm 6.14.5
    @vue/cli 4.5.13
    
 - M-x emacs-version:
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian

**Screenshots**
在emacs上显示效果。

![pic1](https://raw.githubusercontent.com/ShaoChenHeng/Summer2021/main/pic1.png)

在浏览器上显示效果

![pic2](https://raw.githubusercontent.com/ShaoChenHeng/Summer2021/main/pic2.png)

**Additional context**
我还尝试过这样子写，也无法在emacs上显示图片。
```vue
<template>
  <div id="app">
    <img src= "./assets/logo.png">
    <HelloWorld msg="EAF can now use Vue.js to write applications!"/>
  </div>
</template>
```

**Comment by manateelazycat** [comment]
请参考 music-player 的 icon 组件，支持SVG图片内嵌。

或者通过 ```self.buffer_widget.execute_js``` 调用Vue组件的JavaScript函数（需要事先在 mounted 函数中通过 window.foo = this.foo 的形式注入JavaScript函数）的方式告诉Vue组件图片存储的绝对路径，Python端运行时的绝对路径可以通过 __file__ 属性来获得。

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/eaf-file-manager/blob/3f3941575fbf8a2d30a9d98760bf13f72fe4f83a/src/components/Main.vue#L20

https://github.com/emacs-eaf/eaf-file-manager/blob/3f3941575fbf8a2d30a9d98760bf13f72fe4f83a/src/components/Main.vue#L345

看这两个链接，确保图片放到 assets 目录下，同时定义一个函数直接 ```return "/home/user/repo/src/assets/logo.png``` 返回图片路径即可。
