### ISSUE TITLE
Please do not bundle third-party libraries

### ISSUE THREAD

**Issue by tarsius** [manateelazycat/emacs-application-framework#757]
If at all possible, then a repository used to maintain an Emacs package should not bundle any third-party libraries.

Bundling external dependencies might not cause any issues for users who install the package from Melpa, because packages distributed there can filter out unwanted libraries. But some people (including myself) run packages directly from their repositories (e.g. because that makes it much easier to contribute).

For such users the bundled library may end up on the `load-path`, possibly before the independently installed upstream version.  As a result some outdated version can end up being loaded and that can be very confusing and hard to debug.

I recommend that you never bundle any third-party libraries.  If that is not possible, then I recommend that you put those libraries in a separate directory and alongside a file named `.nosearch`. The existence of this file instructs some tools (such as `normal-top-level-add-subdirs-to-load-path` and the tools that I use to maintain the Emacsmirror) to ignore the containing directory.

Thanks for considering this!

<sub>I have written similar messages many many times so I now [use a template](https://help.github.com/en/github/writing-on-github/working-with-saved-replies). I try to adjust it to match each individual case but it might still not apply 100% in all cases.</sub>

**Comment by manateelazycat** [comment]
No, I haven't add ```normal-top-level-add-subdirs-to-load-path```, I use my own ```eaf-add-subdirs-to-load-path```, because I need it load elisp file under directory ```emacs-application-framework``` and not scan any **node_modules** directory (it will slow down Emacs start speed).

normal-top-level-add-subdirs-to-load-path can't skip **node_modules** as I know.

**Comment by tarsius** [comment]
I would like to elaborate on the core part of my request.

> For such users the bundled library may end up on the `load-path`, possibly before the independently installed upstream version.  As a result some outdated version can end up being loaded and that can be very confusing and hard to debug.

You have recently decided that it is more convenient for you if you include the external dependencies into the repository instead of having to install them externally using `package.el` (or some other package manager). Maybe you also think that this is more convenient for the users of your package, and maybe for some of them it really is.

But put yourself in the shoes of an inexperienced user who has already installed `deferred` for some other reason before they install `eaf` without realizing that doing so installs a second copy of `deferred.el`. They then run into some bug in `deferred` and its maintainer fixes it and tells the user to update, which they do. But the bug doesn't go away! Great confusion! A lot of back and forth follows and finally, after much time has been spend on it, they somehow figure out about the second copy of `deferred.el` inside `eaf`, which has not updated yet.

To safe users and maintainers from having to go through this painful and completely avoidable pain, you should *never* bundle libraries *for the benefit of the users* of your package. If you did this for the benefit of the users then you should revert it.

If however you have done it for your own benefit and you want to keep doing it (after all **you** know that you have bundled this libraries, so it won't take you by surprise), then you should protect other users from accidentally ending up with your bundled copy on the `load-path`.

You can do that by adding the `.nosearch` file, to prevent it from *accidentally* ending up on the `load-path`. Of course since you still want it to appear on *your* `load-path` you will have to add it explicitly, but this is a small inconvenience compared to the potentially hour long mystery bug hunting that it can prevent.

**Comment by manateelazycat** [comment]
Well, I buildin epc libraries to improve EPC protocol, because EAF depend on protocol stable and effective.

I have push new patch https://github.com/manateelazycat/emacs-application-framework/commit/641c1115d72513b61482e650a0fedd8a4ba3f071 to avoid conflict with user's concurrent/deferred libraries.

**Comment by tarsius** [comment]
Thanks!

**Comment by MatthewZMD** [comment]
Yep, EAF pulls these EPC related libraries in the repo is not only for the sake of convenience in installation, but also had some and plans to have more changes to these libraries, to keep the EAF protocols stable and effective. 

Basically, we now decided to maintain a fork of these libraries. These changes may or may not ever go back to the upstream, due to the fact that the original maintainer of these packages, @kiwanami, has been *very* silent on Github with only 1 activity this year, ignoring virtually all issues and PRs raised in the past 4 years.

Your concerns are very real, Manatee changing the names do effectively solve it.

**Comment by tarsius** [comment]
> PS: Very happy to see the magit maintainer using this package!

I am not but it looks interesting and I am probably going to try it at some point.

I noticed this because I maintain the emacsmirror. I also contribute to melpa and one task that I sometimes help with in that function are "package takeovers":

An alternative to forking these packages is to become their new maintainers. Ideally you would contact @kiwanami and they would transfer the repository to you. If they don't get back to you in a reasonable time frame, then we the melpa maintainers sometimes agree to treat some fork as the new official package.

It sounds like you intend to make big changes. Do you also intend to keep backward compatibility? If not, then *maybe* a fork is the option after all.

**Comment by MatthewZMD** [comment]
> An alternative to forking these packages is to become their new maintainers. Ideally you would contact @kiwanami and they would transfer the repository to you. If they don't get back to you in a reasonable time frame, then we the melpa maintainers sometimes agree to treat some fork as the new official package, but we very much prefer it if it doesn't come to that.
> 
> It sounds like you intend to make big changes. Do you also intend to keep backward compatibility? If not, then *maybe* a fork is the option after all.

Our main priority on this fork right now is to make sure epc and its related libraries work effectively with EAF, this includes improving existing features, but may also  include removing extra features we don't care/breaking EAF things. So it is not intended to be backward compatible, even if it does currently. We might not be the best people to take over the ownership.

**Comment by tarsius** [comment]
Okay understood!
