### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QtCore'

### ISSUE THREAD

**Issue by noloop** [manateelazycat/emacs-application-framework#79]
I installed all dependencies:

**sudo pip3 install dbus-python pymupdf grip qrcode python-xlib pyqt5 pyqtwebengine**

 and when I try `eaf-open-browser RET https://www.google.com` and I get:

```
Traceback (most recent call last):
  File "/home/noloop/.emacs.d/emacs-application-framework/eaf.py", line 25, in <module>
    from app.browser.buffer import AppBuffer as NeverUsed # noqa
  File "/home/noloop/.emacs.d/emacs-application-framework/app/browser/buffer.py", line 22, in <module>
    from PyQt5.QtCore import QUrl
ModuleNotFoundError: No module named 'PyQt5.QtCore'
```

**Comment by MatthewZMD** [comment]
Try uninstall and reinstall, it worked for me
```
sudo pip uninstall pyqt5
sudo pip install pyqt5
```

**Comment by manateelazycat** [comment]
Please Check pyqt5 package is install success

You can use ipython check first, if ipython import correctly, EAF will works fine.
