### ISSUE TITLE
let `eaf-open-camera` support camera taking photograph

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#82]
I have not found any keybinding actions on `eaf-open-camera`. Can it support taking photograph and save to file?

And if it can support Emacs' built-in major-mode keybindings `[C-h m]` to list out current major-mode keybindings/commands will be helpful. I don't know whether this is possible for eaf buffer.

**Comment by MatthewZMD** [comment]
> And if it can support Emacs' built-in major-mode keybindings [C-h m] to list out current major-mode keybindings/commands will be helpful. I don't know whether this is possible for eaf buffer.

I am also looking into this

**Comment by manateelazycat** [comment]
EAF's keybinding use eaf-monitor-key-event function to capture key event, not major-mode keybinding implement.

So C-h m is not easy

**Comment by MatthewZMD** [comment]
我觉得如果能把它通过某种方式跟major mode绑定在一起的话会更方便用户调整配置，有什么idea吗

**Comment by manateelazycat** [comment]
> 我觉得如果能把它通过某种方式跟major mode绑定在一起的话会更方便用户调整配置，有什么idea吗

现在已经是自定义按键的方式了，但是EAF必须接管输入事件转发，要不是会出现很多焦点的问题。

我觉得最好的方法就是，EAF本身Elisp这端可以做一个单独的按键Popup的功能，不用依赖 C-h m

**Comment by stardiviner** [comment]
@manateelazycat 类似magit的popup按键还是挺好用的。我赞成。

**Comment by manateelazycat** [comment]
> @manateelazycat 类似magit的popup按键还是挺好用的。我赞成。

欢迎PR，不能我一个人吭哧吭哧写代码，欢迎贡献。;)

**Comment by stardiviner** [comment]
Ok, I used to use Magit's utility `transient` to write this popup keybinding for [bilibili.el](https://github.com/0xDEATHCODE/emms-bilibili)

**Comment by manateelazycat** [comment]
C-h m fixed by https://github.com/manateelazycat/emacs-application-framework/pull/96
