### ISSUE TITLE
cannot eval eaf.el on mac os 

### ISSUE THREAD

**Issue by eggcaker** [manateelazycat/emacs-application-framework#9]
when run `eval-buffer` on eaf.el got  error : 

```
Debugger entered--Lisp error: (dbus-error "No connection to bus" :session)
  signal(dbus-error ("No connection to bus" :session))
  dbus-register-signal(:session "com.lazycat.eaf" "/com/lazycat/eaf" "com.lazycat.eaf" "focus_emacs_buffer" eaf-focus-buffer)
  eval-buffer()  ; Reading at buffer position 10546
  funcall-interactively(eval-buffer)
  call-interactively(eval-buffer nil nil)
  command-execute(eval-buffer)
```

**Comment by manateelazycat** [comment]
We use Xlib and DBus perhaps won't on MacOS, i wil try to find a way to work on Mac in next week

**Comment by manateelazycat** [comment]
I have speed two days make eaf working on MacOS.

Sadly, it can't work, sorry.

Why this awesome framework can't works with MacOS?
There are mainly three obstacles:

1. I can't make dbus/python-dbus works on MacOS High Sierra
2. This framework need use X11 reparent to stick Qt5 window to emacs frame, but i don't know how to make X11 works on MacOS.
3. Qt5 QGraphicsView/QGraphicsScene can't work MacOS, specify QGraphicsVideoItem can't work.
