### ISSUE TITLE
EAF does not install due to unsupported npm

### ISSUE THREAD

**Issue by happyboy2k** [manateelazycat/emacs-application-framework#933]
I tried to install eaf via the eaf-install.py script (just executed it in a terminal).
it failed with this error message:
`npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "npm:": npm:vue-loader@16.5.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-03-21T11_57_20_324Z-debug.log
`
Then I added 
`(add-to-list 'load-path "~/.emacs.d/site-lisp/emacs-application-framework/")
(require 'eaf)`
to my .emacs file.

After starting emacs I got this error:
`Warning (initialization): An error occurred while loading ‘/home/user/.emacs’:

Symbol's function definition is void: json-parse-buffer

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
`

`$ npm --version
5.8.0

$ uname -a
Linux pc 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

$ emacs --version
GNU Emacs 26.1
Copyright (C) 2018 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

`
 
Logs:
$ cat /home/user/.npm/_logs/2022-03-21T11_57_20_324Z-debug.log
`(...)19 silly saveTree | `-- v8-compile-cache@2.3.0
19 silly saveTree +-- qwebchannel@5.9.0
19 silly saveTree +-- vue-audio-visual@2.3.0
19 silly saveTree | +-- axios@0.21.1
19 silly saveTree | `-- vue@2.6.14
19 silly saveTree `-- vue@2.6.14
20 verbose stack Error: Unsupported URL Type "npm:": npm:vue-loader@16.5.0
20 verbose stack     at unsupportedURLType (/usr/lib/nodejs/npm-package-arg/npa.js:197:15)
20 verbose stack     at fromURL (/usr/lib/nodejs/npm-package-arg/npa.js:250:13)
20 verbose stack     at Function.resolve (/usr/lib/nodejs/npm-package-arg/npa.js:71:12)
20 verbose stack     at module.exports (/usr/share/npm/lib/install/realize-shrinkwrap-specifier.js:21:14)
20 verbose stack     at BB.each (/usr/share/npm/lib/install/inflate-shrinkwrap.js:53:23)
20 verbose stack     at tryCatcher (/usr/lib/nodejs/bluebird/js/release/util.js:16:23)
20 verbose stack     at Object.gotValue (/usr/lib/nodejs/bluebird/js/release/reduce.js:155:18)
20 verbose stack     at Object.gotAccum (/usr/lib/nodejs/bluebird/js/release/reduce.js:144:25)
20 verbose stack     at Object.tryCatcher (/usr/lib/nodejs/bluebird/js/release/util.js:16:23)
20 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/nodejs/bluebird/js/release/promise.js:512:31)
20 verbose stack     at Promise._settlePromise (/usr/lib/nodejs/bluebird/js/release/promise.js:569:18)
20 verbose stack     at Promise._settlePromise0 (/usr/lib/nodejs/bluebird/js/release/promise.js:614:10)
20 verbose stack     at Promise._settlePromises (/usr/lib/nodejs/bluebird/js/release/promise.js:693:18)
20 verbose stack     at Async._drainQueue (/usr/lib/nodejs/bluebird/js/release/async.js:133:16)
20 verbose stack     at Async._drainQueues (/usr/lib/nodejs/bluebird/js/release/async.js:143:10)
20 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/nodejs/bluebird/js/release/async.js:17:14)
21 verbose cwd /home/user/.emacs.d/site-lisp/emacs-application-framework/app/music-player
22 verbose Linux 4.19.0-18-amd64
23 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
24 verbose node v10.24.0
25 verbose npm  v5.8.0
26 error code EUNSUPPORTEDPROTOCOL
27 error Unsupported URL Type "npm:": npm:vue-loader@16.5.0
28 verbose exit [ 1, true ]
´
(the logfile is actually longer but to long for my terminal to display. I hope this is enough...)

**Comment by MatthewZMD** [comment]
As the log says, you need to upgrade your npm. This is a npm error, we can't do anything to circumvent it.
