### ISSUE TITLE
pdf viewer 鼠标点击buffer 之后， 快捷键失效

### ISSUE THREAD

**Issue by mut0u** [manateelazycat/emacs-application-framework#98]
开启 pdf viewer 的时候， 如果鼠标点击pdf 对应的buffer 之后， 快捷键失效，需要点击其他的buffer 之后可以恢复正常。

使用环境是： emacs 26.2 , fedora-31 , i3wm

具体原因还没有查。

**Comment by manateelazycat** [comment]
换一下KDE的窗口管理器，我感觉是i3wm窗口管理器处理焦点有问题

**Comment by MatthewZMD** [comment]
Cannot reproduce in Manjaro KDE

**Comment by manateelazycat** [comment]
i3wm 窗口管理器的焦点问题，我不用i3wm，欢迎提交补丁兼容 i3wm

**Comment by CHANTXU64** [comment]
我也有这个问题，在Mac Browser中
